Kong/kongponents

packages/styles/forms/_checkbox-radio.scss, packages/styles/forms/_inputs.scss
Update minor styles for form elements
* Fix border for checkbox hover
* Remove invalid selector - was styling red error for required fields
=> styles(forms) update invalid and checkbox styles

docs/style-guide/utilities.md, packages/styles/_utils.scss
Adds missing flex, display, width utilities. Add `!important` to classes to ensure they take effect regardless of where the stylesheet is imported.
=> feat(styles): adds missing utilities & add important declarations 

packages/KButton/package.json
=> test(*) try publish -INTF-1522

pull_request_template.md
Removes "Version" portion of PR template, since CI autoversions kongponents.
*
↑
removing this one!
=> chore(pr): remove pr package.json checklist item

packages/KEmptyState/package.json, packages/KSkeleton/README.md, packages/KSkeleton/package.json
there wasn't an npm token on gh-actions so need to reset/bump versions.
=> chore(version) bump

cli/template/package.json, packages/KAlert/package.json, packages/KBadge/package.json, packages/KButton/package.json, packages/KCard/package.json, packages/KCheckbox/package.json, packages/KClipboardProvider/package.json, packages/KEmptyState/package.json, packages/KIcon/package.json, packages/KInput/package.json, packages/KInputSwitch/package.json, packages/KLabel/package.json, packages/KModal/package.json, packages/KPop/package.json, packages/KRadio/package.json, packages/KSkeleton/package.json, packages/KSlideout/package.json, packages/KTable/package.json, packages/KTest/package.json, packages/KToaster/package.json, packages/KToggle/package.json, packages/KoolTip/package.json, packages/Krumbs/package.json, packages/styles/package.json
Set `publishConfig` access to public:
https://github.com/lerna/lerna/tree/master/commands/publish#publishconfigaccess
=> chore(ci) npm access to public

docs/components/card.md, packages/KCard/KCard.vue
Noticed there is no defined background on KCard. Fixed background, bad `noBorder` class and added variables to change styles.
* Fixed classes
* Added css theming vars
=> fix(KCard) Updates KCard Styles

packages/KSkeleton/KSkeletonBox.vue
Fixes accidental class widths.
=> fix(skeleton): correct the width classes

docs/components/button.md, packages/KButton/KButton.vue
Adds support for disabled anchor tags as well as fixes disabled styling.
* disabled & hover styles
=> style(kbutton): fixes disabled styles

docs/components/breadcrumbs.md, packages/Krumbs/Krumbs.vue, packages/Krumbs/__snapshots__/Krumbs.spec.js.snap
Handles long krumb items by default.
* Add maxWidth
=> feat(krumbs): add maxWidth prop

packages/KIcon/__snapshots__/KIcon.spec.js.snap, packages/KIcon/icons/icn-gateway.svg, packages/KIcon/icons/icn-services.svg, packages/KIcon/icons/index.js
Reverts to previous gateway icon and moves new one to services
=> Refactor(KIcon) reverts gateway icon & adds services icon

docs/components/switch.md, packages/KInputSwitch/KInputSwitch.vue, packages/styles/forms/_switch.scss
Adds styling for disabled state and docs example
* switch.scss
* update docs
=> Style(KInputSwitch) add styling for disabled state

docs/components/alert.md, docs/components/toaster.md, packages/KAlert/KAlert.vue
Before:
After:
* Add css to wrap text.
=> style(kalert): add word break

docs/components/popover.md, packages/KPop/KPop.vue
@xitongzou check this out and lemme know what you think. Adding as part of work for dropdown
=> refactor(kpop) on-popover-click return value

yarn.lock
Bumping the yarn lock file
*Bumping the yarn lock file
=> chore(yarn): regen yarn lock

packages/KIcon/package.json
forces re-publish of kicon. I will deprecate the version prior to this once this build successfully. I will also bump major version.
=> feat(kicon): force re-publish

packages/KSegmentedControl/KSegmentedControl.vue
Should have been blue-500 @steph-kalacis
=> fix(segmentedcontrol) blue 500

packages/styles/forms/_checkbox-radio.scss
Fixes https://konghq.atlassian.net/browse/INTF-2666
*removes blue border from disabled checkboxes
=> fix(checkbox): remove blue outline border from disabled checkboxes - INTF-2666

packages/styles/package.json
NPM token was invalidated so need to push a trivial change to force publish styles up to the registry.
=> chore(style/checkbox) force publish

packages/KTest/package.json
=> fix(automation): test automation token

packages/KTest/package.json
Reverting from "automation token" to "publish token" for auto-publishing.
=> fix(automation): add publish token

packages/KTest/package.json
Remove so that publish token can work.
=> fix(automation): remove 2FA

docs/README.md
Adds example for script tag installation. Closes https://github.com/Kong/kongponents/issues/164
=> doc(Readme) Adds script tag example

docs/components/toaster.md, packages/KCard/KCard.vue
Updates some notifications in KToaster docs and fixes some typos in KCard code comments
* Updates the appearance of a notification to match the button triggering it
* Updates the message of a notification to match the others in the same section
* Fixes some typos in code comments
=> docs(KToaster): updates notification appearance to match button

docs/components/input-checkbox.md
Fixes a typo in a v-model in KCheckbox docs
* Fixes a typo in a v-model in KCheckbox docs
=> docs(KCheckbox): fix kcheckbox v-model

docs/style-guide/utilities.md, packages/styles/_utils.scss
Add new utility classes.
* Fix `py-0` - previously had same definition as `px-0`
* Margin/padding attributes `all` support: adds `.ma-#` and `.pa-#` 
* Text transformations: `.capitalize`, `.lowercase`, `.uppercase`
* Font-Weight: `.bold-500`, `.bold-600`, `.bold-700`
* Truncation: `.truncate-multi` and example config
* Height: `.h-100`, `.h-auto`, `.h-screen`
* Float: `.float-right`, `.float-left`, `.float-center`
* Overflow: `.overflow-auto`
=> feat(styles/utilities): CSS utility class updates

packages/KCheckbox/package.json, packages/KRadio/package.json
update version for kradio, kcheckbox
=> ci: update the version

lerna.json
The release message is not a valid conventional commit. Add `:` to have it match the standard.
* Change publish commit message in lerna config
=> ci: fix release message

.github/workflows/test.yml
Add Percy visual regression testing
* add ci build step to run visual regression testing
=> ci: add visual regression tests

.github/workflows/publish.yml
adds visual regression testing to the master build to create a baseline
* add visual regression tests to the master test run
=> ci: add percy to master build

lerna.json
=> chore(*): version bump project to 4.0.0-beta.1 [khcp-1886]

package.json
=> chore(*): update publish:ci

.github/workflows/publish.yml, .github/workflows/test.yml
Don't do visual regression testing on the 404 page since the content is randomly generated.
*
=> fix(*): don't percy 404 page [khcp-1969]

.github/workflows/codeql-analysis.yml, .github/workflows/publish.yml, .github/workflows/test.yml, lerna.json, package.json
Move to beta releases
* change to canary with the beta tag as per https://github.com/lerna/lerna/blob/main/commands/version/README.md#--preid
* add canary flag to publish as per https://github.com/lerna/lerna/tree/main/commands/publish#--canary
* run actions on release branches
=> chore: move to beta version

.github/workflows/publish.yml
Missing a dollar sign on the variable expansion
* add `$`
=> fix: missing dollar sign

.github/workflows/publish.yml
use the newer git checkout action to avoid setup git issues
* update github actions
=> fix: git checkout to v2

docs/components/button.md, docs/components/card.md, docs/components/icon.md, docs/components/renderless/komponent.md, packages/KButton/KButton.vue, packages/KButton/__snapshots__/KButton.spec.js.snap, packages/KEmptyState/KEmptyState.spec.js, packages/KEmptyState/KEmptyState.vue, packages/KEmptyState/__snapshots__/KEmptyState.spec.js.snap, packages/KModal/KModal.spec.js, packages/KModal/__snapshots__/KModal.spec.js.snap, packages/KMultiselect/__snapshots__/KMultiselect.spec.js.snap, packages/KSegmentedControl/KSegmentedControl.spec.js, packages/KSegmentedControl/KSegmentedControl.vue, packages/KSegmentedControl/__snapshots__/KSegmentedControl.spec.js.snap, packages/KViewSwitcher/KViewSwitcher.vue, packages/KViewSwitcher/__snapshots__/KViewSwitcher.spec.js.snap
This implements design changes requested in KHCP-1888.
* Add default rounded style of button
* Add medium and large button sizes
* Remove outlinePrimary outlineDanger btnLinkDaner appearances
* Add creation appearance
* Adjust paddings to new redesign
=> Redesign of KButton

lerna.json
add beta tag to Lerna source of truth version
* add beta version to lerna.json
=> ci: add beta tag to version

docs/.vuepress/styles/index.styl, docs/style-guide/type.md, packages/styles/_typography.scss, packages/styles/styles.scss
Update body font-weight to 200.
*
=> feat(typeface): redesign typeface

docs/components/breadcrumbs.md, packages/Krumbs/Krumbs.vue, packages/Krumbs/__snapshots__/Krumbs.spec.js.snap
Update `Krumbs` to new metalab designs.
*
=> feat(krumbs): redesign krumbs

docs/components/badge.md, packages/KBadge/KBadge.vue, packages/KBadge/__snapshots__/KBadge.spec.js.snap, packages/styles/_variables.scss
KBadge was redesigned to allow for rectangular border shape, new standardized color and a different paddings
* Add new "info" appearance for badge
* Add round and rectangular shape for badge
* Change paddings
* Add variables for line height
* Update test snapshots
=> KBadge redesign

docs/.vuepress/config.js, docs/.vuepress/enhanceApp.js, docs/components/pagination.md, packages/KButton/KButton.vue, packages/KPagination/KPagination.spec.js, packages/KPagination/KPagination.vue, packages/KPagination/README.md, packages/KPagination/__snapshots__/KPagination.spec.js.snap, packages/KPagination/package.json
We introduced a new Kongponent - KPagination. It will provide standardized tool to paginate long lists.
* Introduce KPagination component
* Add --KButtonFontSize variable
* Update Docs
=> feat(kpagination): new kongponent

lerna.json, package.json
remove the flags we used during the new version beta period.
* no canary tag
* back to independent publishing
=> ci: remove flags

lerna.json, package.json
=> chore(*): all versions to 6.0

package.json
* Update publish no more `--conventional-prerelease`
=> chore(*): no more prerelease

docs/components/table.md, docs/components/textarea.md, packages/KTable/KTable.vue, packages/KTextArea/KTextArea.spec.js, packages/KTextArea/KTextArea.vue, packages/KTextArea/__snapshots__/KTextArea.spec.js.snap, utils/utils.js
General fixes from the redesign
* Update `KTable` docs to remove sortable when not sorting
* `KTable` - fix client sort and add experimental `enableClientSort` prop
* `KtextArea`
* Add prop `disableCharLimit`
* Fix alignment of char limit text
* Emit an event if the character limit is exceeded
* Update docs / tests
=> fix(*): general fixes

packages/KCardCatalog/KCardCatalog.vue, packages/KCardCatalog/package.json, packages/KTable/KTable.vue, packages/KTable/package.json
Restore references to files (rather than package) for
tests to run successfully and new @kongponents/utils package
can successfully deploy.
=> chore(utils): restore references to publish pkg

packages/KCard/package.json, packages/KInput/package.json, packages/KMenu/package.json, packages/KPop/package.json, packages/KSelect/package.json, packages/KTable/package.json, packages/KTextArea/package.json
=> chore(*): update dependencies on vue-uuid

packages/KSkeleton/FullScreenKongSkeleton.vue, packages/styles/package.json
=> chore(kskeleton): expose assets

packages/styles/package.json
=> chore(styles): back out change

packages/KCardCatalog/package.json, packages/KTable/package.json
=> chore(ktable): more dependencies

.github/workflows/publish.yml
Update the node version in publish to 12.x
* Update `publish.yml` to use node 12.x
=> fix(publish): update node version in publish

packages/styles/styles.scss
Remove reference to custom element package in outputted comment.
=> chore(comments): update outputted comment

.github/workflows/publish.yml, .github/workflows/test.yml, package.json, yarn.lock
=> fix(actions): fix actions

docs/contributing/getting-started.md
=> fix(docs): fix contribution docs

docs/components/skeleton.md, packages/KSkeleton/CardSkeleton.vue
Adjust styles to properly render `CardSkeleton`.
* Fixes #466.
* Closes #467.
=> style(kskeleton): fix styles for card type

lerna.json
Version publishing is broken right now. Switch to manual versioning temporarily to fix.
*
=> chore(*): fix version

lerna.json
Reverting back to proper versioning (independent).
=> revert(version): revert independent version fix

packages/KTable/KTable.vue
=> fix(ktable): update sort styling

docs/.vuepress/config.js, docs/.vuepress/enhanceApp.js, docs/components/table-legacy.md, packages/KTableLegacy/KTableLegacy.spec.js, packages/KTableLegacy/KTableLegacy.vue, packages/KTableLegacy/README.md, packages/KTableLegacy/__snapshots__/KTableLegacy.spec.js.snap, packages/KTableLegacy/package.json
Add legacy version of KTable to allow smoother upgrade process.
*
=> feat(ktable): add legacy ktable component

packages/KTableLegacy/README.md
=> chore(ktablelegacy): fix readme

netlify.toml
Add Netlify deploy config for different build command on next branch.
The settings in `./netlify.toml` will override the Netlify Deploy Settings in the UI.
=> chore(netlify): add netlify deploy config

docs/README.md, docs/components/card-catalog.md, docs/components/icon.md, docs/components/table.md
Add `raw-loader` documentation to 
* KIcon
* KTable
* KCardCatalog
=> docs(raw-loader): add docs on using raw loader

pull_request_template.md
=> chore(pr): add label to pr template

packages/Krumbs/Krumbs.vue
Fixes the icon prop on Krumbs
- Updates to the corresponding `.spec.ts` test file(s) to utilize [Cypress Component Testing](https://docs.cypress.io/guides/component-testing/introduction).
If …
=> fix(krumbs): fix kicon prop

package.json
Adding `volta` config in package.json
=> chore(volta): add volta config

packages/Krumbs/Krumbs.vue
Fix the `Krumbs` icon viewbox prop
=> fix(krumbs): fix breadcrumb icon viewbox

docs/components/table.md
* Fix typos in KTable docs
- Updates to the corresponding `.spec.ts` test file(s) to utilize [Cypress Component Testing](https://docs.cypress.io/guides/component-testing/introduction).
If you …
=> fix(docs): ktable docs have a typo in initialFetcherParams [KHCP-2863]

packages/KInput/KInput.vue
Properly bind variable to attribute
- Updates to the corresponding `.spec.ts` test file(s) to utilize [Cypress Component Testing](https://docs.cypress.io/guides/component-testing/introduction) …
=> fix(kinput): properly bind variable to attribute

packages/KModal/KModal.vue
Fix `rgb` to `rgba` in KModal background
- Updates to the corresponding `.spec.ts` test file(s) to utilize [Cypress Component Testing](https://docs.cypress.io/guides/component-testing/introduc …
=> fix(kmodal): fix background rgba

packages/KModalFullscreen/KModalFullscreen.vue, packages/KModalFullscreen/__snapshots__/KModalFullscreen.spec.js.snap
=> fix(kmodalfullscreen): add tabindex

packages/KTabs/KTabs.vue
emit changed event with keyboard input
=> fix(ktabs): emit changed event with keyboard input

cypress/support/index.ts, docs/components/input.md, src/components/KBreadcrumbs/KBreadcrumbs.spec.ts, src/components/KInput/KInput.spec.ts, src/components/KInput/KInput.vue, src/components/KTooltip/KTooltip.spec.ts
Added enhancements that were made to `KInput` component since original conversion.
=> feat(kinput): add kinput enhancements to vue 3 version

.github/workflows/test.yml
=> ci: rename action

docs/components/button.md, src/components/KButton/KButton.spec.ts, src/components/KButton/KButton.vue
=> feat(kbutton): update kbutton with icon prop

packages/KModal/KModal.vue
Applies class on mounted instead of using `immediate` watcher.
=> fix(kmodal): fix overflow to apply on mounted

packages/KBadge/KBadge.vue
Adjust `info` style for kbadge
*
=> fix(kbadge): adjust info colors

.github/workflows/publish.yml, .github/workflows/test.yml, docs/.vuepress/config.ts, package.json, src/components/KCard/KCard.vue, yarn.lock
=> ci(release): add semantic-release

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/publish.yml, .github/workflows/test.yml, docs/guide/theming.md
=> docs(theming): update theming example

.github/workflows/get-changed-files.yml, docs/README.md
=> ci: update test logic

.github/workflows/get-changed-files.yml, src/components/KMenu/KMenu.vue
=> fix(kmenu): type interface

src/components/KMenu/KMenu.vue
=> fix(kmenu): update type comment

src/components/KPagination/KPagination.vue
Style updates for `KPagination` (design feedback)
=> fix(kpagination): style updates

docs/components/icon.md, src/components/KIcon/KIcon.vue
Update docs and fix slot checking.
=> fix(kicon): update docs and fix slot checking [KHCP-3331]

src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue
=> fix(kselect): select popover pos

docs/components/skeleton.md, src/components/KSkeleton/KSkeletonBox.vue, src/components/KSkeleton/TableSkeleton.vue
=> fix(kskeleton): docs cleanup

packages/KTable/KTable.vue
=> fix(ktable): revert #609

packages/KIcon/KIcon.vue
Re-render icon if any of the given props change.
---
=> fix(kicon): re-render svg if props change

src/components/KIcon/KIcon.vue
Update svg if icon props change
---
=> fix(kicon): update svg if icon props change

docs/components/table.md, src/components/KTable/KTable.vue
Better support for conditional row/cell events.
---
=> feat(ktable): support for conditional events [beta]

docs/components/table.md, src/components/KTable/KTable.vue
=> fix(ktable): emit event on cell and row click [beta]

docs/style-guide/utilities.md, packages/styles/_utils.scss
- Add support for `.multi-line-truncation`
- Deprecate `.truncate-multi`
---
=> feat(kstyles): multi-line truncation [khcp-3552]

docs/components/skeleton.md, packages/KInlineEdit/KInlineEdit.vue, packages/KSkeleton/KSkeleton.vue, packages/KSkeleton/__snapshots__/KSkeleton.spec.js.snap, packages/KTable/__snapshots__/KTable.spec.js.snap
Fix for [KHCP-3931](https://konghq.atlassian.net/browse/KHCP-3931)
- Update background color on hover for `KInlineEdit`
- Default `delay-milliseconds` to `0` for `KSkeleton`
---
=> fix(kinlineedit): hover bg color [khcp-3931]

.github/workflows/codeql-analysis.yml, .github/workflows/commitlint.yml, .github/workflows/publish.yml, .github/workflows/test.yml
- Update Percy flow on main to utilize same actions as the beta branch; this will also allow for setting PERCY_TARGET_BRANCH: main 
- Remove Percy from the publish.yml flow; the code already went through Percy in the test.yml workflow
---
=> ci(percy): update percy configuration [KHCP-3967]

docs/components/table.md, packages/KPagination/package.json, packages/KTable/KTable.vue
Follow up fixes for https://github.com/Kong/kongponents/pull/666 and https://github.com/Kong/kongponents/pull/663.
---
=> fix(kpagination): fix page size change and import bugs

src/components/KModalFullscreen/KModalFullscreen.vue
- fix alignment of icon and header text / height of divider
---
=> fix(kmodalfullscreen): align header [beta]

packages/KPagination/PaginationOffset.vue
=> fix(kpagination): use more specific css classes

packages/KModalFullscreen/KModalFullscreen.vue
=> fix(kmodalfullscreen): padding [khcp-4020]

packages/KButton/KButton.vue, packages/KCard/KCard.vue, packages/KEmptyState/KEmptyState.vue, packages/KPagination/KPagination.vue, packages/styles/forms/_inputs.scss
=> style(font): update font-weight [khcp-4054]

src/components/KButton/KButton.vue, src/components/KCard/KCard.vue, src/components/KEmptyState/KEmptyState.vue, src/components/KPagination/KPagination.vue, src/styles/forms/_inputs.scss
Backport: [https://github.com/Kong/kongponents/pull/676](https://github.com/Kong/kongponents/pull/676)
---
=> chore(*): backport fixes

packages/KButton/KButton.vue, packages/KModal/KModal.vue, packages/KModalFullscreen/KModalFullscreen.vue, packages/KTable/KTable.vue, packages/Krumbs/Krumbs.vue, packages/styles/forms/_inputs.scss
=> style(font): update font weight

src/components/KBreadcrumbs/KBreadcrumbs.vue, src/components/KButton/KButton.vue, src/components/KModal/KModal.vue, src/components/KModalFullscreen/KModalFullscreen.vue, src/components/KTable/KTable.vue, src/styles/forms/_inputs.scss
Backport: [https://github.com/Kong/kongponents/pull/678](https://github.com/Kong/kongponents/pull/678)
---
=> chore(*): backport fixes 678

docs/components/catalog.md, packages/KCatalog/KCatalog.spec.js, packages/KCatalog/KCatalog.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-4110](https://konghq.atlassian.net/browse/KHCP-4110)
Beta branch already updated.
---
=> fix(kcatalog): add new prop [khcp-4110]

packages/KCatalog/KCatalog.vue, packages/KCatalog/KCatalogItem.vue
=> fix(kcatalog): remove router-link slot

packages/KAlert/KAlert.vue
Update KAlert default colors per Figma spec
---
=> fix(kalert): update default appearance colors

packages/KSelect/KSelect.vue
Fix KSelect dropdown border color (missed in the other PR).
Will be ported to `beta` in @aanchalm01 other KSelect PR
---
=> fix(kselect): update dropdown border color

docs/components/select.md, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue
Backport: 
[https://github.com/Kong/kongponents/pull/693](https://github.com/Kong/kongponents/pull/693)
---
=> chore(*): backport fixes khcp-4158 [beta]

src/components/KCatalog/KCatalog.spec.ts, src/components/KCatalog/KCatalog.vue, src/components/KTable/KTable.spec.ts, src/components/KTable/KTable.vue
=> fix(ktable,kcatalog): backport #685 [beta]

docs/components/select.md, src/components/KSelect/KSelect.vue, src/styles/forms/_checkbox-radio.scss
Beta branch fix for update KSelect input border radius and popover spacing from input
---
=> fix(kselect): input border radius and dropdown spacing [beta]

packages/KSelect/KSelect.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-4218](https://konghq.atlassian.net/browse/KHCP-4218)
Before:
After:
NOTE: I will port the style to **beta** once this gets in **main**. 
---
=> style(kselect): update placeholder color [khcp-4218]

src/components/KSelect/KSelect.vue
Backport:
[https://github.com/Kong/kongponents/pull/712](https://github.com/Kong/kongponents/pull/712)
---
=> fix(kselect): backport #712 [beta]

.github/workflows/publish.yml, .github/workflows/test.yml, package.json, src/components/KPagination/KPagination.spec.ts, src/components/KPop/KPop.vue, src/components/KSelect/KSelect.spec.ts, yarn.lock
Fix KPopover errors due to a misconfigured target
---
=> fix(kpopover): fix logic to prevent errors [beta]

.gitignore, docs/components/select.md, packages/KCatalog/__snapshots__/KCatalog.spec.js.snap, packages/KLabel/__snapshots__/KLabel.spec.js.snap, packages/KMultiselect/__snapshots__/KMultiselect.spec.js.snap, packages/KPagination/__snapshots__/KPagination.spec.js.snap, packages/KPop/KPop.vue, packages/KPop/__snapshots__/KPop.spec.js.snap, packages/KSelect/KSelect.spec.js, packages/KSelect/KSelect.vue, packages/KSelect/__snapshots__/KSelect.spec.js.snap, packages/KTable/__snapshots__/KTable.spec.js.snap, packages/KoolTip/__snapshots__/KoolTip.spec.js.snap
Add autosuggest support for KSelect. @adamdehaven 
---
=> feat(kselect): add autosuggest support [KHCP-4227]

src/components/KModal/KModal.vue, src/components/KTooltip/KTooltip.vue
=> fix(kooltip): z-index bump [beta]

packages/KIcon/__snapshots__/KIcon.spec.js.snap, packages/KIcon/icons/icn-arrow-down.svg, packages/KIcon/icons/icn-arrow-up.svg, packages/KIcon/icons/index.js
https://konghq.atlassian.net/browse/MA-823
---
=> feat(icons): add new arrow up/down icons to be used by vitals metric cards [MA-823]

packages/KSelect/KSelect.vue
Porting #735 to the main branch.
---
=> fix(kselect): update popover width when it opens

src/components/KIcon/icons/icn-arrow-down.svg, src/components/KIcon/icons/icn-arrow-up.svg, src/components/KIcon/icons/index.ts
- used in vitals metric cards
---
=> feat(kicon): add arrow up/down icons

docs/components/icon.md
Addresses:
[https://konghq.atlassian.net/browse/KHCP-4279](https://konghq.atlassian.net/browse/KHCP-4279)
---
=> fix(kicon): fix styling in md file

docs/components/icon.md
Backports: [https://github.com/Kong/kongponents/pull/741](https://github.com/Kong/kongponents/pull/741)
---
=> fix(*): update icon md file

docs/components/modal.md, src/components/KModal/KModal.vue
=> fix(kmodal): dismiss icon logic [beta]

packages/KPagination/KPagination.vue
Use `positionFixed` so content does not get caught off for short tables.
---
=> fix(kpagination): use positionFixed

src/components/KPagination/KPagination.vue
Use `positionFixed` so content does not get caught off for short tables.
---
=> fix(kpagination): use positionFixed [beta]

src/components/KPop/KPop.vue, src/components/KSelect/KSelect.vue
Ports over changes from https://github.com/Kong/kongponents/pull/750
---
=> fix(kselect): update items and filter logic

src/components/KCatalog/KCatalog.vue, src/components/KTable/KTable.vue
Backports:
[https://github.com/Kong/kongponents/pull/747](https://github.com/Kong/kongponents/pull/747)
---
=> chore(*): update empty state action button color

packages/KStepper/package.json
=> fix(kstepper): include stepper-icons directory too

docs/components/select.md, src/components/KSelect/KSelect.spec.ts, src/components/KSelect/KSelect.vue
Porting changes of #749
@kaiarrowood
=> feat(kselect): add clearable prop

docs/components/select.md, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue
=> fix(kselect): backport #723

docs/components/dropdown-menu.md, src/components/KButton/KButton.vue, src/components/KDropdownMenu/KDropdownMenu.vue
=> fix(*): backport #771

packages/utils/utils.js, packages/utils/utils.spec.js
=> fix(ktable): client sorting with number values

src/components/KSelect/KSelect.vue
=> refactor(kselect): remove the `items` slot [KHCP-4668]

src/components/KSelect/KSelect.vue
Fix `KSelect` key
Port https://github.com/Kong/kongponents/pull/784
---
=> fix(kselect): ensure key is set [KHCP-4680]

packages/KSelect/KSelect.vue
=> fix(kselect): replace key string

docs/components/button.md, docs/components/dropdown-menu.md, packages/KButton/KButton.vue, packages/KCatalog/__snapshots__/KCatalog.spec.js.snap, packages/KDropdownMenu/KDropdownMenu.vue, packages/KMultiselect/KMultiselect.vue, packages/KMultiselect/__snapshots__/KMultiselect.spec.js.snap, packages/KPagination/__snapshots__/KPagination.spec.js.snap, packages/KSelect/KSelect.vue, packages/KTable/__snapshots__/KTable.spec.js.snap
Addresses:
[https://konghq.atlassian.net/browse/KHCP-4206](https://konghq.atlassian.net/browse/KHCP-4206)
---
=> feat(caret): chevron should not toggle [khcp-4206]

docs/components/button.md, docs/components/dropdown-menu.md, src/components/KButton/KButton.vue, src/components/KDropdownMenu/KDropdownMenu.vue, src/components/KIcon/icons/index.ts, src/components/KSelect/KSelect.vue
Backports: 
[https://github.com/Kong/kongponents/pull/786](https://github.com/Kong/kongponents/pull/786)
---
=> fix(*): backport #786

src/components/KDropdownMenu/KDropdownItem.vue
=> fix(*): correct handling of sass division

packages/KDropdownMenu/KDropdownItem.vue
This PR fixes the style issue.
---
=> fix(dropdown): update psuedo element position

src/components/KDropdownMenu/KDropdownItem.vue
=> fix(*): remove sass division [beta]

.github/CODEOWNERS
As discussed added @aanchalm01 and @jillztom as code owners.
---
=> chore(codeowners): update

src/components/KDropdownMenu/KDropdownItem.vue
Backports:
[https://github.com/Kong/kongponents/pull/796](https://github.com/Kong/kongponents/pull/796)
---
=> fix(dropdown): update pseudo element position beta

src/components/KPagination/KPagination.vue
Backports:
[https://github.com/Kong/kongponents/pull/801](https://github.com/Kong/kongponents/pull/801)
---
=> fix(*): backport khcp 4611

packages/KPagination/KPagination.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-4611](https://konghq.atlassian.net/browse/KHCP-4611)
---
=> style(kpagination): update width [khcp-4611]

src/components/KPop/KPop.vue
=> fix(kpop): always remove click listeners

src/components/KCard/KCard.vue, src/components/KCatalog/KCatalog.vue, src/components/KCatalog/KCatalogItem.vue, src/components/KDropdownMenu/KDropdownMenu.vue, src/components/KLabel/KLabel.vue, src/components/KMenu/KMenu.vue, src/components/KMenu/KMenuItem.vue, src/components/KPagination/KPagination.vue, src/components/KPop/KPop.vue, src/components/KSelect/KSelect.vue, src/components/KTable/KTable.vue, src/components/KTabs/KTabs.vue, src/components/KTooltip/KTooltip.vue
A few fixes to resolve Vue 3 warnings in the `@vue/compat` build
---
=> fix: vue 3 fixes

src/components/KDateTimePicker/KDateTimePicker.vue
=> datepicker: remove unused input emit

src/components/KToaster/KToaster.vue
Task in Jira: https://konghq.atlassian.net/browse/KHCP-4965
- **Fix** - Fixed styles
---
=> fix(ktoaster): repaired width in toaster component [KHCP-4965]

docs/.vuepress/config.ts, package.json, src/components/KIcon/KIcon.vue, src/components/KSelect/KSelect.vue, src/components/KTable/KTable.vue, yarn.lock
=> fix(*): upgrade vue, vuepress, and fix dependency tree

src/components/KDateTimePicker/KDateTimePicker.vue
=> fix(datepicker): hover state should be blue-200

package.json, yarn.lock
Merging `main` branch into `beta` (`-Xours` strategy)
---
=> chore: merging main branch into beta

package.json, src/components/KSelect/KSelect.vue, yarn.lock
=> chore(deps): update vue-tsc

docs/.vuepress/config.ts, docs/components/badge.md, docs/components/multiselect.md, src/components/KBadge/KBadge.spec.ts, src/components/KBadge/KBadge.vue, src/components/KMultiselect/KMultiselect.spec.ts, src/components/KMultiselect/KMultiselect.vue, src/components/KMultiselect/KMultiselectItem.vue, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue, src/components/index.ts, src/composables/useUtilities.ts, src/styles/_mixins.scss, src/styles/forms/_inputs.scss
New `KMultiselect` component.
Addresses requirements in [KHCP-53314](https://konghq.atlassian.net/browse/KHCP-3314).
Completes subtask [KHCP-5147](https://konghq.atlassian.net/browse/KHCP-5147).
Updates to `KBadge`:
- dismiss action emits `dismissed`
- minor style updates
- add conditional display of tooltip if badge is truncated
- adds associated props `truncationTooltip` and `alwaysShowTooltip`
- adds `hidden` prop for `KBadge` usage in `KMultiselect` staging area
=> feat(kmultiselect): new component [khcp-5147]

.github/workflows/test.yml
=> ci(percy): re-enable percy visual regression tests for docs

cypress/fixtures/file-upload/file-upload-document.md, src/components/KFileUpload/KFileUpload.spec.ts
Addresses:
[https://konghq.atlassian.net/browse/KHCP-5137](https://konghq.atlassian.net/browse/KHCP-5137)
=> fix(upload-file): add more test [khcp-5137]

docs/components/select.md, src/components/KSelect/KSelect.cy.ts, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue
This PR adds disabled items support for `KSelect`.
=> feat(kselect): support disabled item

src/components/KTable/KTable.vue, tsconfig.build.json
=> fix(build): resolve corrupted build

docs/components/select.md, src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.vue
Resolve issues with `KSelect` background colors
=> fix(kselect): background color [KHCP-5396]

src/components/KSelect/KSelect.vue
This PR fixes border style (`border-radius` and `border-color`) for `<KSelect appearance="select">`.
Reference: https://kongstrong.slack.com/archives/CTAMPSTNX/p1669292981697989?thread_ts=1669271688.915199&cid=CTAMPSTNX
=> fix(kselect): border style for `appearance="select"`

docs/components/segmented-control.md, src/components/KSegmentedControl/KSegmentedControl.cy.ts, src/components/KSegmentedControl/KSegmentedControl.vue
Adds theming and slotting support to `KSegmentedControl` in order to support new designs for analytics.
Addresses [KHCP-5421](https://konghq.atlassian.net/browse/KHCP-5421).
=> feat(ksegmentedcontrol): updates [khcp-5421]

docs/.vitepress/config.ts
Add Algolia Doc Search to the docs site
=> docs(search): add algolia search

src/components/KLabel/KLabel.vue
Add `position-fixed` to tooltip for `KLabel`.
=> fix(klabel): tooltip use positionFixed

docs/components/file-upload.md, src/components/KFileUpload/KFileUpload.vue
=> fix(file-upload): update style if label is absent [khcp-5654]

docs/components/modal-fullscreen.md, src/components/KCodeBlock/KCodeBlock.vue, src/components/KModalFullscreen/KModalFullscreen.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-5683](https://konghq.atlassian.net/browse/KHCP-5683)
Before:
After:
=> fix(code-block): remove extra z-index [khcp-5683]

src/components/KCodeBlock/KCodeBlock.vue, src/components/KModalFullscreen/KModalFullscreen.vue, src/components/KPrompt/KPrompt.vue, src/styles/_variables.scss
Update copy button mobile styles
=> fix(kcodeblock): mobile copy button styles

src/components/KTabs/KTabs.vue
Decrease bottom border from `2px` to `1px`.
Address [KHCP-5674](https://konghq.atlassian.net/browse/KHCP-5674).
=> fix(ktabs): shrink border [khcp-5674]

src/components/KSegmentedControl/KSegmentedControl.cy.ts, src/components/KSegmentedControl/KSegmentedControl.vue
Add validation and normalize code for `options`.
=> fix(ksegmentedcontrol): add option validation

src/components/KDateTimePicker/KDateTimePicker.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-5697?focusedCommentId=88958
=> fix(kdatetimepicker): minor styling touchups [KHCP-5697]

src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.vue
Resolves this issue: https://app.datadoghq.com/rum/explorer?query=%40application.id%3A6e430333-9e0f-4d6b-ac63-5f7d4ad9a641%20env%3Aprod%20-%40browser.name%3AHeadlessChrome%20%40type%3Aerror&cols=&event=AgAAAYXkcsLLOOzoxwAAAAAAAAAYAAAAAEFZWGtjdkhUQUFEZWlZeFdmRHFHN2dBQQAAACQAAAAAMDE4NWU0ODEtYjg5Ny00MGVlLTg3ZGMtMGE1N2FmOTlkODRl&index=&type=rum&from_ts=1674574895000&to_ts=1674575015000&live=false
=> fix(selects): optional chain prop items

docs/.vitepress/config.ts, docs/components/external-link.md, src/components/KExternalLink/KExternalLink.cy.ts, src/components/KExternalLink/KExternalLink.vue, src/components/index.ts
Ticket: https://konghq.atlassian.net/browse/KHCP-5745
=> feat(*): add external link component [KHCP-5745]

cli/utils/kongponents.ts, docs/guide/contributing.md, docs/guide/usage.md, src/global-components.ts, src/index.ts
Add global component module exports and update the docs with instructions
=> chore(types): global component types

src/components/KTruncate/KTruncate.vue
Fixes reactivity issue on render (screenshot)
=> fix(ktruncate): fix render reactivity issue

docs/components/multiselect.md, docs/components/select.md, src/components/KMultiselect/KMultiselect.vue, src/components/KRadio/KRadio.vue, src/components/KSelect/KSelect.vue
Ticket: https://konghq.atlassian.net/browse/KHCP-6007
=> feat(kselect, kmultiselect): dropdown footer text position prop [KHCP-6007]

src/components/KDropdownMenu/KDropdownMenu.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-6209
=> fix(kdropdownmenu): fix kpopover undefined class bug [KHCP-6209]

docs/components/modal-fullscreen.md, src/components/KModalFullscreen/KModalFullscreen.cy.ts, src/components/KModalFullscreen/KModalFullscreen.vue
Ticket: https://konghq.atlassian.net/browse/KHCP-6093
=> feat(kmodalfullscreen): add footer content slot [KHCP-6093]

src/components/KButton/KButton.vue, src/components/KPagination/KPagination.vue, src/components/KTruncate/KTruncate.vue
=> fix(kbutton): fix btn-link variables

src/components/KAlert/KAlert.vue, src/components/KBadge/KBadge.vue, src/components/KBreadcrumbs/KBreadcrumbs.vue, src/components/KButton/KButton.vue, src/components/KDropdownMenu/KDropdownMenu.vue, src/components/KFileUpload/KFileUpload.vue, src/components/KModal/KModal.vue, src/components/KModalFullscreen/KModalFullscreen.vue, src/components/KToaster/KToaster.vue, src/index.ts, src/types/alert.ts, src/types/badge.ts, src/types/breadcrumbs.ts, src/types/button.ts, src/types/index.ts, src/types/utils.ts
[Jira task](https://konghq.atlassian.net/browse/KHCP-5635)
=> refactor(kalert,kbadge,kbreadcrumbs,kbutton): ts improvment [KHCP-5635]

docs/components/tooltip.md
Addresses: https://konghq.atlassian.net/browse/KHCP-6453
=> docs(tooltip): add note about disabled trigger element [KHCP-6453]

src/components/KMultiselect/KMultiselect.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-6460
=> fix(kmultiselect): fix input element full width [KHCP-6460]

src/components/KTruncate/KTruncate.vue
Ticket: https://konghq.atlassian.net/browse/KHCP-6527
Before:
After:
(I like to move-it-move-it 😂)
=> fix(ktruncate): fix items floating to right issue [KHCP-6527]

src/styles/_mixins.scss, src/styles/forms/_inputs.scss
Addresses:
[https://konghq.atlassian.net/browse/KHCP-6440](https://konghq.atlassian.net/browse/KHCP-6440)
**Before:**
**After:**
=> fix(textarea): update styles [khcp-6440]

docs/components/badge.md, src/components/KBadge/KBadge.cy.ts, src/components/KBadge/KBadge.vue
=> feat(kbadge): add maxWidth prop

src/components/KAlert/KAlert.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-6492](https://konghq.atlassian.net/browse/KHCP-6492)
=> fix(kalert): update setup syntax [khcp-6492]

src/components/KBreadcrumbs/KBreadcrumbs.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-6493](https://konghq.atlassian.net/browse/KHCP-6493)
=> fix(kbreadcrumbs): update setup syntax khcp-6493]

src/components/KButton/KButton.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-6494](https://konghq.atlassian.net/browse/KHCP-6494)
=> fix(kbutton): update setup syntax [khcp-6494]

src/components/KMultiselect/KMultiselect.vue
Fix [KHCP-6644](https://konghq.atlassian.net/browse/KHCP-6644).
[KHCP-6644]: https://konghq.atlassian.net/browse/KHCP-6644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kmultiselect): display [khcp-6644]

docs/guide/contributing.md
[Jira task](https://konghq.atlassian.net/browse/KHCP-6738)
=> docs: update docs [KHCP-6738]

.github/CODEOWNERS
=> chore:update code owners

src/components/KTable/KTable.vue, src/composables/useUtilities.ts
Switch to setup syntax.
Address [KHCP-6519](https://konghq.atlassian.net/browse/KHCP-6519).
[KHCP-6519]: https://konghq.atlassian.net/browse/KHCP-6519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ktable): setup syntax [khcp-6519]

src/components/KTable/KTable.vue, src/composables/useUtilities.ts
=> Revert "feat(ktable): setup syntax [khcp-6519]"

package.json, src/components/KTabs/KTabs.vue
Update the `@semantic-release/git` configuration to update the `package.json` file on release.
=> fix(semantic-release): update version on publish [KHCP-6911]

package.json, src/components/KCard/KCard.vue, src/types/card.ts, yarn.lock
https://konghq.atlassian.net/browse/KHCP-6495
=> feat(KCard): setup syntax [KHCP-6495]

src/components/KCard/KCard.vue, src/components/KCollapse/KCollapse.vue, src/types/card.ts, src/types/collapse.ts, src/types/utils.ts
https://konghq.atlassian.net/browse/KHCP-6498
=> feat(KCollapse): setup syntax [KHCP-6498]

src/components/KCatalog/KCatalog.vue, src/components/KCatalog/KCatalogItem.vue, src/types/catalog.ts
Switch to setup syntax.
Addresses [KHCP-6496](https://konghq.atlassian.net/browse/KHCP-6496).
[KHCP-6496]: https://konghq.atlassian.net/browse/KHCP-6496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(kcatalog): setup syntax [khcp-6496]

README.md
Remove codecov badge; we are no longer integrated
=> chore: remove codecov badge

README.md
=> chore: add publish badge

src/components/KDropdownMenu/KDropdownItem.vue, src/types/dropdown-menu.ts
Refactor Dropdown menu item component
=> feat(KDropdown): refactor dropdown menu item

src/components/KEmptyState/KEmptyState.vue
https://konghq.atlassian.net/browse/KHCP-6501
=> feat(KEmptyState): switch to setup syntax [KHCP-6501]

src/components/KPrompt/KPrompt.vue
https://konghq.atlassian.net/browse/KHCP-6512
Setup syntax
=> feat(KPrompt): switch to setup syntax [KHCP-6512]

package.json, vite.config.ts
Externalize `vue-router` and add in `peerDependencies`
=> fix(deps): externalize vue-router

sandbox/components/SandboxNav.vue, sandbox/pages/SandboxMultiselect.vue, sandbox/router.ts, src/components/KMultiselect/KMultiselect.cy.ts, src/components/KMultiselect/KMultiselect.vue
- Ensure items pushed to invisible selected items array are unique
- Add multiselect to sandbox
- Add regression test
=> fix(KMultiselect): fix collapsed item count [MA-1506]

src/components/KSkeleton/CardSkeleton.vue, src/components/KSkeleton/FormSkeleton.vue, src/components/KSkeleton/FullScreenGenericSpinner.vue, src/components/KSkeleton/FullScreenKongSkeleton.vue, src/components/KSkeleton/KSkeleton.vue, src/components/KSkeleton/KSkeletonBox.vue, src/components/KSkeleton/SkeletonBase.vue, src/components/KSkeleton/TableSkeleton.vue
https://konghq.atlassian.net/browse/KHCP-6516
=> feat(KSkeleton): switch to setup syntax [KHCP-6516]

src/components/KSelect/KSelectItem.vue
https://konghq.atlassian.net/browse/KHCP-6515
=> feat(KSelect): switch to setup syntax for Select item [KHCP-6515]

src/components/KSlideout/KSlideout.vue
https://konghq.atlassian.net/browse/KHCP-6517
=> feat(KSlideout): switch to setup syntax [KHCP-6517]

.eslintrc.cjs
Fix issue with empty spaces rule
=> chore(eslint): fix empty lines rule

.github/workflows/pr-closed.yml, .github/workflows/publish.yml, .github/workflows/test.yml
=> chore(ci): use public npm token [KHCP-7211]

docs/guide/contributing.md
Add some tips to the contribution docs.
=> fix(contributing): docs clarification

src/components/KTextArea/KTextArea.vue
https://konghq.atlassian.net/browse/KHCP-6521
=> feat(KTextArea): switch to setup syntax [KHCP-6521]

docs/components/checkbox.md, src/components/KCheckbox/KCheckbox.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-7391](https://konghq.atlassian.net/browse/KHCP-7391)
**Before:**
**After:**
=> fix(checkbox): fix label-tooltip [khcp-7391]

src/components/KInputSwitch/KInputSwitch.vue, src/types/input-switch.ts
https://konghq.atlassian.net/browse/KHCP-6506
=> feat(KInputSwitch): switch to setup syntax [KHCP-6506]

src/components/KRadio/KRadio.vue
Fixes alignment issue when `type="card"`
=> fix(kradio): fix card alignment

package.json
=> fix(types): update types path

src/components/KTabs/KTabs.vue
https://konghq.atlassian.net/browse/KHCP-6520
=> feat(KTabs): switch to setup syntax [KHCP-6520]

src/components/KFileUpload/KFileUpload.vue
https://konghq.atlassian.net/browse/KHCP-6502
=> feat(KFileUpload): switch to setup syntax [KHCP-6502]

src/components/KViewSwitcher/KViewSwitcher.vue
https://konghq.atlassian.net/browse/KHCP-6524
=> feat(KViewSwitcher): switch to setup syntax [KHCP-6524]

src/components/KIcon/KIcon.vue
https://konghq.atlassian.net/browse/KHCP-6503
=> feat(KIcon): switch to setup syntax [KHCP-6503]

src/components/KPagination/KPagination.vue, src/components/KPagination/PaginationOffset.vue, src/types/pagination.ts
https://konghq.atlassian.net/browse/KHCP-6510
=> feat(KPagination): switch to setup syntax [KHCP-6510]

docs/components/select.md, src/components/KSelect/KSelect.vue
=> fix(k-select): fix custom select item width

sandbox/components/SandboxNav.vue, sandbox/pages/SandboxTabs.vue, sandbox/router.ts, src/components/KTabs/KTabs.vue
Extras for https://github.com/Kong/kongponents/pull/1426 to be merged onto another PR not `main`
FYI I've been working with @adamdehaven
=> WIP: Feat/khcp 7542 tab panels pt3

src/components/KDateTimePicker/KDateTimePicker.vue, src/types/date-time-picker.ts
https://konghq.atlassian.net/browse/KHCP-6499
=> feat(KDateTimePicker): switch to setup syntax [KHCP-6499]

.github/workflows/cleanup-preview-packages.yaml
=> fix: change schedule to run every 6 hours [KHCP-7461]

.github/workflows/cleanup-preview-packages.yaml
cut & paste error fix. using correct token.
=> fix: using correct env token to make it less confusing [KHCP-7461]

.vscode/extensions.json, .vscode/settings.json, docs/components/button.md, docs/guide/contributing.md, docs/vite.config.ts, package.json, src/components/KButton/KButton.vue, src/styles/_tmp-variables.scss, src/styles/_variables.scss, yarn.lock
Addresses: https://konghq.atlassian.net/browse/KHCP-7696
Adds new `kui-` design tokens to `KButton`
=> refactor(kbutton): add design tokens [KHCP-7696]

src/components/KPagination/KPagination.vue
Part 2 of [KHCP-7908](https://konghq.atlassian.net/browse/KHCP-7908). More variables that need to be updated on change to `total`.
[KHCP-7908]: https://konghq.atlassian.net/browse/KHCP-7908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kpagination): cache issue [khcp-7908]

.github/CODEOWNERS, docs/components/alert.md, package.json, src/components/KAlert/KAlert.vue, src/styles/_tmp-variables.scss, yarn.lock
Addresses: https://konghq.atlassian.net/browse/KHCP-7693
Changes:
* introduces `kui-` design tokens in `KAlert` component
* removes usage of utility classes in `KAlert` template
=> feat(kalert): introduce design tokens [KHCP-7693]

tsconfig.json, vite.config.ts
dont generate sourcemap as part of npm package
https://konghq.atlassian.net/browse/KHCP-7565
=> feat(sourcemaps): dont generate sourcemap as part of npm package [KHCP-7565]

.github/CODEOWNERS, docs/components/table.md, src/components/KAlert/KAlert.vue, src/components/KTable/KTable.vue, src/styles/_tmp-variables.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-7726
Changes:
- introduces `kui-` design tokens in `KTable` component
- removes any usage of Kongponents utility classes in `KTable` component template
=> feat(ktable): introduce kui tokens [KHCP-7726]

package.json, yarn.lock
=> chore(deps): update design tokens

.github/CODEOWNERS, .stylelintrc.cjs, src/components/KAlert/KAlert.vue, src/components/KCatalog/KCatalog.vue, src/components/KCatalog/KCatalogItem.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-7698
Changes:
- introduces `kui-` design tokens in `KCatalog` component
- removes any usage of Kongponents utility classes in `KCatalog` component template
=> feat(kcatalog): introduce kui tokens [KHCP-7698]

src/components/KBadge/KBadge.cy.ts
Fixes import of const in `KBadge` component test
=> fix(kbadge): fix import

.github/CODEOWNERS, src/components/KDateTimePicker/KDateTimePicker.vue, src/styles/_tmp-variables.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-7702
Changes:
- introduces `kui-` design tokens in `KDateTimePicker` component
- removes any usage of Kongponents utility classes in `KDateTimePicker` component template
=> feat(kdatetimepicker): introduce kui tokens [KHCP-7702]

.github/CODEOWNERS, src/components/KCard/KCard.vue, src/styles/_tmp-variables.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-7697
Changes:
- introduces `kui-` design tokens in `KCard` component
- removes any usage of Kongponents utility classes in `KCard` component template
=> feat(kcard): introduce kui tokens [KHCP-7692]

.github/CODEOWNERS, docs/components/popover.md, src/components/KPop/KPop.vue, src/styles/_tmp-variables.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-7718
Changes:
- introduces `kui-` design tokens in `KPop` component
- removes any usage of Kongponents utility classes in `KPop` component template
=> feat(kpop): introduce kui tokens [KHCP-7718]

.github/CODEOWNERS, package.json, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue, src/components/KSelect/KSelectItems.vue, src/styles/_mixins.scss, src/styles/_tmp-variables.scss, yarn.lock
Addresses: https://konghq.atlassian.net/browse/KHCP-7722
Changes:
- introduces `kui-` design tokens in `KSelect` component
- removes any usage of Kongponents utility classes in `KSelect` component template
=> feat(kselect): introduce kui tokens [KHCP-7722]

.github/CODEOWNERS, src/components/KCheckbox/KCheckbox.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-7699
Changes:
- introduces `kui-` design tokens in `KCheckbox` component
- removes any usage of Kongponents utility classes in `KCheckbox` component template (none found)
=> feat(kcheckbox): introduce kui tokens [KHCP-7699]

.github/CODEOWNERS, src/components/KEmptyState/KEmptyState.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-7704
Changes:
- introduces `kui-` design tokens in `KEmptyState` component
- removes any usage of Kongponents utility classes in `KEmptyState` component template (none found)
=> feat(kemptystate): introduce kui tokens [KHCP-7704]

.github/CODEOWNERS, docs/components/modal.md, src/components/KModal/KModal.vue, src/index.ts, src/styles/_tmp-variables.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-7714
Changes:
- introduces `kui-` design tokens in `KModal` component
- removes any usage of Kongponents utility classes in `KModal` component template
=> feat(kmodal): introduce kui tokens [KHCP-7714]

.github/CODEOWNERS, docs/components/collapse.md, src/components/KCollapse/KCollapse.cy.ts, src/components/KCollapse/KCollapse.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-7701](https://konghq.atlassian.net/browse/KHCP-7701)
=> feat(kcollapse): replace utility classes

.github/CODEOWNERS, src/components/KFileUpload/KFileUpload.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KMultiselect/KMultiselectItem.vue, src/components/KMultiselect/KMultiselectItems.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-7716
Changes:
- introduces `kui-` design tokens in `KMultiselect` component
- removes any usage of Kongponents utility classes in `KMultiselect` component template
=> feat(kmultiselect): introduce kui tokens [KHCP-7716]

.github/CODEOWNERS, docs/components/modal-fullscreen.md, src/components/KModalFullscreen/KModalFullscreen.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-7715](https://konghq.atlassian.net/browse/KHCP-7715)
=> feat(kmodalfullscreen): introduce kui tokens [KHCP-7715]

.github/CODEOWNERS, docs/components/tabs.md, src/components/KTabs/KTabs.vue, src/styles/_tmp-variables.scss
Addresses:
[https://konghq.atlassian.net/browse/KHCP-7727](https://konghq.atlassian.net/browse/KHCP-7727)
=> feat(ktabs): introduce kui tokens [khcp-7727]

.github/CODEOWNERS, src/components/KPagination/KPagination.vue, src/components/KPagination/PaginationOffset.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-7717
Changes:
- introduces `kui-` design tokens in `KPagination` component
- removes any usage of Kongponents utility classes in `KPagination` component template
=> feat(kpagination): introduce kui tokens [KHCP-7717]

.github/CODEOWNERS, docs/components/view-switcher.md, src/components/KViewSwitcher/KViewSwitcher.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-7733
Changes:
- introduces `kui-` design tokens in `KViewSwitcher` component
- removes any usage of Kongponents utility classes in `KViewSwitcher` component template
=> feat(kviewswitcher): introduce kui tokens [KHCP-7733]

.github/CODEOWNERS, src/components/KCodeBlock/KCodeBlock.vue, src/components/KModalFullscreen/KModalFullscreen.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KMultiselect/KMultiselectItem.vue, src/styles/_mixins.scss, src/styles/_tmp-variables.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-7700
Changes:
- introduces `kui-` design tokens in `KCodeBlock` component
- removes any usage of Kongponents utility classes in `KCodeBlock` component template
=> feat(kcodeblock): introduce kui tokens [KHCP-7700]

src/styles/forms/_labels.scss
=> fix(labels): font size

src/components/KTable/KTable.vue
- fixes offset reset on new searchQuery input.
=> fix(ktable): reset offset when new query is issued

docs/vite.config.ts, package.json, renovate.json, src/components/KDateTimePicker/KDateTimePicker.cy.ts, src/components/KDateTimePicker/KDateTimePicker.vue, yarn.lock
https://konghq.atlassian.net/browse/MA-2050
https://deploy-preview-1728--kongponents.netlify.app/components/datetime-picker.html#date-and-time-range
=> feat(datetimepicker): update v-calendar dependency [MA-2030]

sandbox/netlify.toml, src/index.ts
=> chore: comment test

.github/workflows/test.yaml
Generate PR previews for PR with label `create preview package`
=> ci: preview for pr with label

docs/components/renderless/clipboard-provider.md, docs/components/renderless/toggle.md, src/components/KToggle/index.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-8974
=> docs(clipboard-provider): use script setup [KHCP-8974]

docs/components/renderless/k-component.md, docs/components/renderless/toggle.md, src/components/KComponent/index.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-9006, https://konghq.atlassian.net/browse/KHCP-8977
=> fix(kcomponent, ktggle): minor touchups [KHCP-8977]

docs/components/button.md, docs/components/input.md, docs/components/select.md, docs/guide/migrating-to-version-9.md, docs/vite.config.ts, package.json, sandbox/components/SandboxNavComponent.vue, sandbox/components/SandboxSectionComponent.vue, sandbox/pages/SandboxButton.vue, sandbox/pages/SandboxInput.vue, sandbox/router.ts, src/components/KButton/KButton.vue, src/components/KDateTimePicker/KDateTimePicker.vue, src/components/KInput/KInput.cy.ts, src/components/KInput/KInput.vue, src/components/KRadio/KRadio.vue, src/components/KSelect/KSelect.cy.ts, src/components/KSelect/KSelect.vue, src/styles/_mixins.scss, src/styles/_transitions.scss, src/styles/_vars.scss, src/styles/styles.scss, src/types/input.ts, vite.config.ts, yarn.lock
[Jira](https://konghq.atlassian.net/browse/KHCP-8985)
[Figma](https://www.figma.com/file/Yze0SWXl5nKjR0rFdilljK/Components?type=design&node-id=218%3A646&mode=dev)
KInput component reskinning.
Links:
- [Kongponents sandbox](https://deploy-preview-1759--kongponents-sandbox.netlify.app/#/input)
- [Kongponents docs preview](https://deploy-preview-1759--kongponents.netlify.app/components/input.html)
- TODO: khcp-ui adoption PR
- TODO: khcp-ui adoption PR preview
=> feat(kinput): component reskinning [KHCP-8985]

src/components/KSelect/KSelect.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-9483](https://konghq.atlassian.net/browse/KHCP-9483)
[https://konghq.atlassian.net/browse/KHCP-9327](https://konghq.atlassian.net/browse/KHCP-9327)
=> fix(kselect): filter input [khcp-9483]

docs/guide/migrating-to-version-9.md, src/components/KDropdown/KDropdownItem.vue
=> fix(*): misc alpha fixes

src/components/KDropdown/KDropdown.cy.ts, src/components/KDropdown/KDropdownItem.vue
=> fix(kdropdownitem): clean up bound data-testid attribute

docs/guide/migrating-to-version-9.md, package.json, src/components/KBadge/KBadge.vue, src/components/KBreadcrumbs/KBreadcrumbs.vue, src/components/KCodeBlock/KCodeBlock.vue, src/components/KStepper/stepper-icons/KActiveState.vue, src/components/KStepper/stepper-icons/KCompletedState.vue, src/components/KStepper/stepper-icons/KPendingState.vue, yarn.lock
=> fix(kbadge): minor fix

sandbox/pages/SandboxTextarea.vue, src/components/KTextArea/KTextArea.cy.ts, src/components/KTextArea/KTextArea.vue
Handle textarea `characterLimit` prop `true` value
=> fix(ktextarea): fix character limit prop logic

src/components/KModalFullscreen/KModalFullscreen.vue
Removes button style overwrites from KModalFullscreen
=> fix(kfullscreenmodal): fix button height

docs/components/button.md, docs/guide/migrating-to-version-9.md, src/components/KButton/KButton.vue, src/components/KDropdown/KDropdown.vue
Add deprecation warnings for deprecated props and slots in components.
=> fix(*): add deprecation warnings

docs/components/dropdown.md
=> docs(dropdown): deprecated prop warn

src/components/KSelect/KSelect.cy.ts
This PR adds some test cases to cover #1843 and #1844.
=> test(kselect): add test cases

docs/components/radio.md, package.json, sandbox/pages/SandboxCheckbox.vue, sandbox/pages/SandboxLabel.vue, sandbox/pages/SandboxRadio.vue, src/components/KCheckbox/KCheckbox.vue, src/components/KCodeBlock/KCodeBlock.vue, src/components/KFileUpload/KFileUpload.vue, src/components/KRadio/KRadio.vue, src/components/KSegmentedControl/KSegmentedControl.vue, src/components/KSelect/KSelect.vue, yarn.lock
[Jira](https://konghq.atlassian.net/browse/KHCP-9570)
[Figma](https://www.figma.com/file/Yze0SWXl5nKjR0rFdilljK/Components?type=design&node-id=763%3A12969&mode=dev)
Updates KRadio card styles
Links:
- [Kongponents sandbox](https://deploy-preview-1851--kongponents-sandbox.netlify.app/#/radio)
- [Kongponents docs preview](https://deploy-preview-1851--kongponents.netlify.app/components/radio.html)
=> fix(kradio): update radio card styles [KHCP-9491]

src/components/KCard/KCard.vue, src/components/KPagination/KPagination.vue, src/components/KPagination/PaginationOffset.vue
Few component fixes:
KCard:
before
after
=> fix(*): component style fixes

src/components/KDropdown/KDropdownItem.vue
Minor but mighty fix in KDropdownItem
=> fix(kdropdown): minor fix

src/components/KButton/KButton.vue, src/components/KDropdown/KDropdownItem.vue
=> fix(kdropdown): kdropdownitem width fix

docs/components/table.md, src/components/KTable/KTable.vue
https://konghq.atlassian.net/browse/KHCP-9591
=> feat(KTable): add hasNextPage support for offset pagination [KHCP-9591]

src/components/KMultiselect/KMultiselectItem.vue, src/components/KPagination/PaginationOffset.vue
* add disabled attribute to pagination offset buttons
* fix KMultiselect item description font size
=> fix(kpagination, kmultiselect): misc styling fixes

docs/components/slideout.md, src/components/KSlideout/KSlideout.vue
Add maxWidth prop for KSlideout
=> feat(KSlideout): add maxWidth prop

src/styles/_mixins.scss, src/styles/mixins/_input-select.scss
Adds a shared selects mixin (for KSelect and KMultiselect)
=> fix(mixins): add selects shared mixin

src/components/KCard/KCard.vue
=> fix(kcard): card content width

cypress/support/index.ts
=> test: fix custom command

src/components/KCard/KCard.vue
=> fix(kcard): add box-sizing rule

src/styles/mixins/_input-text.scss
Breaks out input text styles into a mixin
=> fix(mixins): add input text mixin

cli/template/docs/Template.md, docs/components/tabs.md, docs/guide/migrating-to-version-9.md, sandbox/pages/SandboxTabs.vue, src/components/KTabs/KTabs.cy.ts, src/components/KTabs/KTabs.vue, src/types/tabs.ts
[Jira](https://konghq.atlassian.net/browse/KHCP-9003)
[Figma](https://www.figma.com/file/Yze0SWXl5nKjR0rFdilljK/Components?type=design&node-id=297%3A3525&mode=dev)
`KTabs` component reskin.
Links:
- [Kongponents sandbox](https://deploy-preview-1914--kongponents-sandbox.netlify.app/#/tabs)
- [Kongponents docs preview](https://deploy-preview-1914--kongponents.netlify.app/components/tabs.html)
=> feat(ktabs): reskin component [KHCP-9003]

src/components/KMultiselect/KMultiselect.vue
=> test(kmultiselect): fix component tests

src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue
Give KPop a unique target in KSelect and KMultiselect
=> fix(kselect, kmultiselect): kpop unique target

src/components/KMultiselect/KMultiselect.vue
=> fix(kmultiselect): fix staging dismiss icon

docs/components/segmented-control.md, docs/guide/migrating-to-version-9.md, sandbox/index.ts, sandbox/pages/SandboxSegmentedControl.vue, sandbox/router/sandbox-routes.ts, src/components/KDateTimePicker/KDateTimePicker.cy.ts, src/components/KSegmentedControl/KSegmentedControl.cy.ts, src/components/KSegmentedControl/KSegmentedControl.vue, src/styles/_vars.scss, src/types/segmented-control.ts
[Jira](https://konghq.atlassian.net/browse/KHCP-8997)
[Figma](https://www.figma.com/file/Yze0SWXl5nKjR0rFdilljK/Components?type=design&node-id=1244%3A14989&mode=dev)
`KSegmentedControl` component reskin
Links:
- [Kongponents sandbox](https://deploy-preview-1953--kongponents-sandbox.netlify.app/#/segmentedcontrol)
- [Kongponents docs preview](https://deploy-preview-1953--kongponents.netlify.app/components/segmented-control.html)
=> feat(ksegmentedcontrol): component reskin [KHCP-8997]

package.json, src/components/KTabs/KTabs.vue, yarn.lock
=> fix(ktabs): minor styling fixes

package.json, vite.config.ts, yarn.lock
=> chore: vite plugin vue devtools

src/components/KFileUpload/KFileUpload.vue
Related to DD error: https://konghq.atlassian.net/browse/KHCP-10556
=> fix(kfileupload): file name [KHCP-10556]

src/components/KDateTimePicker/KDateTimePicker.vue, src/styles/_mixins.scss
https://konghq.atlassian.net/browse/MA-2397
=> fix(kdatetimepicker): datetimepicker height [MA-239]

src/components/KDateTimePicker/KDateTimePicker.vue
https://konghq.atlassian.net/browse/MA-2582
=> fix(datetimepicker): no border needed around kbutton [MA-2582]

docs/components/external-link.md, docs/guide/migrating-to-version-9.md, src/components/KExternalLink/KExternalLink.vue
[Jira](https://konghq.atlassian.net/browse/KHCP-8981)
`KExternalLink` component reskin
=> feat(kexternallink): reskin component [KHCP-8981]

src/components/KModalFullscreen/KModalFullscreen.vue
[Jira](https://konghq.atlassian.net/browse/KHCP-8991)
`KModalFullScreen` component styling touch-ups
=> fix(kmodalfullscreen): touch up component styles [KHCP-8991]

docs/.vitepress/config.ts, netlify.toml
https://konghq.atlassian.net/browse/KHCP-10667
- Add canonical links to all pages
- Add generated sitemap
- Add `rel="nofollow"` to the other doc version links in the navbar
=> docs(main): fix seo issues [KHCP-10667]

docs/.vitepress/config.ts, netlify.toml, src/components/KModal/KModal.vue
https://konghq.atlassian.net/browse/KHCP-10667
- Add `meta.robots` `noindex,nofollow` - this will be removed before merging into `main`
- Add canonical links to all pages (currently pointing to alpha deploy preview)
- Add generated sitemap
- Add `rel="nofollow"` to the other doc version links in the navbar
=> docs(alpha): fix seo issues [KHCP-10667]

docs/components/datetime-picker.md, docs/components/dropdown.md, docs/components/external-link.md, docs/components/tooltip.md, docs/guide/migrating-to-version-9.md, sandbox/index.ts, sandbox/pages/SandboxDateTimePicker.vue, sandbox/pages/SandboxDropdown.vue, sandbox/pages/SandboxModals.vue, sandbox/pages/SandboxSegmentedControl.vue, sandbox/router/sandbox-routes.ts, src/components/KCopy/KCopy.vue, src/components/KDateTimePicker/KDateTimePicker.cy.ts, src/components/KDateTimePicker/KDateTimePicker.vue, src/components/KExternalLink/KExternalLink.vue, src/components/KModalFullscreen/KModalFullscreen.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KTooltip/KTooltip.cy.ts, src/components/KTooltip/KTooltip.vue, src/styles/mixins/_input-text.scss
`KTooltip` and `KDateTiePicker` component reskin:
https://github.com/Kong/kongponents/pull/1988
https://github.com/Kong/kongponents/pull/2000
=> feat(ktooltip, kdatetimepicker): reskin components

docs/components/toaster.md, docs/guide/migrating-to-version-9.md, sandbox/index.ts, sandbox/pages/SandboxToaster.vue, sandbox/router/sandbox-routes.ts, src/components/KToaster/KToaster.cy.ts, src/components/KToaster/KToaster.vue, src/components/KToaster/ToastManager.ts, src/styles/_transitions.scss, src/types/toaster.ts
[Jira](https://konghq.atlassian.net/browse/KHCP-9005)
[Figma](https://www.figma.com/file/Yze0SWXl5nKjR0rFdilljK/Components?type=design&node-id=497%3A9761&mode=dev&t=lcG4fMxcpZoeYwsC-1)
`KToaster` component reskin
Links:
- [Kongponents sandbox](https://deploy-preview-2015--kongponents-sandbox.netlify.app/#/toaster)
- [Kongponents docs preview](https://deploy-preview-2015--kongponents.netlify.app/components/toaster.html)
=> feat(ktoaster): component reskin [KHCP-9005]

src/components/KSlideout/KSlideout.vue
Includes fixes for issues discussed in https://github.com/Kong/kongponents/pull/2020
=> fix(kslideout): adoption fixes

package.json, yarn.lock
=> docs: fix deploys

src/components/KSlideout/KSlideout.vue
=> fix(kslideout): remove slotted title icon styling

src/components/KModal/KModal.vue, src/components/KSlideout/KSlideout.vue, src/components/KToaster/KToaster.vue, src/components/KTruncate/KTruncate.vue
Update `@keyup` to `@keydown` events on `role="button"` icons
=> fix(*): fix keyboard events

sandbox/pages/SandboxMultiselect.vue
Add example in `KMultiselect` sandbox
=> chore(sandbox): multiselect resize example

docs/components/slideout.md, docs/components/toaster.md, docs/components/truncate.md, docs/guide/migrating-to-version-9.md, sandbox/index.ts, sandbox/pages/SandboxSlideout.vue, sandbox/pages/SandboxToaster.vue, sandbox/router/sandbox-routes.ts, src/components/KModal/KModal.vue, src/components/KSlideout/KSlideout.cy.ts, src/components/KSlideout/KSlideout.vue, src/components/KToaster/KToaster.cy.ts, src/components/KToaster/KToaster.vue, src/components/KToaster/ToastManager.ts, src/components/KTruncate/KTruncate.cy.ts, src/components/KTruncate/KTruncate.vue, src/styles/_transitions.scss, src/types/toaster.ts
`KTruncate`, `KSlideout` and `KToaster` components reskin
- https://github.com/Kong/kongponents/pull/2009
- https://github.com/Kong/kongponents/pull/2012
- https://github.com/Kong/kongponents/pull/2015
=> feat(ktruncate, kslideout, ktoaster): components reskin

src/components/KMultiselect/KMultiselect.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-10321
Fix KMultiselect behaviour on window resize
**Functional testing instructions:**
Compare component behaviour in `alpha` branch [sandbox](https://kongponents-sandbox.netlify.app/#/multiselect) (incorrect) to this branch [sandbox](https://deploy-preview-2039--kongponents-sandbox.netlify.app/#/multiselect).
=> fix(kmultiselect): react to resize [KHCP-10321]

src/components/KPagination/KPagination.vue, src/components/KPagination/PaginationOffset.vue
=> fix(kpagination): reduce spacing, icon size

src/components/KCopy/KCopy.vue
=> fix(kcopy): icon & tooltip text styles

docs/components/collapse.md, src/components/KCopy/KCopy.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-11057
=> fix(kcopy): substring of undefined [KHCP-11057]

src/components/KTreeList/KTreeDraggable.vue, src/components/KTreeList/KTreeList.vue
=> fix(ktreelist): tweak unscoped styles

sandbox/pages/SandboxModals.vue, src/components/KModal/KModal.vue
Allow setting title icon color in full screen KModal
=> fix(kmodal): remove enforcing title icon color

src/components/KCard/KCard.vue
Reduce KCard title font size and line height
=> fix(kcard): title font size

docs/components/modal.md, docs/components/prompt.md, sandbox/pages/SandboxModals.vue, src/components/KModal/KModal.cy.ts, src/components/KModal/KModal.vue, src/components/KPrompt/KPrompt.vue, src/types/prompt.ts
Jira: https://konghq.atlassian.net/browse/KHCP-11113
Adds `inputAutofocus` prop in KModal and KPrompt
=> fix(kmodal): add input autofocus prop [KHCP-11113]

docs/components/radio.md, docs/components/tabs.md, docs/components/toaster.md, sandbox/pages/SandboxBadge.vue, sandbox/pages/SandboxButton.vue, sandbox/pages/SandboxCard.vue, sandbox/pages/SandboxCopy.vue, sandbox/pages/SandboxDropdown.vue, sandbox/pages/SandboxInputSwitch.vue, sandbox/pages/SandboxModals.vue, sandbox/pages/SandboxRadio.vue, sandbox/pages/SandboxSelect.vue, sandbox/pages/SandboxTable.vue, sandbox/pages/SandboxToaster.vue, src/components/KSelect/KSelect.vue, src/components/KToaster/KToaster.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-11152
Changes:
* fix invisible user input in KSelect when `selected-item-template` is set
* fix KToaster width on mobile
=> fix(kselect): invisible user input [KHCP-11152]

src/components/KLabel/KLabel.vue, src/components/KModal/KModal.vue, src/components/KTooltip/KTooltip.vue
=> fix(kmodal): toggle focus trap off on unmounted

package.json, yarn.lock
=> docs: update vitepress

docs/components/skeleton.md, docs/guide/migrating-to-version-9.md, sandbox/index.ts, sandbox/pages/SandboxSkeleton.vue, sandbox/router/sandbox-routes.ts, src/components/KSkeleton/CardSkeleton.vue, src/components/KSkeleton/FormSkeleton.vue, src/components/KSkeleton/FullScreenGenericSpinner.vue, src/components/KSkeleton/FullScreenKongSkeleton.vue, src/components/KSkeleton/KSkeleton.cy.ts, src/components/KSkeleton/KSkeleton.vue, src/components/KSkeleton/KSkeletonBox.vue, src/components/KSkeleton/SkeletonBase.vue, src/components/KSkeleton/TableSkeleton.vue, src/styles/_mixins.scss, src/styles/mixins/_loaders.scss
[Jira](https://konghq.atlassian.net/browse/KHCP-8999)
[Figma](https://www.figma.com/file/Yze0SWXl5nKjR0rFdilljK/Components?type=design&node-id=2020%3A12479&mode=dev&t=uQGBuUCQfJdk9Uab-1)
`KSkeleton` component reskin
Links:
- [Kongponents sandbox](https://deploy-preview-2082--kongponents-sandbox.netlify.app/#/skeleton)
- [Kongponents docs preview](https://deploy-preview-2082--kongponents.netlify.app/components/skeleton.html)
=> feat(kskeleton): component reskin [KHCP-8999]

netlify.toml
=> chore(netlify): bump node version env

netlify.toml
=> Revert "chore(netlify): bump node version env"

sandbox/pages/SandboxBreadcrumbs.vue, src/components/KBreadcrumbs/KBreadcrumbs.vue
Addresses: https://github.com/Kong/kongponents/commit/b3fdd844fd522f08f70974150caf51d36637d6f1
=> fix(kbreadcrumbs): make last item a link

docs/components/button.md, src/components/KPrompt/KPrompt.vue
Adds `aria-label` on confirmation text input field in KPrompt
=> fix(kprompt): add arial-label

docs/components/datetime-picker.md
Fix issues thrown by `docs:build` command
=> docs(datetime-picker): fix build issues

src/utilities/ShortcutManager.ts
Related to [DD](https://app.datadoghq.com/rum/error-tracking?issueId=885e7b18-f0e5-11ee-8739-da7ad0900002) error
=> fix(kcodeblock): fix shortcut manager runtime undefined

src/components/KCodeBlock/KCodeBlock.vue
Jira: https://konghq.atlassian.net/browse/KHCP-11554
DD: https://app.datadoghq.com/rum/error-tracking?fromUser=false&issueId=e0b8d8f8-f18f-11ee-be1d-da7ad0900002&view=spans&from_ts=1713361190200&to_ts=1713364790200&live=true
=> fix(KCodeBlock): add question marks [KHCP-11554]

src/components/KTable/ColumnVisibilityMenu.vue
Apply design feedback - button/dropdown alignment.
=> fix(ktable): column visibility design feedback

src/components/KSelect/KSelect.vue
This PR fixes incorrect event triggering:
https://github.com/Kong/kongponents/assets/10095631/0865b29f-4019-4390-a393-6fde9e75bb83
Note: hide whitespace for a better review experience.
=> fix(kselect): avoid incorrect event triggering with null

docs/components/collapse.md, sandbox/pages/SandboxCollapse.vue, src/components/KCollapse/KCollapse.cy.ts, src/components/KCollapse/KCollapse.vue
Adds `title` slot in KCollapse
=> fix(kcollapse): add title slot

docs/components/catalog.md, docs/components/select.md, docs/components/toaster.md, src/types/catalog.ts, src/types/select.ts
=> docs(*): add comments in interfaces

src/components/KCodeBlock/KCodeBlock.vue, src/components/KInput/KInput.vue, src/components/KTextArea/KTextArea.vue
Jira: https://konghq.atlassian.net/browse/KHCP-12065
=> fix(*): add question marks before tostring [KHCP-12065]

.github/workflows/test.yaml
=> chore: preview package instructions message

src/components/KBadge/KBadge.vue, src/components/KCopy/KCopy.vue
=> fix(kbadge, kcopy): minor fix

cli/index.ts, cli/tsconfig.json, cli/utils/index.ts, cli/utils/kongponents.ts, package.json
=> cli: update for node 20

src/global-components.ts
The module needs an export to be properly picked up
=> fix(types): module needs an export

sandbox/pages/SandboxDropdown.vue, src/components/KDropdown/KDropdown.vue
Fix close dropdown popover on item click behaviour
=> fix(kdropdown): close on popover click

src/components/KPop/KPop.vue
=> fix(kpop): flip

docs/guide/migrating-to-version-9.md
=> docs(migration-guide): minor fixes

src/components/KBreadcrumbs/KBreadcrumbs.vue, src/components/KDropdown/KDropdownItem.vue
The prop and its fallback value don't match. I checked the figma mocks and can confirm the fallback is correct, so I updated the prop values.
=> fix(*): inconsistent tokens

package.json, src/types/index.ts
=> ci: trigger v9 release

.vscode/settings.json
=> chore(vscode/settings): newline

src/components/KMultiselect/KMultiselect.vue, src/styles/mixins/_input-text.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-12491
Fix autofocus on input in KMultiselect dropdown upon opening
=> fix(kmultiselect): autofocus on input upon opening [KHCP-12491]

src/components/KSelect/KSelect.vue
=> fix: trigger ci

src/components/KSkeleton/CardSkeleton.vue
=> fix(kskeleton): box sizing

.github/workflows/publish.yaml, .github/workflows/test.yaml, src/components/KToaster/ToastManager.ts
Fix the dist artifacts broken from https://github.com/Kong/kongponents/pull/2283
=> fix: dist artifacts

sandbox/pages/SandboxAlert.vue, src/components/KAlert/KAlert.vue
=> fix(kalert): break the word to prevent a long text overflow

src/components/KToaster/KToaster.vue
=> fix(ktoaster): add box-sizing

src/components/KPrompt/KPrompt.vue
=> fix(kprompt): hide error message once confirm text typed in

sandbox/pages/SandboxDropdown.vue, src/components/KCard/KCard.vue, src/components/KDropdown/KDropdown.vue, src/components/KPop/KPop.vue
Add `aria-label` to dropdown trigger button
=> fix(kpop): bind aria-controls to trigger [KHCP-12832]

docs/components/badge.md
=> docs(badge): add default appearance

docs/components/tree-list.md, src/components/KTreeList/KTreeDraggable.vue, src/components/KTreeList/KTreeList.vue, src/types/tree-list.ts
Update the type interfaces for `KTreeList`
=> fix(ktreelist): type interfaces

src/components/KRadio/KRadio.vue
Support setting the `modelValue` to `null` to unset the selection.
=> feat(kradio): support setting to null

src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue, src/components/KSelect/KSelectItems.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-12967
Adds arrow up and down navigation through items in KSelect
=> fix(kselect): arrow down navigation [KHCP-12967]

src/components/KTableView/KTableView.vue
=> fix(ktableview): minor fix

src/components/KCodeBlock/KCodeBlock.vue
* make code block focusable upon click so that keyboard events can work
* fix typo: Options -> Option
=> fix(kcodeblock): keyboard shortcut for copy should work

src/components/KTable/KTable.vue
=> fix(ktable): column visibility alignment

docs/components/table-view.md
=> docs(ktableview): toolbar default items note

docs/components/catalog.md, src/components/KCatalog/KCatalog.cy.ts, src/components/KCatalog/KCatalog.vue, src/components/KTable/KTable.vue
Jira: https://konghq.atlassian.net/browse/KHCP-13325
Support offset pagination in KCatalog
=> feat(kcatalog): support offest pagination [KHCP-13325]

commitlint.config.ts
=> fix: update the helpUrl

docs/components/renderless/toggle.md
Addresses: https://konghq.atlassian.net/browse/KHCP-13938
=> docs(toggle): fix component docs [KHCP-13938]

src/components/KCodeBlock/KCodeBlock.vue
=> fix(kcodeblock): type error

src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.vue
=> fix(kselect, kmultiselect): create item on enter logic

docs/.vitepress/theme/_overrides.scss, docs/.vitepress/theme/_variables.scss, docs/.vitepress/theme/index.scss, docs/vite.config.ts, package.json, pnpm-lock.yaml, src/styles/_mixins.scss, src/styles/_transitions.scss, src/styles/_vars.scss, src/styles/globals.scss, src/styles/mixins/_badges.scss, src/styles/mixins/_buttons.scss, src/styles/mixins/_cards.scss, src/styles/mixins/_common.scss, src/styles/mixins/_input-radio-checkbox.scss, src/styles/mixins/_input-select.scss, src/styles/mixins/_input-text.scss, src/styles/mixins/_inputs.scss, src/styles/mixins/_label.scss, src/styles/mixins/_loaders.scss, src/styles/mixins/_tables.scss, src/styles/styles.scss, vite.config.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-14088
Build size for `main`:
=> fix(*): sass @import to @use [KHCP-13755]

src/components/KTableData/KTableData.vue, src/components/KTableView/KTableView.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-14032
Fix `@update:table-preferences` event emits
=> fix(ktableview, ktabledata): table updates event [KHCP-14032]

sandbox/pages/SandboxAlert.vue, src/components/KAlert/KAlert.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-14152
Add default styling for slotted links in KAlert
=> fix(kalert): slotted links default styling [KHCP-14152]

docs/components/table-view.md
=> docs(table-view): minor tweak

src/styles/mixins/_tables.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-14265
In the nested table, add spacing on the left to align it with the first column of the parent table
=> fix(ktableview): align nested table with parent [KHCP-14265]

src/components/KAlert/KAlert.vue
Apply the `KAlert > code` styles to `:deep` elements as well
=> fix(kalert): code style

package.json, pnpm-lock.yaml, sandbox/composables/useShiki.ts, sandbox/pages/SandboxCodeBlock.vue, src/components/KCodeBlock/KCodeBlock.vue, vite.config.ts
Add sandbox example with syntax highlighting + reactive code/highlighted lines
=> chore(kcodeblock): add sandbox example

src/components/KAlert/KAlert.vue
JIRA ticket : https://konghq.atlassian.net/browse/KHCP-14565
Fixed Kalert modifying Kbutton text color when the button is of type external link( :to is sent in prop)
=> fix(kalert): kbutton text color within kalerts [KHCP-14565]

src/components/KCodeBlock/KCodeBlock.vue
[Jira Ticket
](https://konghq.atlassian.net/jira/software/c/projects/KHCP/issues/KHCP-12992)for screen sizes > $kui-breakpoint-laptop hide copy button only display if hovered on the code block
=> refactor(kcodeblock): show copy button on kcodeblock hover [KHCP-12992]

src/components/KTabs/KTabs.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-14697](https://konghq.atlassian.net/browse/KHCP-14697)
This PR adds **data-testid** attribute to "li" elements in **KTabs** to enhance traceability.
=> fix(ktabs): add data-testid to list items

src/components/KCodeBlock/KCodeBlock.vue
Jira ticket : https://konghq.atlassian.net/browse/KHCP-14618
Updated the secondary actions position as sticky to make sure actions are visible when scrolled to the bottom
=> refactor(kcodeblock): secondary actions as sticky position [KHCP-14618]

README.md
Add documentation for approvals.
=> docs(security): approvals and releases [SEC-1280]

src/components/KSelect/KSelect.vue
=> fix(kselect): fix selection color upon keyboard focus

.stylelintrc.mjs, src/styles/mixins/_input-radio-checkbox.scss
Add stylelint spacing rules and fix
```
'@stylistic/declaration-colon-space-after': 'always',
'@stylistic/media-feature-colon-space-after': 'always',
```
=> fix(stylelint): add spacing rules

src/components/KTreeList/KTreeDraggable.vue
Increase `fallbackTolerance` to make selecting an item easier
=> fix(ktreelist): increase fallback tolerance

docs/components/table-view.md, sandbox/pages/SandboxTableData.vue, sandbox/pages/SandboxTableView/SandboxTableView.vue, src/components/KTableData/KTableData.vue, src/components/KTableView/KTableView.vue, src/types/table.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-15470
Adds `row-actions-toggle` event in KTableView and KTableData
=> fix(ktableview, ktabledata): add row-actions-toggle event [KHCP-15470]

src/types/popover.ts
Allow `data-testid` in `PopoverAttributes` type
=> fix(types): allow data-testid in popover attributes

docs/components/button.md, src/components/KButton/KButton.vue, src/types/button.ts
[KM-1094](https://konghq.atlassian.net/browse/KM-1094)
[KM-1094]: https://konghq.atlassian.net/browse/KM-1094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(kbutton): migrate to type-based defineProps

src/components/KButton/KButton.vue, src/types/button.ts
[KM-1094](https://konghq.atlassian.net/browse/KM-1094)
Preview PR: https://github.com/Kong/konnect-ui-apps/pull/6289
[KM-1094]: https://konghq.atlassian.net/browse/KM-1094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(kbutton): improve slot types

src/components/KAlert/KAlert.vue, src/types/alert.ts
[KM-1099](https://konghq.atlassian.net/browse/KM-1099)
Preview PR: https://github.com/Kong/konnect-ui-apps/pull/6306
[KM-1099]: https://konghq.atlassian.net/browse/KM-1099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(kalert): ts improvement for kalert

src/components/KPop/KPop.cy.ts, src/components/KPop/KPop.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-15519
Close KPop on esc key press
=> fix(kpop): close on esc key press [KHCP-15519]

src/components/KBadge/KBadge.vue, src/types/badge.ts
[KM-1101]
Preview PR: https://github.com/Kong/konnect-ui-apps/pull/6328
[KM-1101]: https://konghq.atlassian.net/browse/KM-1101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(kbadge): typescript improvement for k-badge [KM-1101]

src/components/KEmptyState/KEmptyState.vue, src/types/empty-state.ts
KM-1111
Typescript improvements for `KEmptyState`
Konnect Preview PR: https://github.com/Kong/konnect-ui-apps/pull/6342
=> refactor(kemptystate): ts improvements

src/components/KCard/KCard.vue, src/types/alert.ts, src/types/button.ts, src/types/card.ts
[KM-1109](https://konghq.atlassian.net/browse/KM-1109)
...and unified the comment formatting a bit.
[KM-1109]: https://konghq.atlassian.net/browse/KM-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(kcard): improve types

src/components/KCollapse/KCollapse.vue, src/types/collapse.ts
[KM-1137](https://konghq.atlassian.net/browse/KM-1137)
- Preview PR: https://github.com/Kong/konnect-ui-apps/pull/6393 ✅ CI passed
[KM-1137]: https://konghq.atlassian.net/browse/KM-1137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(kcollapse): improve typings for kcollapse

src/components/KCodeBlock/KCodeBlock.vue, src/components/KCodeBlock/KCodeBlockIconButton.vue, src/types/code-block.ts
[KM-1133](https://konghq.atlassian.net/browse/KM-1133)
Preview PR:
- https://github.com/Kong/konnect-ui-apps/pull/6385 ✅ CI passed
[KM-1133]: https://konghq.atlassian.net/browse/KM-1133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(kcodeblock): improve typing for kcodeblock

docs/components/popover.md, src/components/KPop/KPop.vue, src/components/KPop/KPopTeleportWrapper.vue, src/types/popover.ts
[KM-1167](https://konghq.atlassian.net/browse/KM-1168)
[KM-1167]: https://konghq.atlassian.net/browse/KM-1167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kpop): improve typings for kpop

docs/components/dropdown.md, src/components/KDropdown/KDropdown.vue, src/components/KDropdown/KDropdownItem.vue, src/types/dropdown.ts, src/types/popover.ts
[KM-1141](https://konghq.atlassian.net/browse/KM-1141)
[KM-1141]: https://konghq.atlassian.net/browse/KM-1141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kdropdown): ts improvements for kdropdown

docs/components/badge.md, sandbox/pages/SandboxBadge.vue, src/components/KBadge/KBadge.vue, src/types/badge.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-15964
Add `tooltipAttributes` prop in KBadge
=> fix(kbadge): add tooltip attributes prop [KHCP-15964]

cypress.config.ts
Resolve a (sudden-ish) resolution issue in the Cypress config.
=> test: cypress errors

src/components/KSlideout/KSlideout.vue, src/types/slideout.ts
KM-1221
Typescript improvements for `KSlideout`
[Konnect Preview](https://github.com/Kong/konnect-ui-apps/pull/6625)
=> feat: ts improvement for kslideout

docs/components/select.md, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue, src/components/KSelect/KSelectItems.vue, src/types/checkbox.ts, src/types/input.ts, src/types/label.ts, src/types/popover.ts, src/types/select.ts
[KM-1165](https://konghq.atlassian.net/browse/KM-1165)
[KM-1165]: https://konghq.atlassian.net/browse/KM-1165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kselect): ts improvements for kselect

src/components/KSkeleton/CardSkeleton.vue, src/components/KSkeleton/FormSkeleton.vue, src/components/KSkeleton/FullScreenGenericSpinner.vue, src/components/KSkeleton/FullScreenKongSkeleton.vue, src/components/KSkeleton/KSkeleton.vue, src/components/KSkeleton/KSkeletonBox.vue, src/components/KSkeleton/TableSkeleton.vue, src/types/skeleton.ts, src/types/utils.ts
[KM-1233](https://konghq.atlassian.net/browse/KM-1233)
[KM-1233]: https://konghq.atlassian.net/browse/KM-1233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kskeleton): ts improvements for kskeleton

src/types/file-upload.ts
[KM-1138](https://konghq.atlassian.net/browse/KM-1138)
Fix type import.
[KM-1138]: https://konghq.atlassian.net/browse/KM-1138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kfileupload): fix type import

src/components/KStepper/KStep.vue, src/components/KStepper/KStepper.vue, src/types/stepper.ts
[KM-1252](https://konghq.atlassian.net/browse/KM-1252)
*Not used in Konnect/KM.*
[KM-1252]: https://konghq.atlassian.net/browse/KM-1252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kstepper): ts improvements for kstepper

src/components/KPrompt/KPrompt.vue, src/types/modal.ts, src/types/prompt.ts
[KM-1231](https://konghq.atlassian.net/browse/KM-1231)
[KM-1231]: https://konghq.atlassian.net/browse/KM-1231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kprompt): ts improvements for kprompt

src/components/KRadio/KRadio.vue, src/types/radio.ts
[KM-1230](https://konghq.atlassian.net/browse/KM-1230)
[KM-1230]: https://konghq.atlassian.net/browse/KM-1230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kradio): ts improvements for kradio

src/components/KToaster/KToaster.vue, src/components/KToaster/ToastManager.ts, src/types/toaster.ts
=> feat(ktoaster): precise typings for ktoaster

src/components/KTabs/KTabs.vue, src/types/tabs.ts
[KM-1337](https://konghq.atlassian.net/browse/KM-1337)
[KM-1337]: https://konghq.atlassian.net/browse/KM-1337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ktabs): ts improvements for ktabs

docs/components/datetime-picker.md, sandbox/pages/SandboxDateTimePicker.vue, src/components/KDateTimePicker/KDateTimePicker.vue, src/types/date-time-picker.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-16750
Add `readonly` prop in KDateTimePicker
=> fix(kdatetimepicker): add readonly prop [KHCP-16750]

package.json, pnpm-lock.yaml, pnpm-workspace.yaml
This reverts commit 16c275aa55a26251640668102948842635f543c8.
=> revert: sandbox layout update

package.json, pnpm-lock.yaml
Preview for https://github.com/Kong/eslint-config-kong-ui/pull/40.
=> chore: bump eslint config

src/components/KTreeList/KTreeDraggable.vue, src/components/KTreeList/KTreeItem.vue, src/components/KTreeList/KTreeList.vue, src/types/tree-list.ts
[KM-1340](https://konghq.atlassian.net/browse/KM-1340)
[KM-1340]: https://konghq.atlassian.net/browse/KM-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ktreelist): ts improvements for ktreelist

src/components/KDateTimePicker/CalendarWrapper.vue
=> fix: forgot relativeDateTime supposed to show time inputs

src/components/KSlider/KSlider.vue
This PR fixes a bug where the component couldn't work when `min`, `max` and/or `step` is a floating-point number.
| Before | After |
| - | - |
| https://github.com/user-attachments/assets/7b6aa149-476b-4a22-8870-92775ffbffd5 | https://github.com/user-attachments/assets/a02d26a7-16f5-40b5-b8f9-6ca37f7225e3 |
=> fix(kslider): floating point rounding error

.github/workflows/cleanup-preview-packages.yaml, .github/workflows/commitlint.yaml, .github/workflows/get-changed-files.yaml, .github/workflows/pr-closed.yaml, .github/workflows/pr-on-close.yaml, .github/workflows/publish.yaml, .github/workflows/renovate-auto-approve.yaml, .github/workflows/test.yaml
Adding Harden Runner to all the Workflows.
=> Harden Runner Integration

src/components/KPop/KPop.vue
[KM-1684](https://konghq.atlassian.net/browse/KM-1684)
[Preview PR on Konnect](https://github.com/Kong/konnect-ui-apps/pull/8154)
`<KPop>` previously attached a single `click` event listener on the `document` and determined behavior based on the event’s origin.
This caused an issue when a parent element used `stopPropagation` in its `click` handler, since the global listener never fired, causing the `<KPop>` component inside to stop working.
```vue
<div @click.stop> 
...
<KPop>...</KPop>
...
</div>
```
We cannot simply switch the global event listener to use the capture phase, as this would break the existing behavior where stopping propagation inside the popover trigger prevents the popover from being toggled.
So this PR separates the logic into three independent handlers, each …
=> fix(kpop): fix event handlers to allow stopPropagation work outside the popover
