packages/KButton/KButton.vue
resets focus state to browser default
=> style(KButton): reset focus state

docs/.vuepress/config.js, docs/components/alert.md, docs/components/popover.md, packages/KPop/KPop.vue
Adds `opened` and `closed` events so kpop users can load kpop content on-demand. I also corrected some of the KPop docs and improved the isSVG docs to show a good example.
=> feat(kpop): add opened/closed events

docs/components/button.md, docs/components/table.md, packages/KButton/KButton.vue, packages/KTable/KTable.vue
It was realized that when using a `KButton` in `KTable` the padding of the button dramatically increased the table row height. This is undesired so this fix will remove any padding. If a design/user calls for it they can override in their project
* Remove button top and bottom padding
=> style(KTable) Remove button padding

packages/KTable/KTable.vue
Swap out css var overrides for negative margin so buttons look normal but row is short
=> fix(KTable) Swap vars for negative margin

packages/KIcon/package.json
Adds './icons' folder to the KIcon's npm package, then we can imports KIcon or KIcon related Kongponents by the vue files.
* includes './icons' to the package.json of `KIcon`
=> chore(KIcon) add folder to package.json - intf-2259

packages/KAlert/package.json, packages/KBadge/package.json, packages/KButton/package.json, packages/KCard/package.json, packages/KCheckbox/package.json, packages/KEmptyState/package.json, packages/KIcon/package.json, packages/KInput/package.json, packages/KInputSwitch/package.json, packages/KLabel/package.json, packages/KModal/package.json, packages/KPop/package.json, packages/KRadio/package.json, packages/KSlideout/package.json, packages/KTable/package.json, packages/KTest/package.json, packages/KToaster/package.json, packages/KoolTip/package.json, packages/Krumbs/package.json
The PR(#181 ) builds new UMD modules with `Postcss` enable. But new modules haven't publish, since `lerna` did not mark the component as `changed`
In this PR, we pump up package version to trigger the `lerna` publish process.
* pumps up version in package.json
=> chore(*) publish new UMD modules

packages/KSlideout/KSlideout.vue
We need to add a hardcoded color fallback to a css-var, then the UMD module can be use in IE11.
* adds color fallback
=> style(kslideout) adds hardcoded color fallback

packages/KButton/KButton.vue, packages/KCard/KCard.vue
Changing height of kbutton icons to be auto, as having a hardcoded size does not work in all scenarios where kbutton is used. Tested with other kbutton icons and changing height to auto does not introduce any regressions
Also fixes margin of KCard
*changed height of kbutton icons to be auto
*fixes margin bottom of kcard
=> fix(kbutton): change height of kbutton icons to be auto - intf-2282

packages/KButton/package.json, packages/KCard/package.json, packages/KEmptyState/package.json, packages/KModal/package.json, packages/KSlideout/package.json
re-publish kongponents that were previously manually published
*changed package json to force CI to re-publish build
=> chore(publish): re-publish kongponent builds

docs/components/card.md, packages/KCard/KCard.spec.js, packages/KCard/KCard.vue, packages/KCard/__snapshots__/KCard.spec.js.snap
adds permanent shadow property to card even when not hovering.
=> feat(kcard): add permanent shadow property

packages/KEmptyState/package.json, packages/KSkeleton/package.json
`YARN_TOKEN` did not have publish privileges. Making trivial changes to bump versions.
=> chore(version) bump

docs/components/popover.md, packages/KPop/KPop.vue
This adds a prop which removes the caret (arrow) from the popover. Helpful for use when you need a flyout menu but you don't want the little triangle 
* Prop added
* Dynamic `.hide-caret` class added
* `.hide-caret:after` & `.hide-caret:before` set to display none
=> feat(KPop) Adds prop to hide caret

docs/components/popover.md, packages/KPop/KPop.vue
This PR adds all popper.js supported positions (-start, -end) to supported positions. It also updates the class prop to not remove `.k-popover` when passed. This also adds css padding theming. Additionally I added a [setting](https://github.com/Kong/kongponents/compare/feat/kpop-add-more-positions?expand=1#diff-198bd74514b5965edfd8dd6f5317205fR256) to ensure the pop over does not flow outside of the viewport ever.
* Updated placement prop
* Updated class logic
* Adds `KPopPaddingX` & `KPopPaddingY`
=> feat(KPop) Adds positions & theme

docs/components/table.md, packages/KTable/KTable.spec.js, packages/KTable/KTable.vue, packages/KTable/__snapshots__/KTable.spec.js.snap
Adds KTable events to rows and cells e.g.
```vue
<KTable @row:click="rowHandler" @cell:mouseover="cellHandler" ... />
```
See docs for more usage.
* feat(ktable): add dynamic row and cell events
* fix(ktable/sort): use header `.sortable` to detect if we should $emit
* test(ktable): split tests into describe sections
=> feat(ktable): add row and cell events

docs/components/table.md, packages/KTable/KTable.spec.js, packages/KTable/KTable.vue
Added additional functionality to KTable's defaultSorter to handle null, undefined and array values
*Add type checking for ktable to properly sort null, defined and array values
*added associated unit tests
*Updated docs to have array example
=> fix(ktable): beef up defaultSorter to handle null, undefined and array values

vue.config.js
* the relative path for the .gif was not working, but we might as well
allow for the gif to be inlined into the javascript. Bumping inline gif
sizes to 14kb.
Moral of the testing story is that when running `yarn link` you should also verify that the bundles are working. Shortcut to only build certain packages: `yarn build:cli --scope="@kongponents/kskeleton"`
=> fix(kskeleton): inline bigger gifs

docs/.vuepress/enhanceApp.js, docs/components/skeleton.md, packages/KSkeleton/CardSkeleton.vue, packages/KSkeleton/FormSkeleton.vue, packages/KSkeleton/KSkeleton.spec.js, packages/KSkeleton/KSkeleton.vue, packages/KSkeleton/KSkeletonBox.vue, packages/KSkeleton/Skeleton.vue, packages/KSkeleton/TableSkeleton.vue, packages/KSkeleton/__snapshots__/KSkeleton.spec.js.snap, packages/KSkeleton/index.js, packages/KSkeleton/package.json
Introduce a new skeleton component `<KSkeletonBox />` which allows users to compose skeletons to form their own placeholder content. This was born from needing to create a custom placeholder that looks more like the content it is place-holding. For example, Kong Manager there are multiple cards with different layouts, so instead of making the cards look generic everywhere, allow them to be composable and specialized to the content. e.g. plugin select cards, workspace dashboard cards. Check new docs in this PR for more information on usage.
* export kskeleton as a plugin, auto-importing components
* use KSkeletonBox in all the skeleton variants
* slot content in skeleton card
* allow KSkeletonBox to be used as a primitive outside of KSkeleton
=> feat(skeleton): add box primitive

docs/.vuepress/components/swatch.vue, docs/.vuepress/components/text-block.vue, docs/components/button.md, docs/style-guide/forms.md, docs/style-guide/utilities.md, packages/KButton/KButton.vue, packages/styles/_typography.scss, packages/styles/forms/_inputs.scss
- Updates type sizing classes (`.xl`-> `.type-xl`)
- Adds color classes to utils (`.color-blue-base`)
- Adds missing styles for `<select />`
- Fixes svg sizing/spacing in KButton as well as the slot checks
=> styles(*) Fix broken & missing styles

docs/.vuepress/config.js, docs/.vuepress/enhanceApp.js, docs/components/inline-edit.md, packages/KInlineEdit/KInlineEdit.spec.js, packages/KInlineEdit/KInlineEdit.vue, packages/KInlineEdit/README.md, packages/KInlineEdit/__snapshots__/KInlineEdit.spec.js.snap, packages/KInlineEdit/package.json
Adds inline edit. Currently only supports text input editing per feature request. More input types to come.
=> feat(KInlineEdit): Adds KInlineEdit component

packages/KTable/KTable.vue
Updated row listeners to support clicking all non Anchor / Button elements rather than just TD elements.
*Updated row listeners to support clicking all non Anchor / Button elements rather than just TD elements.
=> fix(ktable): update row listeners to support clicking non td elements

docs/components/button.md, packages/KButton/KButton.vue, packages/KMultiselect/KMultiselect.vue, packages/KMultiselect/__snapshots__/KMultiselect.spec.js.snap
More and more designs are including a button with a dropdown caret similar. Instead of adding one off instances I added a utility class to KButton. I also updated KMultiselect to use the caret 💄
* Add KButton classes
* Use class in KMultiselect
* Add example of class to button docs
=> Style(KButton) Adds isOpen prop for dropdown caret 

docs/components/input.md, packages/KInput/KInput.spec.js, packages/KInput/KInput.vue, packages/KInput/__snapshots__/KInput.spec.js.snap
Add v-model support to `KInput`
Fixes #186
=> feat(kinput): add v-model

packages/KToaster/KToaster.vue, packages/KToaster/__snapshots__/KToaster.spec.js.snap
Updates toaster design to more closely match new Kongponent styles. Moves toasters to bottom right to no longer overlap action buttons as well as moves to only theming the left border instead of the entire alert.
Latest designs: 
- https://share.goabstract.com/2084d396-6741-4406-8283-3a20e378e0c1?mode=design&sha=fd108e0f965f983894ceebc3a485f7a17a8f091f
- https://share.goabstract.com/23a7b7d7-3dec-4a3b-bb99-cfa70f4d4c18?mode=design&sha=9ce13587f0d55a0ccf757a887893f34df8aad96d 
* Updates KToaster styles
=> feat(KToaster): change to white style, move to bottom

packages/KTable/KTable.vue
Reverting https://github.com/Kong/kongponents/pull/239
* Reverting the row click handler back so that divs within anchors and buttons can have the intended click functionality again
=> fix(ktable): revert row click handler to target td again - intf-2543

docs/components/modal.md, packages/KModal/KModal.spec.js, packages/KModal/KModal.vue, packages/KModal/__snapshots__/KModal.spec.js.snap
Added a few more theming options to the modal as well as added title and content props used as default slot content. Previously you had to slot even just to set a custom title.
* Props added
* Theme options added
* Prop test added
* Snapshot updated
=> feat(KModal) Adds title & content props, Adds more theme options

docs/components/inline-edit.md, packages/KInlineEdit/KInlineEdit.spec.js, packages/KInlineEdit/KInlineEdit.vue
Blocks https://konghq.atlassian.net/browse/KHCP-331
- Adds prop for ignoring initial value when clicking to edit
- Adds prop for adding custom styles to the input which will override those inherited from the element when clicking to edit.
In Konnect we implemented this component to display slightly differently when there was no value. This became a problem when you would click to edit for the first time, the styling from the initial element would transfer in. We also want to display text when empty but NOT pass that text in on click (similar to input placeholder).   
* Adds props
* Adds tests
* Updates snapshots
* Adds doc
=> feat(KInlineedit) Adds props for overriding styles & ignore value

packages/KToaster/KToaster.vue, packages/styles/_variables.scss
- Adds new value for yellow-200 and pushes existing colors up by 1 (old 200 -> new 300)
- Updates yellow value for warning toaster
=> Style(Colors) Adds new yellow-200

docs/components/popover.md, packages/KPop/KPop.spec.js, packages/KPop/KPop.vue
Adding a callback function prop that triggers when the popover has already been opened
*Adding a callback function prop that triggers when the popover has already been opened
*Rename isShow to isOpen
=> feat(kpop): kpop adds an optional callback function when popover is already opened

packages/KSegmentedControl/KSegmentedControl.vue, packages/KSegmentedControl/package.json
Before:
After:
* mute colors to suit konnect design
* fix hover active and focus borders and box shadows
NOTE: in previous version hover focus and active states were all handled gracefully by kbutton, in this design they have to be overriden
=> fix(segmentedcontrol) color and selectors

docs/components/badge.md, packages/KBadge/KBadge.vue, packages/KBadge/__snapshots__/KBadge.spec.js.snap
Add width "auto" + sane min/max widths by default. Add css vars support for overriding, and truncate with ellipsis.
Demo
=> style(kbadge) auto width by default, add vars, truncate

packages/KButton/KButton.vue
Adds a null check for mounting non kicon svg icons
*Adds a null check for mounting non kicon svg icons
=> fix(kbutton): add null check for kicon mounting

docs/components/skeleton.md, packages/KSkeleton/KSkeleton.vue, packages/KSkeleton/KSkeletonBox.vue, packages/KSkeleton/__snapshots__/KSkeleton.spec.js.snap
The delay-milliseconds implementation currently handles the skeleton flashing by conditionally rendering after a timeout.
I propose to change this in favour of rendering transparently until after the timeout.
This way I do not need to approximate the pixel height of the skeleton and presented data to avoid components that flow vertically below from jumping up and down.
* added a css class
* moved isVisible condition to css class
* added example in docs to demonstrate the problem
* added a fade in
=> feat(kskeleton) override transparency

packages/KSkeleton/package.json
KSkeleton had an old deprecated version 1.1.0 I believe. So bumping up the package version so that it will publish and not have any more collisions.
https://github.com/Kong/kongponents/runs/1573435067
```
lerna info execute Skipping releases
lerna ERR! Error: Command failed: git tag @kongponents/kskeleton@1.1.0 -m @kongponents/kskeleton@1.1.0
lerna ERR! fatal: tag '@kongponents/kskeleton@1.1.0' already exists
lerna ERR! 
lerna ERR!     at makeError (/home/runner/work/kongponents/kongponents/node_modules/execa/index.js:174:9)
lerna ERR!     at Promise.all.then.arr (/home/runner/work/kongponents/kongponents/node_modules/execa/index.js:278:16)
lerna ERR! Error: Command failed: git tag @kongponents/kskeleton@1.1.0 -m @kongponents/kskeleton@1.1.0
lerna ERR! fatal: tag …
```
=> chore(kskeleton): force publish

docs/components/popover.md, docs/components/tooltip.md, docs/style-guide/colors.md, packages/KoolTip/KoolTip.spec.js, packages/KoolTip/KoolTip.vue, packages/KoolTip/__snapshots__/KoolTip.spec.js.snap, packages/KoolTip/package.json, packages/styles/_variables.scss
Adds new design for tooltips and composes `KPop` to take advantage of positioning and appending to the DOM functionality `KPop` has. We also didn't have opaque black colors, so I add those to our styles. I aligned our props so that it makes a bit more sense re: `message` -> `label`, and `position` -> `placement`. The "alignment" prop was used to align text, but we weren't ever using it. Users can now slot the content if they want to text align.
- feat(style) add solid black colors
- feat(kooltip)!: kooltip implemented with kpop
* fixes issues with placement
* uses new styling and adds kpop as a dependency
* adds ability to have slotted html content
BREAKING CHANGE: props and styles completely updated
- docs(kpop) typos
Fixes #262
=> feat(kooltip)!: refactor to kpop and restyle

docs/components/skeleton.md, packages/KSkeleton/KSkeleton.vue
Fixes regression caused by making skeletons invisible rather than unrendered
* added some css
* added an example in vuepress docs
=> fix(kskeleton): button spinner

packages/KEmptyState/KEmptyState.spec.js, packages/KEmptyState/KEmptyState.vue
* warning2 -> warning
A side effect is that this closes #286
=> fix(kempty): use correct warning icon

docs/components/badge.md, packages/KBadge/KBadge.spec.js, packages/KBadge/KBadge.vue, packages/KBadge/__snapshots__/KBadge.spec.js.snap
This will help with snowflake badges in Konnect.
- Updates colors to latest style guide. 
- Add `default` appearance type. 
- Add larger default border radius.
BREAKING CHANGE: default is no longer custom
=> feat(badge)!: update styles, remove min width, add default

docs/components/card.md, packages/KCard/KCard.vue
- trying to get card header spacing to be equal whether there are actions or not, so we can put cards side by side without janky padding
* add demo in docs
* slapped min-height on card header
=> fix(KCard) card header spacing

docs/components/input-checkbox.md, docs/components/input-radio.md, packages/styles/forms/_checkbox-radio.scss
This adds consistent margin between input and label for checkboxes and radios
* Add `margin-right: 4px` to KRadio input
* Add `margin-right: 8px` to KCheckbox input
=> style(KCheckbox,KRadio): add margin-right to input

packages/KCheckbox/KCheckbox.vue, packages/KCheckbox/__snapshots__/KCheckbox.spec.js.snap
Wrap the text of a KCheckbox label in a span tag to remove unwanted whitespace
* Wrap the text of KCheckbox label in a span tag
=> fix(KCheckbox) wrap label text in span

docs/components/icon.md, packages/KIcon/KIcon.vue, packages/KToaster/__snapshots__/KToaster.spec.js.snap
We have a requirement for an icon with a linear-gradient color. This PR adds a new slot `svgElements` to not only allow adding a `<linearGradient />` svg element to a KIcon, but other customizations as well.
* Add `svgElements` slot to allow for customizing the svg of a KIcon
* Add documentation for new `svgElements` slot in KIcon kongponent
=> feat(KIcon): add svgElements slot

docs/components/table.md, packages/KTable/KTable.vue
Add `cellAttrs` prop for greater table customization
This allows customization at a much more granular level. Cells, columns and rows can be customized via this new prop.
Here's an example I've added to the docs. This table has been customized in the following ways:
1. Two columns of cells,`Name` and `Description`, have been given different `max-width` values.
2. Two columns of cells, `Name` and `Description`, have been given the `truncate` class.
3. The cells in the last row have been given different background colors based on data in the row (in this case, based on Google being the value in the `Company` column)
* Add `cellAttrs` prop to KTable component
* Update docs to include details about new `cellAttrs` prop
=> feat(KTable): add cellAttrs prop for customization

docs/components/switch.md, packages/KInputSwitch/KInputSwitch.vue
Add the ability to display a tooltip on hover if `KSwitch` is `disabled`.
* Add new property `disabledTooltipText`
* Added separate section in docs for `disabled` property
=> feat(KSwitch) add optional tooltip when disabled

docs/.vuepress/config.js, docs/components/label.md, packages/KIcon/KIcon.vue, packages/KLabel/KLabel.spec.js, packages/KLabel/KLabel.vue, packages/KLabel/__snapshots__/KLabel.spec.js.snap, packages/styles/forms/_labels.scss
Some inputs require additional context to explain what the user should provide. This feature uses `KIcon` to add a help icon and `KoolTip` to show a tooltip if the `help` property is provided.
`KoolTip` uses the prop `label` to provide the text. I have chosen `help` in this component so that there is no confusion between the `KLabel` slot and the `KoolTip` prop.
[Demo](https://deploy-preview-306--kongponents.netlify.app/components/label.html#with-help)
* Add `help` property to `KLabel`
* Add tests for `KLabel`
=> feat(klabel): add help property with icon + tooltip

.github/workflows/publish.yml, .github/workflows/test.yml
Fixes #297
bump the version of Node used to test and publish to drop unsupported versions and add LTS.
* change node matrix
=> ci: drop Node 8 & 10 support, add Node 14

docs/components/switch.md, packages/KInputSwitch/KInputSwitch.vue, packages/KInputSwitch/__snapshots__/KInputSwitch.spec.js.snap
Adds a prop to add a check icon to the switch when enabled
* Added a check icon to KInputSwitch component that can be enabled via a prop
* Updated `switch` docs to include a usage example for the new `enabledIcon` prop
* Doc linting and component snapshot update
=> feat(KInputSwitch): add enabled icon

docs/components/modal.md, packages/KModal/KModal.spec.js, packages/KModal/KModal.vue, packages/KModal/__snapshots__/KModal.spec.js.snap
Allow users to specify help text to display under the modal title.
* Add new slot `help` and property `helpText`
=> feat(KModal): add support for help text

docs/components/card.md, packages/KCard/KCard.spec.js, packages/KCard/KCard.vue, packages/KCard/__snapshots__/KCard.spec.js.snap
Adds a `help-text` prop to the KCard component
* Add a `help-text` prop to the KCard component
* Add some examples to the KCard docs
* Small KCard doc linting changes
* Update KCard snapshot
=> feat(KCard): add help text prop

docs/components/card.md, packages/KCard/KCard.vue, packages/KCard/__snapshots__/KCard.spec.js.snap
This adds `16px` bottom margin to the KCard help text element. This way, users of the prop won't always have to add top margin to KCard body content.
* Adds bottom margin to KCard help text element
(no screenshot because it looks the same)
=> fix(KCard): add bottom margin to help text element

docs/components/card.md, packages/KCard/KCard.vue, packages/KCard/__snapshots__/KCard.spec.js.snap
Adjusts KCard helpText margins. Fixes an issue where unwanted margin was added when helpText was used via component slot rather than a prop. Adds `24px` bottom margin to the helpText element.
* Fixes an issue where unwanted margin was added when helpText was used via component slot rather than a prop
* Adds `24px` bottom margin to the helpText element
* Adds an example of using helpText via slot
* Updates test snapshot
**Before:**
**After:**
=> fix(KCard): adjust helpText margins

docs/.vuepress/styles/prism-theme.min.css, packages/KTable/KTable.vue
Fix CSS color variable name so that side border will display on rows.
*
=> fix(KTable) fix side border display

docs/components/input.md, packages/KInput/KInput.spec.js, packages/KInput/KInput.vue, packages/KInput/__snapshots__/KInput.spec.js.snap, packages/styles/forms/_general.scss, packages/styles/forms/_inputs.scss
* Parameterize `help` text and add a built in `label` prop
* Maintain support for `.help` utility class and combining with `KLabel`
* Maintain attribute binding
* Update snapshots
Help section:
Labeling options:
=> feat(kinput): fun with labels

docs/components/alert.md, packages/KAlert/KAlert.spec.js, packages/KAlert/KAlert.vue
Adds more border options for KAlert component via three new props:
1. `has-border-right`
2. `has-border-top`
3. `has-border-bottom`
These additions are in preparation for upcoming work on the KToaster component.
* Adds three new props, `has-border-right`, `has-border-top`, `has-border-bottom`
* Adds documentation examples for the new border props
=> feat(KAlert): add more border options

packages/KRadio/package.json
closes #319
Seems to be a copy-paste error when creating this component. Its main references kbutton instead of kradio
* update main in KRadio package.json
=> fix: copy paste error for kradio

docs/components/label.md, packages/KLabel/KLabel.spec.js, packages/KLabel/KLabel.vue, packages/KLabel/__snapshots__/KLabel.spec.js.snap
Klabel was expected to implement the html label's `for` attribute and was used in many places that way, but was not previously implemented. This PR implements this behavior.
* Adds `for` prop that is passed as a label attribute
* Adds documentation example with the new prop
* Adds snapshot test
=> feat(klabel): add for attribute for label

docs/components/input-checkbox.md, docs/components/input-radio.md, packages/KCheckbox/KCheckbox.vue, packages/KCheckbox/__snapshots__/KCheckbox.spec.js.snap, packages/KRadio/KRadio.vue, packages/KRadio/__snapshots__/KRadio.spec.js.snap
Radio and Checkbox button has different spacing between button and label depending on how the label is specified. When the label is passed through the prop, the spacing is smaller:  
```
<KRadio label="Option 1" />
<KCheckbox :label="checkbox1 ? 'on' : 'off'" />
```
When the label is passed through a slot, the spacing is bigger:
```
<KRadio>Option 1</KRadio>
<KCheckbox v-model="checkbox1">Label goes here.</KCheckbox>
```
* Added `d-inline-block` class for label
* Added `float-left` class for input and span
* Added `label-text` class for checkbox span
=> style(kcheckbox,kradio): fix label space

.eslintignore
the dist folder contains the compiled outputs. Linting it is causing the publish step to fail.
* add `dist` to eslint ignore rules
=> ci: don't lint the dist outputs

docs/components/alert.md, docs/components/button.md, docs/components/card.md, docs/components/empty-state.md, docs/components/icon.md, docs/components/inline-edit.md, docs/components/input-checkbox.md, docs/components/input-radio.md, docs/components/modal.md, docs/components/popover.md, docs/components/renderless/kclipboard.md, docs/components/renderless/komponent.md, docs/components/renderless/ktoggle.md, docs/components/skeleton.md, docs/components/switch.md, docs/components/table.md, docs/components/tooltip.md, docs/guide/theming.md, packages/KSkeleton/KSkeleton.vue, packages/KTable/README.md, packages/KToggle/KToggle.js, packages/KToggle/README.md, packages/KoolTip/KoolTip.vue
> In 2.6.0, we introduced a new unified syntax (the v-slot directive) for named and scoped slots. It replaces the slot and slot-scope attributes, which are now deprecated, but have not been removed and are still documented here. The rationale for introducing the new syntax is described in this RFC.
https://vuejs.org/v2/guide/components-slots.html
Kongponents is using the old scope syntax.
This will make Kongponents compatible with Vue 2.6+ and Vue 3 for slots.
* `slot="name"` syntax were switched to `<template v-slot:name>`
* structural and non-functional `div`s and `spans` has been simplified
=> Update deprecated slots to new v-slot syntax

docs/components/input-checkbox.md, docs/components/input-radio.md, packages/KCheckbox/KCheckbox.vue, packages/KCheckbox/__snapshots__/KCheckbox.spec.js.snap, packages/KRadio/KRadio.vue, packages/KRadio/__snapshots__/KRadio.spec.js.snap
Konnect Registration page has Checkbox input/span alignment issue.
*
=> style(kcheckbox): fix label alignment

package.json
The publishing step on the release branch failed as it didn't bump the prerelease version. Switch to conventional prerelease.
* update lerna publish config
=> ci: add conventional prerelease

docs/components/modal.md, packages/KButton/KButton.vue, packages/KButton/__snapshots__/KButton.spec.js.snap, packages/KModal/KModal.spec.js, packages/KModal/KModal.vue, packages/KModal/__snapshots__/KModal.spec.js.snap
Update KModal with new design.
For khcp-1897.
* Default `KButton` `appearance` property to `outline`
* Remove default values for modal `title` and `content`
* Make `title` required for accessibility
* Add `hideTitle` prop if they don't want the title displayed
* Remove `helpText` prop and `help` slot
* Swap order of action and cancel buttons (cancel comes first)
* Add `action-buttons` slot
* Update style classes to prefix with `k-` (class without `k-` left in for backwards compatibility)
* Update snaps
Figma: https://www.figma.com/file/sfSZhMfpzCzddEhd8tdk9s/Kong_Design-library?node-id=209%3A1086
=> feat(kmodal): style redesign [khcp-1897]

docs/components/empty-state.md, packages/KEmptyState/KEmptyState.spec.js, packages/KEmptyState/KEmptyState.vue, packages/KEmptyState/__snapshots__/KEmptyState.spec.js.snap
Update `KEmptyState` design.
* Add `icon` prop for customizing the displayed icon
* Add theming support for `--KEmptyTitleColor`, `--KEmptyContentColor`, `--KEmptyBackground`
* Update tests
Figma: https://www.figma.com/file/sfSZhMfpzCzddEhd8tdk9s/Kong_Design-library?node-id=257%3A1640
=> feat(kemptystate): redesign [khcp-1990]

docs/components/select.md, packages/KButton/KButton.vue, packages/KSelect/KSelect.spec.js, packages/KSelect/KSelect.vue, packages/KSelect/__snapshots__/KSelect.spec.js.snap, packages/KSelect/package.json
* Add `button` style `appearance` for pagination page size dropdown style
* Add `buttonText` prop that allows customizing the text if the appearance is `button`
* Emit `selected` event when an item is selected
* Update docs
=> feat(kselect): add `button` appearance

docs/components/alert.md, packages/KAlert/KAlert.spec.js, packages/KAlert/KAlert.vue, packages/KAlert/__snapshots__/KAlert.spec.js.snap, packages/KAlert/package.json, packages/KToaster/KToaster.vue, packages/KToaster/__snapshots__/KToaster.spec.js.snap
KAlert was redesigned to allow for different dismiss types(none/icon/button), alert type(banner/alert), different size(small/large). 
* Add new props: type, dismissType, size(large)
* Add new icon/buttons
* Style icons/buttons based on appearance
* Update test snapshots
=> feat(kalert): redesign [khcp-2008]

docs/components/input.md, packages/KInput/KInput.vue, packages/KInput/__snapshots__/KInput.spec.js.snap, packages/KSelect/__snapshots__/KSelect.spec.js.snap
Fix for UX-555.
UX-601 - add 2 new props `hasError`, `errorMessage` and error styling for error state in KInput.
=> style(kinput): add error state

docs/components/pagination.md, packages/KPagination/KPagination.spec.js, packages/KPagination/KPagination.vue, packages/KPagination/__snapshots__/KPagination.spec.js.snap, packages/KSelect/KSelect.vue, packages/KSelect/__snapshots__/KSelect.spec.js.snap
Fixes for KTable.
* Have the page size dropdown open upward
* Add `currentPage` prop
* Make full page selection button clickable, not just the number
* Update docs and snaps
=> feat(kpagination): fixes for ktable

packages/styles/forms/_checkbox-radio.scss
Increase radio button stroke from 1px to 2px
* Increase radio button stroke from 1px to 2px
=> Increase radio button stroke change

docs/components/card-catalog.md, package.json, packages/KCardCatalog/KCardCatalog.spec.js, packages/KCardCatalog/KCardCatalog.vue, packages/KCardCatalog/__snapshots__/KCardCatalog.spec.js.snap, packages/KPagination/KPagination.vue, utils/utils.js, yarn.lock
Adds the ability to pass a fetcher function into a new fetcher prop which will enable backend pagination for the card catalog.
* Many new props added related to fetcher/pagination see the docs
* Dependencies added:` composition-api` and `swrv`
=> feat(kcardcatalog): adds fetcher and integrates backend pagination

packages/KInput/KInput.vue, packages/KInput/__snapshots__/KInput.spec.js.snap
Apply attributes to the child input element rather than the wrapper to avoid duplicate elements with the same id.
* Add `inheritAttrs` property to component definition to disable attribute inheritance on the wrapper element.
* Alter `v-bind` to use `$attrs` instead of `attrs` (to spec).
=> fix(kinput): apply attributes to input [KHCP-2108]

docs/components/input.md, docs/components/textarea.md, packages/KCheckbox/KCheckbox.vue, packages/KInput/KInput.vue, packages/KInput/__snapshots__/KInput.spec.js.snap, packages/KInputSwitch/KInputSwitch.vue, packages/KLabel/KLabel.vue, packages/KLabel/__snapshots__/KLabel.spec.js.snap, packages/KRadio/KRadio.vue, packages/KSelect/KSelect.vue, packages/KSelect/__snapshots__/KSelect.spec.js.snap, packages/KTextArea/KTextArea.vue, packages/KTextArea/__snapshots__/KTextArea.spec.js.snap, packages/Krumbs/Krumbs.vue
Apply attributes (`$attrs` or computed variable in component, `attrs`) to child elements within applicable components.
* Add `inheritAttrs: false` to component definitions, where applicable.
=> fix(attrs): apply attributes to child elements [KHCP-2173]

docs/components/card-catalog.md, docs/components/pagination.md, docs/components/table.md, packages/KCardCatalog/KCardCatalog.spec.js, packages/KCardCatalog/KCardCatalog.vue, packages/KPagination/KPagination.vue, packages/KTable/KTable.vue
Update KPagination to allow only prev/next page nav support.
* Add new prop `disablePageJump`
=> feat(pagination): support in table and catalog

docs/components/textarea.md, packages/KTextArea/KTextArea.vue
* Update `char-limit-exceeded` event to only fire if switching between exceeding and not exceeding
* Return more data on the event
=> fix(ktextarea): limit exceeded event

docs/.vuepress/styles/index.styl
Add CSS rule to force nowrap whitespace on inline code placed inside of table cells.
=> chore(docs): nowrap whitespace on code inside table

packages/KInput/KInput.vue, packages/KTextArea/KTextArea.vue
`box-shadow` CSS attribute does not display properly in iOS, meaning `KInput`, `KTextArea`, and `KSelect` components appear with no borders on iOS browsers.
* Add `-webkit-appearance: none` to `KInput` and `KTextArea` native input components (`input` and `textarea`).
=> fix(css): box-shadow does not render on ios

package.json
Update lerna ignore flags for build:cli.
* `--ignore @kongponents/styles --ignore @kongponents/utils`
=> fix(build): update lerna ignore flag

docs/components/card-catalog.md, docs/components/table.md, package.json, packages/KCardCatalog/package.json, packages/KTable/package.json, packages/utils/package.json, tailwind-custom-properties.config.js
When utilizing the `@vue/composition-api` inside of a Kongponent package, the `@vue/composition-api` needs to be added as a `peerDependency` to the component package rather than a `dependency`.
> Currently, installing with yarn with the peer flag `yarn add {package-name} --peer` [is broken](https://github.com/yarnpkg/yarn/issues/5287)
You will need to manually add the `peerDependencies` entry inside the individual component's `package.json`. For example, inside `./packages/KTable/package.json` this is what was added
``` json
{
"peerDependencies": {
"@vue/composition-api": "^1.2.4"
}
}
```
The **_parent application_** must then manually add `@vue/composition-api` to it's `package.json` as a dependency if utilizing any of the components depending on the package (this is now outlined in the …
=> fix(*): fix deps and build process

packages/KTable/KTable.vue
* Add missing `border-collapse` style to KTable
=> fix(ktable): add missing style

docs/components/card-catalog.md, docs/components/table.md, packages/KCardCatalog/KCardCatalog.vue, packages/KTable/KTable.vue
Emit events when empty/error state CTA buttons are clicked to allow hooking up a callback.
* Emit events in both `KTable` and `KCardCatalog`
=> feat(ktable/kcardcatalog): emit cta click events

docs/components/card-catalog.md, docs/components/table.md, packages/KCardCatalog/KCardCatalog.spec.js, packages/KCardCatalog/KCardCatalog.vue, packages/KCardCatalog/__snapshots__/KCardCatalog.spec.js.snap, packages/KTable/KTable.spec.js, packages/KTable/KTable.vue, packages/KTable/__snapshots__/KTable.spec.js.snap
Make empty/error state slottable in KTable/KCardCatalog
* Add `empty-state` / `error-state` slots
* Emit `sort` event when sortable headers are clicked
=> feat(ktable/kcardcatalog): make states slottable

packages/KTable/KTable.vue, packages/utils/utils.js
Fix sorting in KTable.
* Default sort to ascending on first click
* Arrow should point upward for ascending and downward for descending
=> feat(ktable): default sort to asc

docs/components/card-catalog.md, docs/components/table.md, packages/KCardCatalog/KCardCatalog.vue, packages/KTable/KTable.vue
Add `fetcherCacheKey` prop to allow manual revalidate of fetcher.
*
=> feat(ktable): add cacheKey prop

packages/KCardCatalog/KCardCatalog.vue, packages/KTable/KTable.spec.js, packages/KTable/KTable.vue
Don't call the fetcher until initialization has completed
*
=> fix(ktable/kcardcatalog): fetch after init

.github/workflows/publish.yml
We want to lock down who can push to master, but this breaks the publish step and the publish actions pushes to master.
Lerna uses `GH_TOKEN` in it's github-client to authenticate to GitHub https://github.com/lerna/lerna/blob/6cb8ab2d4af7ce25c812e8fb05cd04650105705f/utils/github-client/lib/github-client.js#L25
`GITHUB_TOKEN` is an environment variable that can be used by actions to authenticate to github https://docs.github.com/en/actions/security-guides/automatic-token-authentication
* Pass the `GITHUB_TOKEN` to lerna via `GH_TOKEN`
=> ci: use gh token to authenticate to github

.github/workflows/publish.yml
The default is for `persist-credentials` is true, which configs the ssh key that git uses. We want to use the token for `GITHUB_TOKEN`.
* don't persist credentials after checkout
=> ci: don't persist credentials after checkout

.github/workflows/publish.yml
Fix for #446. `with` added to the wrong job
* Add perisist-credentials false to all jobs in the publish phase
=> ci: use with in correct job

.github/workflows/publish.yml
These approaches don't work. For future travellers, I believe what we need is a personal access token from something like a service account that has admin privileges as long as the repo allows pushing from admins
https://github.com/lerna/lerna/issues/1957 
* revert 
* #447 
* #446 
* #444
=> chore: revert publish to protected branch changes

packages/KModal/KModal.vue, packages/KModal/__snapshots__/KModal.spec.js.snap
Addresses a few a11y issues in the `KModal`
* fixed blank `aria-modal`
* added `aria-level` to `role="heading"`
=> chore(kmodal): add aria-modal and aria-level to kmodal

.github/workflows/publish.yml
I created a bot, that is totally not self aware, named @kongponents-bot. It has special privileges ~to conquer the planet~ push to the master branch. This allows us to lock down master while still being able to publish.
* use the kongponents-bot personal access token secret in publish step
=> ci: use kongponents-bot to publish packages

packages/styles/styles.scss
Add a global CSS comment to the top of the outputted styles.css file to allow consuming applications to recognize the style block as needed (e.g. @kong/kong-auth-elements).
* Adds `/*! KONGPONENTS_STYLES */` comment block to the outputted `styles.css` file.
=> feat(comment): add global comment in output file

packages/KAlert/KAlert.vue, packages/KAlert/__snapshots__/KAlert.spec.js.snap, packages/KToaster/KToaster.spec.js, packages/KToaster/__snapshots__/KToaster.spec.js.snap
Fix invalid HTML structure within `KAlert`. Slot elements should not be wrapped with `<span>` tags as the content for a `KAlert` slot is typically HTML, meaning a `<div>` or `<p>` tag inside the slot renders invalid HTML, which is also adversely impacting styles.
* Change `slot` wrapping elements to `<div>`
* Add CSS rule to remove margin of last `<p>` tag inside `.k-alert-msg`
* Updated test snapshots to match tag structure.
=> fix(kalert): fix invalid html structure

docs/components/textarea.md, packages/KTextArea/KTextArea.spec.js, packages/KTextArea/KTextArea.vue
Fixes v-model binding.
* Fixed the emitted event to be  `input`, which is required for proper v-model binding
* Updated the docs to reference the `input` event rather than the `textarea` event
* Updated the tests to test the `input` event rather than the `textarea` event
=> fix(ktextarea): fix v-model

packages/KPagination/KPagination.spec.js, packages/KPagination/KPagination.vue
The `currentPage` prop should update both the active page button and the text detailing which items are currently displayed.
* Added a watcher for the `currentPage` prop
* Added a test to cover this case
=> fix(kpagination): fix currentPage prop

docs/components/input.md, docs/components/textarea.md, docs/guide/theming.md, packages/KTextArea/KTextArea.vue, packages/styles/forms/_inputs.scss
This change allows overriding the default placeholder text color used in `KInput` and other inputs using `k-input` or `form-control` classes. It helps customizing the user experience and introduces more theming options without the need to write specific CSS selectors for placeholders.
* Modify the color of KInput placeholder to use the newly introduced `--KInputPlaceholderColor` CSS variable and fallback to its default color if not defined
* Add `--KInputPlaceholderColor` to the table of available Input variables in theming guide docs
=> feat(kinput): add css variable for optional kinput placeholder text color overrides

docs/README.md
Update Getting Started docs with up-to-date install and usage instructions.
* Add instructions for `transpileDependencies` and PostCSS preserve properties.
* Updated jsfiddle (tied to Darren's account) to a new CodePen that also properly imports `@kongponents/styles`
=> chore(docs): update docs with configs

package.json, packages/styles/_typography.scss, packages/styles/forms/_switch.scss, packages/styles/styles.scss, yarn.lock
Use dart-sass instead of node-sass (depreciated).
* Removed `node-sass` dependency (depreciated); added `sass`
* Updated variable functions to properly interpolate strings (for `dart-sass`).
* Converted division to utilize `@use "sass:math"`
=> chore(sass): use dart-sass

packages/KInput/KInput.vue
Sets the KInput value prop type to `[String, Number]` to prevent warnings in the browser console when using inputs with `type="number"`.
* Small addition to KInput value prop type
=> fix(kinput): allow numbers to be passed in as value

packages/KTable/KTable.vue
* Adjust position of sort icons
* Currently sorted column heading color is blue
Before:
After:
=> fix(ktable): update sort styling

docs/components/breadcrumbs.md, packages/Krumbs/Krumbs.spec.js, packages/Krumbs/Krumbs.vue, packages/Krumbs/__snapshots__/Krumbs.spec.js.snap, packages/styles/_typography.scss
Add `icons` property to `items` object to allow for using a `KIcon` component with or without breadcrumb text.
Update breadcrumb (Krumbs) Kongponent styling and structure, including wrapping breadcrumb text in a `span.breadcrumb-text` element.
* Breadcrumb text is now wrapped in a `<span class="breadcrumb-text" />` tag.
* Add `icon` property to `items` object.
* Style tweaks.
* Updated docs for changes.
=> feat(krumbs): update breadcrumb kongponent with icon [KHCP-2655]

docs/components/multiselect.md, docs/components/popover.md, docs/components/select.md, docs/components/tooltip.md, packages/KMultiselect/KMultiselect.vue, packages/KPop/KPop.vue, packages/KSelect/KSelect.vue, packages/KoolTip/KoolTip.vue
Add `positionFixed` prop to allow prevention of popover content being clipped.
* Add `positionFixed` prop to `KPop`
* Add support for `positionFixed` to kongponents using `KPop`
=> feat(kpop): add positionFixed prop

package.json, packages/utils/package.json, yarn.lock
Bump the version of `swrv` up to `0.9.6` matching the version used in Konnect.
*
- Updates to the corresponding `.spec.ts` test file(s) to utilize [Cypress Component Testing](https://docs.cypress.io/guides/component-testing/introduction). 
**Does your PR modify a component [that already exists on the `next` …
=> chore(swrv): match version in konnect

docs/.vuepress/enhanceApp.js, packages/KCardCatalog/KCardCatalog.spec.js, packages/KCardCatalog/KCardCatalog.vue, packages/KTable/KTable.spec.js, packages/KTable/KTable.vue
Fix usage of composition API.
- Updates to the corresponding `.spec.ts` test file(s) to utilize [Cypress Component Testing](https://docs.cypress.io/guides/component-testing/introduction). 
**Does your PR modify a component [that already exists on the `next` branch](https://github.com/Kong/kongponents/tree/next/src/components)?**
- …
=> fix(composition-api): fix usage of composition api

docs/components/table.md, packages/KIcon/KIcon.vue, packages/KTable/KTable.vue
Adds a new `emptyStateActionButtonIcon` prop to `KTable` which accepts a `string` name of an icon to display next to the action button. (optional).
=> feat(ktable): add empty-state-action-button-icon

docs/components/tabs.md, packages/KTabs/KTabs.vue
Adds a bottom border to tab group
* Added bottom border to tab group
* Changed variable name for bottom border color for individual tabs (from `KTabsBottomBorder` to `KTabBottomBorderColor`).
**Before**
**After**
**Does your PR modify a component [that already exists on the `next` branch](https://github.com/Kong/kongponents/tree/next/src/components)?**
- [] **Yes**, and there is a corresponding PR to update the component on the `next` branch
- `LINK_TO_PR_ON_NEXT_BRANCH` (**required**)
=> fix(ktabs): add bottom border for tabs

docs/components/switch.md, packages/KInputSwitch/KInputSwitch.vue, packages/KInputSwitch/__snapshots__/KInputSwitch.spec.js.snap, packages/styles/forms/_switch.scss
Allow the label to be positioned on the left or right of the switch.
* Adds `label-position` prop, defaults to `right`
- Updates to the corresponding `.spec.ts` test file(s) to utilize …
=> feat(kinputswitch): add label-position prop

docs/.vuepress/config.js, docs/.vuepress/enhanceApp.js, docs/components/prompt.md, packages/KPrompt/KPrompt.spec.js, packages/KPrompt/KPrompt.vue, packages/KPrompt/README.md, packages/KPrompt/__snapshots__/KPrompt.spec.js.snap, packages/KPrompt/package.json, packages/KTableLegacy/package.json
Add new `KPrompt` dialog for modals that prompt a user to take an action.
Warning:
Danger:
* Add new kongponent
* Add tests
* Add docs
* Manually set version of `KTableLegacy` to match other kongponents versions
- Documentation updates for the component changes, as well as updating examples and usage to Vue 3 and …
=> feat(kprompt): add kprompt kongponent

docs/components/prompt.md, packages/KPrompt/KPrompt.spec.js, packages/KPrompt/KPrompt.vue, packages/KPrompt/__snapshots__/KPrompt.spec.js.snap
Add `actionPending` prop.
* Add tests
* Update snaps
- Updates to the corresponding `.spec.ts` test file(s) to utilize [Cypress Component …
=> feat(kprompt): add actionPending prop

packages/KButton/KButton.vue, packages/KInputSwitch/KInputSwitch.vue, packages/KPrompt/KPrompt.vue
Danger button hover color should be red-700.
- Updates to the corresponding `.spec.ts` test file(s) to utilize [Cypress Component Testing](https://docs.cypress.io/guides/component-testing/intr …
=> fix(kbutton): danger button hover color

docs/.vuepress/config.js, docs/.vuepress/enhanceApp.js, docs/components/modal-fullscreen.md, packages/KModal/KModal.vue, packages/KModalFullscreen/KModalFullscreen.spec.js, packages/KModalFullscreen/KModalFullscreen.vue, packages/KModalFullscreen/README.md, packages/KModalFullscreen/__snapshots__/KModalFullscreen.spec.js.snap, packages/KModalFullscreen/package.json
New Fullscreen Modal kongponent. [KHCP-2879](https://konghq.atlassian.net/browse/KHCP-2879)
New tests for the kongponent
- Updates to the corresponding `.spec.ts` test file(s) to utilize …
=> feat(kmodalfullscreen): adds new kongponent [khcp-2879]

docs/components/input.md, docs/components/prompt.md, docs/components/textarea.md, packages/KInput/KInput.spec.js, packages/KInput/KInput.vue, packages/KInput/package.json, packages/KTextArea/KTextArea.spec.js, packages/KTextArea/KTextArea.vue, packages/KTextArea/package.json
Add support for standard `KLabel` if `label` prop provided to `KInput` and `KTextArea`.
Address KHCP-2895.
* Add `overlayLabel` prop - default false
* Restructure location of `errorMessage`
* Restructure docs
* Update dependencies
* Update tests/snaps
- Documentation updates for the component changes, as well as …
=> feat(kinput): add standard label support

packages/KModal/KModal.vue
Fix the overlay to be the right color as per metalab designs.
Fix khcp-2929.
* Update overlay color
Before:
After:
- Updates to the corresponding `.spec.ts` test file(s) to utilize [Cypress …
=> feat(kmodal): fix overlay color [khcp-2929]

docs/components/modal-fullscreen.md, packages/KModalFullscreen/KModalFullscreen.vue, packages/KModalFullscreen/__snapshots__/KModalFullscreen.spec.js.snap, packages/KModalFullscreen/package.json
Misc fixes for kmodalfullscreen
* Change from `absolute` to `fixed` positioning
* Move the cancel button into the `action-buttons` slot - allow full control over form buttons
* Bump the version up to match rest of kongponents
* Update snaps
- Documentation updates for the component changes, as well as updating …
=> fix(kmodalfullscreen): misc fixes

docs/components/modal-fullscreen.md, packages/KModalFullscreen/KModalFullscreen.spec.js, packages/KModalFullscreen/KModalFullscreen.vue, packages/KModalFullscreen/__snapshots__/KModalFullscreen.spec.js.snap
Misc fixes for KModalFullscreen
* Separate `bodyHeaderDescription` into two props
* Add `header-icon`, `body-header`, and `body-header-description` slots
* Move classes outside of <slot> element
* Update docs
* Add missing tests
* Update snaps
- Documentation updates for the component changes, as well as updating …
=> fix(kmodalfullscreen): misc changes

packages/KButton/KButton.vue
Updates the color for KButton: `appearance=creation `
*
- Updates to the corresponding `.spec.ts` test file(s) to utilize [Cypress Component …
=> style(kbutton): update button color [khcp-2987]

docs/components/modal-fullscreen.md, packages/KModalFullscreen/KModalFullscreen.vue
Body header content should align with body.
Before:
After:
*
- Updates to the corresponding `.spec.ts` test file(s) to utilize [Cypress Component …
=> fix(kmodalfullscreen): fix body header alignment

docs/components/input.md, docs/components/textarea.md, packages/KInput/KInput.spec.js, packages/KInput/KInput.vue, packages/KTextArea/KTextArea.spec.js, packages/KTextArea/KTextArea.vue
Add `labelAttributes` prop.
* Add `labelAttributes` prop to `KInput` and `KTextArea`
* Update docs
* Add tests
- Updates to the corresponding `.spec.ts` test file(s) to utilize [Cypress …
=> feat(kinput): support label attrs

docs/components/select.md, packages/KSelect/KSelect.spec.js, packages/KSelect/KSelect.vue
Add support for `labelAttributes`
* Add new prop
* Update docs
* Update tests
=> feat(kselect): add support for labelattrs

docs/components/select.md, packages/KSelect/KSelect.vue, packages/KSelect/__snapshots__/KSelect.spec.js.snap
Fix `v-model` to work correctly on `KSelect`, should hook up to just the item's value you not the entire object.
* Fix v-model
* Update docs/tests
=> fix(kselect): set up v-model

packages/KTable/KTable.vue
There is a CSS rule in `KTable` that added `thead tr:after` that was not allowing table clicks on Safari. This PR adds `pointer-events: none` to the rule, allowing clicks to pass through.
Resolves [KHCP-3165](https://konghq.atlassian.net/browse/KHCP-3165)
=> fix(ktable): allow table clicks to pass through [KHCP-3165]

packages/Krumbs/Krumbs.vue
Fix `Krumbs` icon size to allow the icon itself to control its own viewBox.
Already ported to `next` branch.
=> fix(kbreadcrumbs): icon size

docs/components/select.md, packages/KPagination/KPagination.vue, packages/KPagination/__snapshots__/KPagination.spec.js.snap, packages/KSelect/KSelect.spec.js, packages/KSelect/KSelect.vue, packages/KSelect/KSelectItem.vue, packages/KSelect/__snapshots__/KSelect.spec.js.snap, packages/KTable/__snapshots__/KTable.spec.js.snap
Add support for customizable items and custom filtering.
* Add slot `item-template` for customizing items
* Add `filterFunc` prop 
- Updates to the corresponding `.spec.ts` test file(s) to utilize [Cypress Component Testing](https://docs.cypress.io/guides/component-testing/introduction). 
**Does your PR modify a component [that …
=> feat(kselect): allow custom item content and filter

packages/KModal/KModal.vue
Hide body overflow when `KModal` is open. 
Also adds rule to allow backdrop to scroll as needed.
=> fix(kmodal): hide body overflow

packages/KPop/KPop.spec.js, packages/KPop/KPop.vue, packages/KSelect/__snapshots__/KSelect.spec.js.snap
[https://konghq.atlassian.net/browse/KHCP-3244](https://konghq.atlassian.net/browse/KHCP-3244)
*
=> fix(kpop): fix kpop toggle behavior [khcp-3244]

packages/KViewSwitcher/KViewSwitcher.vue, packages/KViewSwitcher/__snapshots__/KViewSwitcher.spec.js.snap
Metalab style updates
* Style updates for KViewSwitcher
* Update snaps
=> feat(kviewswitcher): metalab style updates

docs/components/card-catalog.md, packages/KCardCatalog/KCardCatalog.spec.js, packages/KCardCatalog/KCardCatalog.vue, packages/KCardCatalog/__snapshots__/KCardCatalog.spec.js.snap, packages/KPagination/KPagination.vue, packages/KTable/__snapshots__/KTable.spec.js.snap
Fix slotting behavior in `KCardCatalog`.
* Add `cardTitle` and `cardBody` slots
* Return `data` on `body` slot
* Return `item` on card slots
=> feat(kcardcatalog): fix item slotting

packages/KCard/KCard.vue, packages/KCard/__snapshots__/KCard.spec.js.snap, packages/KCardCatalog/KCardCatalog.spec.js, packages/KCardCatalog/KCatalogItem.vue, packages/KCardCatalog/__snapshots__/KCardCatalog.spec.js.snap
Long title should not affect placement of `actions` content.
Fix this:
* Allow the `title` slot to take full width below the `statusHat` and `actions` slots
* Check for `title` in `KCatalogItem`
* Update snaps
=> feat(kcard): dom fix

packages/KCatalog/KCatalog.vue
Show `empty` and `loading` states as expected if using `body` slot.
*
=> fix(kcatalog): fix state display with body slot

docs/components/card.md, src/components/KCard/KCard.vue
Fix KCard title positioning.
If no statusHat, align the title with the actions content. If there is a statusHat, align the statusHat with the actions content and display the title beneath.
* Update KCard
* Update snaps
=> fix(kcard): title positioning 

docs/components/card.md, packages/KCard/KCard.vue, packages/KCard/__snapshots__/KCard.spec.js.snap, packages/KCatalog/KCatalogItem.vue, packages/KCatalog/__snapshots__/KCatalog.spec.js.snap
Fix `KCard` title positioning.
If no `statusHat`, align the `title` with the `actions` content. If there is a `statusHat`, align the `statusHat` with the `actions` content and display the `title` beneath.
No statusHat:
With statusHat:
* Update `KCard`
* Update `snaps`
=> fix(kcard): title positioning

TEMP-MIGRATION-CHANGELOG.md, docs/.vuepress/config.ts, docs/components/checkbox.md, docs/components/input-switch.md, docs/contributing/getting-started.md, src/components/KInputSwitch/KInputSwitch.spec.ts, src/components/KInputSwitch/KInputSwitch.vue, src/components/index.ts, src/styles/forms/_switch.scss
Update `KInputSwitch` for Vue 3.
=> feat(kinputswitch): update kinputswitch for vue 3

packages/KCatalog/__snapshots__/KCatalog.spec.js.snap, packages/KPagination/__snapshots__/KPagination.spec.js.snap, packages/KSelect/KSelect.vue, packages/KSelect/KSelectItem.vue, packages/KSelect/__snapshots__/KSelect.spec.js.snap, packages/KTable/__snapshots__/KTable.spec.js.snap
Dropdown form fields do not match other fields (are much shorter height-wise).
[https://konghq.atlassian.net/browse/PDUX-624](https://konghq.atlassian.net/browse/PDUX-624)
-  `.k-select-input` height changed from 32px to `44px`
- Removed the `top` css style for .`kong-icon-chevronDown` to align the icon based on new height
=> test(kselect): update height [pdux-624]

docs/components/table.md, packages/KTable/KTable.vue
Adds a `sortHandlerFn` prop allowing custom sorting on table columns.
* Adds `sortHandlerFn` prop
* Adds `useSortHandlerFn` property to `headers` object
* Updates docs to detail the new prop and provide a usage example
=> fix(ktable): add sortHandlerFn prop

.github/workflows/get-changed-files.yml, .github/workflows/publish.yml, .github/workflows/test.yml
Moves `get-changed-files` CI workflow action into it's own file.
=> ci: update get changed files action

docs/style-guide/type.md
Fix docs display.
https://konghq.atlassian.net/browse/KHCP-3407
=> fix(typography): text display [khcp-3407]

docs/components/menu.md
Fix `width` prop example in docs.
https://konghq.atlassian.net/browse/KHCP-3429
=> fix(kmenu): docs width prop [khcp-3429]

docs/components/badge.md
Docs clean up.
https://konghq.atlassian.net/browse/KHCP-3409
=> fix(kbadge): doc issues [khcp-3409]

src/components/KSegmentedControl/KSegmentedControl.vue
Fix logic for `disabled`.
https://konghq.atlassian.net/browse/KHCP-3433
=> fix(ksegmentedcontrol): disabled logic [khcp-3433]

src/components/KPrompt/KPrompt.vue
Fix `proceedOnEnterLogic` and color of `spinner` icon for `actionPending` state.
https://konghq.atlassian.net/browse/KHCP-3438
=> fix(kprompt): docs fixes [khcp-3438]

packages/KBadge/KBadge.vue
`--KBadgeMinWidth` is [listed as a supported theming variable in the docs](https://kongponents.konghq.com/components/badge.html#theming), but it's not used in the component styling.
- Add `min-width` to KBadge component
=> fix(kbadge): kbadge should support --KBadgeMinWidth

docs/components/alert.md, docs/components/button.md, docs/components/input-switch.md, docs/components/label.md, docs/components/modal.md, docs/components/toaster.md, src/components/KAlert/KAlert.vue, src/components/KCard/KCard.vue, src/components/KIcon/KIcon.vue, src/components/KInputSwitch/KInputSwitch.vue
Docs updates.
- `KAlert` - add `Events` section to docs, descope child styles
- `KButton` - add margin between button examples, fix `Theming` example
- `KCard` - descope child styles
- `KIcon` - bind attrs to parent `span`
- `KInputSwitch` - don't emit duplicate events, added `Events` section to docs
- `KLabel` - doc should have `Props` section and camelcase props
- `KModal` - fix `Theming` example
- `KToaster` - fix spelling errors/spacing between toaster buttons
=> fix(*): doc fixes

docs/components/select.md, src/components/KPop/KPop.vue, src/components/KSelect/KSelect.vue
Fixes:
- Prevent page jump when clicking `KPop` element.
- Hide popover caret in `KSelect.vue`
- Fix Select element examples in the docs.
=> fix(kselect): page jump, caret, and docs

docs/components/select.md, src/components/KSelect/KSelect.spec.ts, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue
Add support for `filterFunc` and slots example
=> feat(kselect): filterfunc support

TEMP-MIGRATION-CHANGELOG.md, docs/components/pagination.md, src/components/KButton/KButton.vue, src/components/KCard/KCard.vue, src/components/KInput/KInput.vue, src/components/KMenu/KMenuItem.vue, src/components/KPagination/KPagination.vue, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue, src/components/KTable/KTable.vue, src/components/KTextArea/KTextArea.vue
Fix `KPagination` theming. Also added new CSS variables
=> fix(kpagination): theming [KHCP-3431]

docs/components/textarea.md, src/components/KTextArea/KTextArea.vue
=> fix(ktextarea): docs cleanup

docs/style-guide/type.md
=> fix(typography): docs display

packages/KTable/KTable.vue
Adds a `data-testid` attribute to empty and error state action buttons using the values passed into the `emptyStateActionMessage` and `errorStateActionMessage` props. The data-testid will reflect the text of the button: if an action button reads "Create New Service", the attribute will be `data-testid="create-new-service"`. This allows the data-testids to be created on the action buttons without needing to manually build out the empty/error states via slots and specify the data-testids by hand.
- Add `data-testid` to error state and empty state action buttons.
If you have questions, tag …
=> fix(ktable): add data-testid to empty/error state buttons

src/components/KCatalog/KCatalog.spec.ts, src/components/KCatalog/KCatalog.vue, src/components/KTable/KTable.spec.ts, src/components/KTable/KTable.vue
Port https://github.com/Kong/kongponents/pull/603 to beta
=> fix(ktable,kcatalog): data-testid additions

src/components/KCatalog/KCatalog.vue, src/components/KTable/KTable.vue
Fix miscellaneous issues with `KTable` and `KCatalog`.
- remove code causing duplicate fetch on initial load
- fix row/cell click handling for Vue3
- trigger row clicks on the `td` instead of the `tr`
=> fix(ktable,kcatalog): fix issues - beta

packages/KCatalog/KCatalog.vue, packages/KTable/KTable.spec.js, packages/KTable/KTable.vue
Fix miscellaneous issues with `KTable` and `KCatalog`.
- remove code causing duplicate fetch on initial load
- fix row/cell click handling for Vue3
- trigger row clicks on the `td` instead of the `tr`
=> fix(ktable,kcatalog): fix issues

packages/KTable/KTable.vue
This resolves the table row click issue we've seen on a number of our tables.
- Removed a condition that limited `@row:click` event listening to just `<td></td>` elements, and not any child elements that may exist within `<td></td>` elements.
=> fix(ktable): create listeners even when td is not clicked target

docs/components/table.md, packages/KTable/KTable.vue
Fix handling of row click events.
- Ignore clicks from `a`, `button`, and `input`
- Ignore clicks from popover content
- Update docs
=> fix(ktable): row click handling

docs/components/table.md, src/components/KTable/KTable.vue
Fix handling of row click events.
- Ignore clicks from `a`, `button`, and `input`
- Ignore clicks from popover content
- Update docs
=> fix(ktable): fix row click handling [beta]

docs/components/table.md, packages/KTable/KTable.vue
Fix an issue where clicking a popover triggered from a button containing only an icon throwing an error on click.
- Fix handling of `className` when an object
- Extend row click logic to query parents
- Docs example update
=> fix(ktable): more row click fix

packages/KPrompt/KPrompt.vue
Fix bottom divider display.
Before:
After:
=> fix(kprompt): bottom divider

docs/components/catalog.md, packages/KCatalog/KCatalog.vue, packages/KTable/KTable.vue
Add `emptyStateActionButtonIcon` prop to `KCatalog`
- add `emptyStateActionButtonIcon` prop to `KCatalog`
- add data-testid's, classes for empty/error state
- use `KButton` `icon` prop
These changes already exist in `beta` branch, no separate PR needed.
=> fix(kcatalog): add emptyStateActionButtonIcon prop

docs/components/catalog.md, src/components/KCatalog/KCatalog.vue, src/components/KTable/KTable.vue
- Update docs with missing prop
- Add empty/error state classes
=> fix(kcatalog,ktables): docs and classes [beta]

src/styles/_mixins.scss, src/styles/_utils.scss, src/styles/styles.scss
You cannot multiply `{number}px` * `{number}px` in Sass, so we are removing the `px` from the `--TPadRight` variable.
=> fix(truncate-multi): fix pixel multiplication

packages/KIcon/KIcon.vue
This is part two of a two part fix that resolves an issue where the icon color within a KButton was not being updated when the disabled attribute on the KButton was toggled.
When the value of the `color` prop was updated, it was not being applied to the icon.
Part one of this fix is here: https://github.com/Kong/kongponents/pull/622
=> fix(kicon): watch icon color to apply updates

packages/KButton/KButton.vue
This is part one of a two part fix that resolves an issue where the icon color within a KButton was not being updated when the `disabled` attribute on the KButton was toggled.
Sometimes `this.$attrs.disabled` can be passed in as `false` and in these cases we want to ensure the button icon color gets updated.
Part two of this fix is here: https://github.com/Kong/kongponents/pull/623
=> fix(kbutton): account for when disabled is false

src/components/KButton/KButton.vue, src/components/KIcon/KIcon.vue
Applies https://github.com/Kong/kongponents/pull/622 and https://github.com/Kong/kongponents/pull/623 to the beta branch.
=> fix(kbutton,kicon): fix button icon color [beta]

packages/KIcon/KIcon.vue
When the `icon` prop changes for `KIcon`, we need to re-render the svg itself and recalculate width, height, colors, etc.
---
=> fix(kicon): re-render svg on icon prop change

docs/components/table.md
Fix KTable examples with no fetcher
---
=> docs(ktable): fix tables with no fetcher

docs/components/table.md, packages/KTable/KTable.vue
Emit event on row/cell click
---
=> fix(ktable): emit event on cell and row click

packages/KIcon/__snapshots__/KIcon.spec.js.snap, packages/KIcon/icons/icn-no-data.svg, packages/KIcon/icons/index.js
https://konghq.atlassian.net/browse/MA-606
Added a new dashed line KIcon (grabbed it from Figma).
---
=> MA-606: add "no data" icon for vitals

docs/components/input.md, docs/components/select.md, packages/KInput/KInput.vue, packages/KTextArea/KTextArea.vue
- Fix issue where manipulating `KInput` `v-model` externally was not reflected
- Wrap `KSelect` in `<div>` for broken markdown issue related to tabbing
---
=> fix(kinput): fix manual change to v-model

docs/components/label.md, docs/components/popover.md, docs/components/tooltip.md, packages/KCatalog/__snapshots__/KCatalog.spec.js.snap, packages/KLabel/KLabel.vue, packages/KLabel/__snapshots__/KLabel.spec.js.snap, packages/KMultiselect/__snapshots__/KMultiselect.spec.js.snap, packages/KPagination/__snapshots__/KPagination.spec.js.snap, packages/KPop/KPop.vue, packages/KPop/__snapshots__/KPop.spec.js.snap, packages/KSelect/__snapshots__/KSelect.spec.js.snap, packages/KTable/__snapshots__/KTable.spec.js.snap, packages/KoolTip/KoolTip.vue, packages/KoolTip/__snapshots__/KoolTip.spec.js.snap
Task in Jira: https://konghq.atlassian.net/browse/KHCP-3486
---
=> feat(klabel, kooltip): added support for max-width and tooltip-attributes [KHCP-3486]

packages/KInput/KInput.vue, packages/KTextArea/KTextArea.vue
We are watching the `value` and then re-assigning it to another var that is editable - clone the value before doing this.
---
=> fix(kinput): deepclone value prop

docs/style-guide/utilities.md, src/styles/_utils.scss
- Add support for `.multi-line-truncation`
- Deprecate `.truncate-multi`
---
=> feat(kstyles): multi-line truncation [beta]

packages/KIcon/__snapshots__/KIcon.spec.js.snap, packages/KIcon/icons/icn-decrease.svg, packages/KIcon/icons/icn-increase.svg, packages/KIcon/icons/index.js
https://konghq.atlassian.net/browse/MA-643
Still need to resolve view box / artboard padding (icons not centered)
---
=> MA-643: add increase / decrease icons

packages/KModalFullscreen/KModalFullscreen.vue
- fix alignment of icon and header text / height of divider
Addresses [KHCP-4021](https://konghq.atlassian.net/browse/KHCP-4021)
---
=> fix(kmodalfullscreen): align header [khcp-4021]

docs/components/table.md, packages/KTable/KTable.spec.js, packages/KTable/KTable.vue
Addresses one of the solutions from this ticket:
[https://konghq.atlassian.net/browse/PDUX-741](https://konghq.atlassian.net/browse/PDUX-741)
Adds new `prop` for KTable `hidePaginationWhenOptional` to display record navigation only when there are more than 15 records in a `KTable`. Otherwise the control should be hidden.
---
=> fix(ktable): hide pagination based on row numbers

docs/components/pagination.md, docs/components/table.md, src/components/KPagination/KPagination.vue, src/components/KPagination/PaginationOffset.vue, src/components/KTable/KTable.vue
Adds support for offset-based pagination.
In practice, the following would need to be done in order to enable offset-based pagination:
1. Use the new `paginationType` prop for KTable: `<KTable :pagination-type="offset" />`
2. Use the new `offset` param in the fetcher function passed to KTable: `fetcher ({ offset }) {}`
**Assumptions:**
This implementation assumes that the API endpoint used in the fetcher function returns the next offset value in the response. Here is an example of the assumed format:
```json
{
"data": [{}],
"pagination": {
"offset": "cGFnZS1udW1iZXI6Mg"
},
}
```
This implementation also assumes that the API endpoint used in the fetcher function properly handles offset usage. Here's an example:
`GET /api/runtime_groups/6e30594e-9a90-4e0f-94f8-90b923696c83/services?size=100& …
=> feat(kpagination/ktable): support offset-based pagination

src/components/KModalFullscreen/KModalFullscreen.vue
Backport https://github.com/Kong/kongponents/pull/682
---
=> fix(kmodalfullscreen): backport spacing

packages/KCatalog/KCatalog.spec.js, packages/KCatalog/KCatalog.vue, packages/KTable/KTable.spec.js, packages/KTable/KTable.vue
Hide pagination bar if less than minimum pagesize, not current pagesize.
---
=> fix(ktable,kcatalog): hide pag logic [khcp-3929]

src/components/KButton/KButton.spec.ts, src/components/KButton/KButton.vue
Because of the new [attribute coercion behavior](https://v3-migration.vuejs.org/breaking-changes/attribute-coercion.html) in Vue 3, if a `KButton` with `:disabled="false"` renders an `<a>` element, the `disabled` attribute is not removed. As a result, the `<a>` element is greyed out and cannot be interacted with.
Reproduction Link: https://codesandbox.io/s/hungry-jones-cf7k0k?file=/src/App.vue
This PR fixes this by stripping falsy disabled attribute before binding `$attrs`.
---
=> fix(kbutton): falsy disabled attribute on native link element

docs/components/menu.md, docs/components/popover.md, docs/components/select.md, packages/KCatalog/__snapshots__/KCatalog.spec.js.snap, packages/KMenu/KMenu.vue, packages/KPagination/__snapshots__/KPagination.spec.js.snap, packages/KPop/KPop.vue, packages/KSelect/KSelect.spec.js, packages/KSelect/KSelect.vue, packages/KSelect/__snapshots__/KSelect.spec.js.snap, packages/KTable/__snapshots__/KTable.spec.js.snap, packages/styles/forms/_inputs.scss
- Fix `width` prop handling to ensure selected item, input, and dropdown are the same size
- Add support for `%` for `width` props
- Add `enableFilter` prop to control filter support on `KSelect` input
---
=> feat(kselect): misc fixes [khcp-4146]

docs/components/select.md, packages/KPop/KPop.vue, packages/KSelect/KSelect.vue, packages/KSelect/KSelectItem.vue, packages/styles/forms/_inputs.scss
Addresses: 
[https://konghq.atlassian.net/browse/KHCP-4158](https://konghq.atlassian.net/browse/KHCP-4158)
**KSelect (general rules)**
- Updates `minimum font size`
- Adds `margin` and `padding` for dropdown items
- `Caret` should switch direction on open/close of dropdown
**KSelect (default, no slots)**
- Updates `font-size` and `font-weight` of dropdown items
**KSelect (slotted content)**
- Support `.select-item-label` by default, and sets` font weight` and `font-size`
- Support `.select-item-description` by default, and sets` font weight` and `font-size`
I have added the label `port to beta branch`. Once this is approved, I will port the changes.
If you have questions, tag `@adamdehaven` or …
=> style(kselect): update for new UI [khcp-4158]

docs/components/select.md, src/components/KSelect/KSelect.vue
- Add support for `overlayLabel` prop
- Clean up the docs
---
=> feat(kselect): add overlayLabel support [beta]

docs/components/select.md, src/styles/forms/_inputs.scss
- Fix KCheckbox,KRadio styles
- KSelect docs cleanup
---
=> fix(kcheckbox): readonly styles

docs/components/select.md, packages/KInput/KInput.vue, packages/KSelect/KSelect.vue, packages/styles/forms/_inputs.scss
- Fixes `.k-input` `disabled` and `readonly` styles so that they are supported both on the component and if a user only utilizes the CSS classes
- Updates `KSelect` `disabled` and `readonly` logic to both be styled correctly given these attributes, but also to respond to or ignore the filter and text input accordingly.
- Adds a `readonly` KSelect to the `overviewLabel` docs just to display a readonly example
---
=> fix(kselect): disabled and readonly states

docs/components/select.md, src/components/KInput/KInput.vue, src/components/KSelect/KSelect.vue, src/styles/forms/_inputs.scss
- Fixes `.k-input` `disabled` and `readonly` styles so that they are supported both on the component and if a user only utilizes the CSS classes
- Updates `KSelect` `disabled` and `readonly` logic to both be styled correctly given these attributes, but also to respond to or ignore the filter and text input accordingly.
- Adds a `readonly` KSelect to the `overviewLabel` docs just to display a readonly example
---
=> fix(kselect): disabled and readonly states [beta]

packages/KModal/KModal.vue
Update `KModal` to not capture all clicks inside the body (allows usage of `KSelect` within the modal)
---
=> fix(kmodal): allow clicking on elements within the modal body [KHCP-4212]

.github/workflows/test.yml, docs/components/popover.md, packages/KPop/KPop.vue
Fix KPopover errors due to a misconfigured target
---
=> fix(kpopover): fix logic to prevent errors

.gitignore, docs/components/select.md, src/components/KPop/KPop.vue, src/components/KSelect/KSelect.spec.ts, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue
Add autosuggest support for KSelect. Port over the changes from #717.
=> feat(kselect): add autosuggest support [KHCP-4292]

docs/components/select.md, packages/KSelect/KSelect.vue
When KSelect uses `v-model`, we need to update the selected item when the `value` is modified programatically.
---
=> fix(kselect): adds watch for selected item

packages/KModal/KModal.vue, packages/KoolTip/KoolTip.vue
z-index of `Kooltip` needs to be at least as high as z-index of `KModal` so they will show when inside.
Tested locally with:
```
<KModal
:is-visible="slottedIsOpen3"
title="Look at my slots!"
content="You know you like these slots."
show-dismiss-icon
dismiss-button-theme="dark"
@canceled="slottedIsOpen3 = false"
>
<template v-slot:header-image>
<div class="slot-image-content">
<h4 class="mx-7 my-5">I'm slotted baby!</h4>
<div>
<KoolTip placement="right" label="A label that appears on the right">
<KButton>right</KButton>
</KoolTip>
<KLabel info="This is an example">Input Title</KLabel>
</div>
</div>
</template>
<template v-slot:action-buttons>
<KButton appearance="btn-link" class="mr-2" @click="slottedIsOpen3 = false">Pass</KButton>
<KButton appearance="primary" @click="slottedIsOpen3 = …
```
=> fix(kooltip): z-index bump

src/components/KSelect/KSelect.vue
`KInput` does not have `is-open` prop, so `KSelect` should not pass it down. Otherwise the rendered input would be:
@adamdehaven
=> fix(kselect): remove is-open prop on KInput

packages/KPop/KPop.vue
Update the default `target` for `KPop.vue` so that it properly attaches to the generated target `id` or the provided `target`
---
=> fix(kpop): target element defaults

src/components/KPagination/KPagination.spec.ts, src/components/KPop/KPop.vue, src/components/KSelect/KSelect.spec.ts
Update the default target for KPop.vue so that it properly attaches to the generated target id or the provided target
---
=> fix(kpop): update target default

src/components/KSelect/KSelect.vue
The popover's width is only set in the `onMounted` hook. This works fine except:
1. `<KSelect>`'s visibility is controlled by `v-show`: https://codesandbox.io/s/crazy-moon-vokjk5
2. `<KSelect>` has a relative `width` and user resizes the viewport: https://codesandbox.io/s/happy-hawking-ngq8td
The perfect solution would be to use `MutationObserver`, but I think updating popover's width every time it opens can solve most of the problem (except when user resizes the viewport while the popover is open, which IMO is acceptable).
Let me know what you think. @adamdehaven @kaiarrowood
=> fix(kselect): update popover width when it opens

docs/.vuepress/config.js, docs/.vuepress/enhanceApp.js, docs/components/dropdown-menu.md, docs/components/select.md, docs/components/table.md, package.json, packages/KButton/package.json, packages/KDropdownMenu/KDropdownItem.vue, packages/KDropdownMenu/KDropdownMenu.spec.js, packages/KDropdownMenu/KDropdownMenu.vue, packages/KDropdownMenu/README.md, packages/KDropdownMenu/__snapshots__/KDropdownMenu.spec.js.snap, packages/KDropdownMenu/index.js, packages/KDropdownMenu/package.json, packages/Krumbs/package.json, yarn.lock
- Add new `KDropdownMenu` kongponent - ported from `khcp-ui`.
- Bump `vue-router` to match version used in `khcp-ui`
- Add it as a `peerDependency` to `KButton`
For [KHCP-690](https://konghq.atlassian.net/browse/KHCP-690).
---
=> feat(kdropdownmenu): new component [khcp-690]

docs/components/modal.md, packages/KModal/KModal.vue
Change the dismiss icon logic as described in [KHCP-4354](https://konghq.atlassian.net/browse/KHCP-4354).
---
=> fix(kmodal): dismiss icon logic [khcp-4354]

packages/KCatalog/KCatalog.vue, packages/KTable/KTable.vue
Updates `KEmptyState` action button color inside `KTable/KCataolg` based on:
- If no data in the list at all, then action button will be a primary button
- if there is data, but if filtered data is empty, then a button link to clear filters
---
=> style(empty-state): update button color [khcp-4222]

src/components/KTable/KTable.vue
`<KTable>` without side borders will throw a warning:
> [Vue warn]: v-on with no argument expects an object value.
@adamdehaven @kaiarrowood
=> fix(ktable): update v-on value

packages/KPop/KPop.vue, packages/KSelect/KSelect.spec.js, packages/KSelect/KSelect.vue
- Only trigger the `items` watcher if the items changed
- Ensure every item always has a `selected` property (`boolean`)
- Prevent the `item.key` from having extra `-selected` text appended if already selected
---
=> fix(kselect): fix items watcher and only update if changed [KHCP-4425]

packages/KButton/KButton.vue
Remove webkit tap highlight color for `KButton`
Resolves #752 
---
=> fix(kbutton): remove webkit tap color

src/components/KMenu/KMenu.vue, src/components/KPop/KPop.vue, src/components/KSelect/KSelect.vue, src/composables/useUtilities.spec.ts, src/composables/useUtilities.ts
Components should use new `getSizeFromString` function.
---
=> fix(*): misc cleanup

packages/KStepper/package.json
Should fix the following error:
---
=> fix(kstepper): include all vue files in package

docs/components/select.md, packages/KSelect/KSelect.spec.js, packages/KSelect/KSelect.vue, packages/KSelect/__snapshots__/KSelect.spec.js.snap
Adds `clearable` to `<KSelect>`.
@adamdehaven @kaiarrowood 
---
=> feat(kselect): add clearable prop

docs/components/alert.md, packages/KAlert/KAlert.spec.js, packages/KAlert/KAlert.vue, packages/KAlert/__snapshots__/KAlert.spec.js.snap, packages/KIcon/__snapshots__/KIcon.spec.js.snap, packages/KIcon/icons/icn-error-filled.svg, packages/KIcon/icons/index.js, packages/KToaster/__snapshots__/KToaster.spec.js.snap
Updates for [KHCP-4405](https://konghq.atlassian.net/browse/KHCP-4405).
- Add new KIcon: `errorFilled`
- Refactor `KAlert` docs and styles
- Don't restrict `icon` to `large` `banner` alerts
- Change `description` to only depend on `large` size
- Previously undocumented props: `iconSize`, `iconColor`, `description`
- New props: `title`
- New slots: `icon`, `title`
---
=> feat(kalert): updates for KHCP-4405

packages/KStepper/KStep.vue
Removes an unused prop which is throwing errors:
Here's the commit I used as a reference for safely removing this: https://github.com/Kong/kongponents/pull/745/commits/5db26878b48742ba61beaa2c2609086b2a28da92
Looks like this has already been fixed in the `beta` branch: https://github.com/Kong/kongponents/blob/beta/src/components/KStepper/KStep.vue#L7
---
=> fix(kstepper): remove unused prop which is throwing errors

packages/KModal/KModal.vue
Stop the propagation of `click` events on a `KModal`. 
Resolves a situation like this:
> I don’t want to have to manually stop propagation on @proceed (or any click event) of KPrompts/KModals that are defined within a KTable structure to avoid triggering the row click.
---
=> fix(kmodal): prevent click propagation [KHCP-4525]

docs/components/select.md
This PR adds `loading` and `empty` slots docs.
---
=> docs(kselect): add missing documentation slots [KHCP-4631]

src/components/KDropdownMenu/KDropdownItem.vue, src/components/KDropdownMenu/KDropdownMenu.vue, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue, src/components/KStepper/KStepper.vue
Replace instances of `Object.hasOwn()` since the browser support is pretty recent.
---
=> fix(*): replace Object.hasOwn()

docs/components/dropdown-menu.md, packages/KButton/KButton.vue, packages/KDropdownMenu/KDropdownItem.vue, packages/KDropdownMenu/KDropdownMenu.vue, packages/KDropdownMenu/__snapshots__/KDropdownMenu.spec.js.snap, packages/KInput/KInput.vue, packages/KMultiselect/KMultiselect.vue, packages/KMultiselect/__snapshots__/KMultiselect.spec.js.snap, packages/KPrompt/__snapshots__/KPrompt.spec.js.snap, packages/KSelect/KSelect.vue, packages/KSelect/KSelectItem.vue, packages/KStepper/KStepper.vue
- Add props to `KDropdownMenu`: `icon`, `buttonAppearance`
- Remove usage of `hasOwn`/`hasOwnProperty`
- Fix display of icons in disabled `KButton` getting the wrong color
---
=> fix(kdropdownmenu): add icon/buttonAppearance props

docs/README.md, docs/style-guide/usage.md, package.json
Fixes an issue with not being able to import the style.css file using a bare module specifier (i.e. `import '@kong/kongponents/dist/style.css'`) due to the absence of the specifier definition from the package.json file’s `exports` field. A workaround for this issue is using `import '../node_modules/@kong/kongponents/dist/style.css'`.
---
=> fix: not being able to import style.css

src/composables/useUtilities.spec.ts, src/composables/useUtilities.ts
Client sorting by a column of number values will have a wrong order if that column contains zeros.
Reproduction link: https://codesandbox.io/s/mystifying-stallman-zzlfmu
I'm not sure why we need to check `if (a && b)` in the first place. IMO if we need to check anything it should be the type of `b`. The code down below guarantees `a` is a number, but leaves `b` unchecked (although in most cases they should be of the same type).
So I changed `if (a && b)` to `if (typeof b === 'number')`. Let me know your opinions. @adamdehaven @kaiarrowood 
---
=> fix(ktable): client sorting with number values

packages/KSelect/KSelect.vue
=> refactor(kselect): remove the `items` slot [KHCP-4668]

packages/KSelect/KSelect.vue
Task in Jira: https://konghq.atlassian.net/browse/KHCP-4680
- **Fix** - Add an additional condition.
- **Refactor** - Removal of redundant `replace`.
---
=> refactor(kselect): cannot read properties of undefined (reading replace) [KHCP-4680]

packages/KDropdownMenu/KDropdownItem.vue
Remove sass division, we can't guarantee `@use sass:math` will be first.
---
=> fix(*): remove sass division

packages/KSelect/KSelect.vue
Updates placeholder text for KSelect auto-suggest.
**Before**:
**After**:
---
=> fix(text): kselect placeholder text

docs/components/table.md
Document correct usage of SWRV revalidate function and key for `KTable`.
For [KHCP-4670](https://konghq.atlassian.net/browse/KHCP-4670).
---
=> fix(ktable): doc revalidate usage [khcp-4670]

src/components/KModal/KModal.vue
Fixes an issue with the modal component not importing the `KIcon` component that it uses.
---
=> fix(modal): not importing icon component

packages/KModal/KModal.vue, packages/KModal/package.json
Add missing `KIcon` dependency.
---
=> fix(kmodal): missing kicon dependency

packages/KPop/KPop.vue
There was a bug with `KPop` where it was always registering a click listener on the document root element, but only removing it when the trigger type was `'click'`. This caused event listeners to not fire for other elements after the kpop element was destroyed.
---
=> fix(kpop): always remove click listeners since they are always added

package.json
Fixes the build script generating a `dist/types/index.d.ts` file that merely contains `export {};` because of the build:cli script running last (this doesn’t happen with published packages because the order of scripts is reversed in the CI workflow).
I suppose this happens somehow because cli/tsconfig.json extends the base tsconfig.json file?
---
=> chore: build script generating incomplete types in dist

src/components/KButton/KButton.vue
Replaces the `padding-right` declaration on a button’s icon with a `gap` property on the button itself which allows adding visually-hidden text to an icon button (this would otherwise have an incorrect gap to the right). This works because visually-hidden text won’t participate as a flex or grid item so no gap will be rendered.
---
```vue
<KButton>
<template #icon>
<KIcon icon="filter" />
</template>
<span class="k-visually-hidden">Filter mode enabled</span>
</KButton>
```
=> fix(kbutton): not considering visually-hidden text

src/components/KInput/KInput.vue, src/styles/forms/_inputs.scss
Fixes issues with the `input-error` class being applied to KInput.
---
=> fix(kinput): input-error styles [KHCP-5100]

docs/components/inline-edit.md, docs/style-guide/forms.md, src/components/KCheckbox/KCheckbox.vue, src/components/KInlineEdit/KInlineEdit.vue, src/components/KInput/KInput.vue, src/components/KInputSwitch/KInputSwitch.vue, src/components/KRadio/KRadio.vue, src/components/KSelect/KSelect.vue, src/components/KTextArea/KTextArea.vue, src/styles/forms/_inputs.scss
Bind classes to the outermost wrapper element instead of the child element(s). 
As an example, this allows for doing `<KInput class="w-100 mr-4" />` and the classes to be applied correctly to the wrapper element.
If merged, Konnect will need to updated to add a class of `w-100` to most `KTextArea` components.
---
=> fix(attrs): bind classes to outermost element

src/components/KPop/KPop.vue
`KPop` is throwing an error because of the `removeOnDestroy` setting on the Popperjs element. On the first `popper.destroy()` call the parent exists and the `removeChild` call works successfully; however, subsequent calls fail because the parentNode is no longer defined. I believe this is because of changes in Vue 3 and how the virtual DOM is rendered.
---
=> fix(kpop): do not remove on destroy [KHCP-5139]

src/components/KCodeBlock/KCodeBlock.spec.ts, src/components/KCodeBlock/KCodeBlock.vue
fix(kcodeblock): handling small resolutions poorly:
Addresses a few issues with the rendering of `KCodeBlock` in smaller resolutions. The actions bar items are now wrapping appropriately and the search input no longer extends beyond the available size.
fix(kcodeblock): shortcuts using Alt not working on macOS:
Fixes a bug where the default shortcuts involving the Alt key weren’t working on macOS because Options+letter commonly results in a differently typed character. The shortcut mechanism now checks the `event.code` property instead of `event.key` to do this more reliably.
fix(kcodeblock): not preventing default action for some shortcuts:
Fixes an issue with not correctly preventing the default action for some shortcuts (e.g. `Alt+F` opening a Chrome menu by default).
=> fix(kcodeblock): a couple of issues

docs/components/badge.md, src/components/KBadge/KBadge.vue
Add support for dismissing a `KBadge`.
Also bump the default text size up to `12px`.
=> feat(kbadge): add dismissable prop [khcp-5146]

src/components/KSelect/KSelect.vue
This pull request fixes an issue where users cannot change the value of the input box in `KSelect`.
Using `KSelect` with autosuggest and having `v-model` defined and its value matches one item in `items`.
A live demo on CSB: https://codesandbox.io/s/kselect-autosuggest-repro-ynkd93?file=/src/App.vue
1. Focus on the input box
2. Input `aa` or `aab`
3. The `aabbaa` keeps showing up in the input
4. Try deleting `aabbaa` from the right side
5. The `aabbaa` keeps showing up in the input
**KHCP-5153**
=> fix(kselect): broken input with autosuggest [KHCP-5153]

src/components/KPop/KPop.vue
This pull request fixes an issue where KPop is not working as expected when the `disabled` property changes.
Live demo: https://codesandbox.io/s/kpop-disabled-repro-r57iqb?file=/src/App.vue
KHCP-5183
=> fix(kpop): disabled prop does not work as expected

src/components/KDropdownMenu/KDropdownItem.vue, src/components/KMenu/KMenuItem.vue, src/components/KStepper/KStepper.vue
Some `data-testid` attributes had incorrect logic to only replace the first instance of a space in the string. This PR replaces _all_ spaces with a dash `-`
When we go to merge, we need to pull this into a PR for `khcp-ui` to ensure it doesn't break existing test selectors
`data-testid="sidebar-item-Personal-access tokens"`
`data-testid="sidebar-item-Personal-access-tokens"`
=> fix: replace all instances of a space

src/components/KCodeBlock/KCodeBlock.vue
Fixes an issue with code block content overflowing in a way that forces the component to grow wider instead of only the code content scrolling horizontally *within* the component. This can happen with long lines of code.
=> fix(kcodeblock): code block content overflowing

src/components/KBadge/KBadge.vue
Fixes the child components not being registered in KBadge.
=> fix(kbadge): components not being registered

docs/components/catalog.md, docs/components/table.md, src/components/KCatalog/KCatalog.spec.ts, src/components/KCatalog/KCatalog.vue, src/components/KTable/KTable.spec.ts, src/components/KTable/KTable.vue
Add `KTable` and `KCatalog` `#toolbar` slot.
=> feat(ktable-kcatalog): add toolbar slot [KHCP-5224]

src/components/KTextArea/KTextArea.vue, src/styles/_typography.scss
Addresses:
[https://konghq.atlassian.net/browse/KHCP-5265](https://konghq.atlassian.net/browse/KHCP-5265)
**Before:**
**hover-**
**placeholder text color -** 
**text font weight -**
**After:**
**hover-**
**placeholder text color -** 
**text font weight -**
=> style(ktextarea): fix styles [khcp-5265]

docs/components/modal-fullscreen.md, src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.vue, src/components/KStepper/KStep.vue, src/components/KStepper/KStepState.vue, src/components/KStepper/KStepper.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-4160](https://konghq.atlassian.net/browse/KHCP-4160)
Fixes the issue where KModalFullscreen gets overlapped by KSelect Caret/KMultiSelect Caret/KStepper.
To repro, go to Create New Upstream modal, click on a KSelect, then scroll down.
=> fix(*): fix the issue of stepper, select icon

docs/components/multiselect.md, src/components/KMultiselect/KMultiselect.cy.ts, src/components/KMultiselect/KMultiselect.vue, src/components/KMultiselect/KMultiselectItem.vue
This PR adds disabled items support for `KMultiselect`.
=> feat(kmultiselect): support disabled item

src/components/KSelect/KSelect.vue
Fixed a style bug that the arrow icon of `KSelect` is not vertically centered:
=> fix(kselect): vertical alignment for arrow icon

src/components/KPop/KPop.vue
Vue transition classes are impacting the placement of KPop `.k-popover` elements. Needs something like this:
```scss
&.fade-enter-active,
&.fade-enter-to,
&.fade-leave-active,
&.fade-leave-to {
animation: none !important;
}
```
=> fix(kpop): disallow vue animation classes [KHCP-5349]

docs/components/codeblock.md, src/components/KCodeBlock/KCodeBlock.vue
Fixes a small issue with the `code-block-render` event being emitted before re-rendering is actually done. This is only an issue **when changing the `props.code`** as the event is already delayed by one Vue tick when turning off filter mode and doesn’t need to be delayed when emitting the event as part of the `mounted` life cycle hook.
=> fix(kcodeblock): code-block-render event being emitted too soon

docs/components/checkbox.md, docs/components/radio.md, src/components/KCheckbox/KCheckbox.vue, src/components/KRadio/KRadio.vue
Update KRadio and KCheckbox to support a label with description text
* Added support for a label along with description subtext for both KRadio and KCheckbox.
* Also updated docs with examples.
=> feat(kradio, kcheckbox): support label desc in radio, ckbox [KHCP-4339]

src/components/KCheckbox/KCheckbox.vue, src/components/KRadio/KRadio.vue
Use default slot to compute hasLabel so default slot is rendered, verified in KCheckbox & KRadio docs (screenshots below).
Ticket: https://konghq.atlassian.net/browse/KHCP-4339
=> fix(kradio, kcheckbox): use default slot to compute hasLabel [KHCP-4339]

docs/components/input.md, docs/components/select.md, src/components/KInput/KInput.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.vue, src/styles/forms/_inputs.scss
Addresses:
[https://konghq.atlassian.net/browse/KHCP-5396](https://konghq.atlassian.net/browse/KHCP-5396)
Issue:
Background color of KSelect kongponent:
Also fixes the overlay issue:
**Before:**
**After:**
`Note:` I have verified that things are looking as expected in all across Kongponents, I would appreciate a through functionality review for this PR. I tried to symlink but it is not working and can't check the impact of these updates across Konnect.
=> fix(select-input): update background issue styles [khcp-5396]

src/components/KPop/KPop.vue
This PR fixes a bug that `popoverTimeout` prop does not work (popover disappears immediately after the mouse leaves no matter the value of `popoverTimeout`). I think this might be related to #835.
=> fix(kpop): popoverTimeout prop

src/components/KSelect/KSelect.vue
The outer container of `KSelect` has a box shadow:
Default:
Hover:
Focus:
This PR removes this box shadow.
=> fix(kselect): remove box shadow on `.k-select-input`

docs/components/select.md, docs/components/tooltip.md
KSelect dropdown elements on the docs page were rendering incorrectly
=> docs(kselect): wrap with client only

src/components/KFileUpload/KFileUpload.vue
Hides the native file upload button in Firefox
=> fix(kfileupload): hide native button in firefox [KHCP-5462]

src/components/KTable/KTable.vue
This pull request adds accessibility attributes to KTable headers.
=> fix(ktable): add a11y attributes

docs/.vitepress/theme/_percy.scss, docs/.vitepress/theme/index.scss, docs/components/datetime-picker.md
Hide the "Last updated" timestamp on docs pages from Percy so it doesn't trigger a change.
=> chore(percy): hide docs elements in percy

src/components/KButton/KButton.vue, src/components/KSelect/KSelect.vue
Remove the padding on `btn-link` appearance buttons and apply outline for `:focus-visible`.
Addresses [KHCP-5475](https://konghq.atlassian.net/browse/KHCP-5475).
=> fix(kbutton): btn-link styles [khcp-5475]

package.json, src/components/KModal/KModal.vue, yarn.lock
This PR traps focus inside `<KModal>` for the sake of a11y, which fixes [a vpat violation](https://docs.google.com/spreadsheets/d/1JinlVfNFFvxCB2qug3YYc-wGhg8ptpF3/edit#gid=684765038&range=51:51):
I checked [vuetify](https://github.com/vuetifyjs/vuetify/blob/bb9412cb3efefd4852b3220705cc41ecfb4d438f/packages/vuetify/src/components/VDialog/VDialog.ts#L216-L217) and [element](https://github.com/element-plus/element-plus/blob/33ca7ee4f06febfd9bcec33bb66e62e27f0102c1/packages/components/dialog/src/dialog.vue#L28-L36), and they both trap focus inside modals, so I think this is something we should do in kongponents.
This PR introduces two new dependencies, resulting in a 5KB~ package size increase:
Let me know what you think.
=> feat(kmodal): add focus trap support for better a11y

src/components/KModal/KModal.vue, vite.config.ts
Add a delay for focus trap activation to ensure the focused element doesn't capture the event that caused the activation. Resolves #946.
=> fix(kmodal): add focus trap activation delay

docs/components/segmented-control.md, src/components/KSegmentedControl/KSegmentedControl.vue
Adds an `allow-pointer-events` slot to `KSegmentedControl` (`false` by default) which disallows pointer events on the button slot content.
=> fix(ksegmentedcontrol): disallow slot pointer events by default [MA-1189]

docs/components/tree-list.md, src/components/KTreeList/KTreeDraggable.vue, src/components/KTreeList/KTreeItem.vue, src/components/KTreeList/KTreeList.vue
The types inside of `KTreeList.vue` being imported from `KTreeItem.vue` were using the `@/` alias, which will break in consuming packages.
This PR updates the type import to not use the alias.
Also, all of the `KTreeList/` components had `export default {}` at the bottom of the script setup; I'm not sure why...? Removed.
=> fix(ktreelist): remove alias from import path

docs/components/badge.md, src/components/KBadge/KBadge.cy.ts, src/components/KBadge/KBadge.vue
Add `isBordered` prop to `KBadge`.
Addresses [KHCP-5591](https://konghq.atlassian.net/browse/KHCP-5591).
=> feat(kbadge): add isBordered prop [khcp-5591]

src/components/KCodeBlock/KCodeBlock.vue, src/utilities/ShortcutManager.ts
Moves general shortcut handling code out of the KCodeBlock component into utilities. This way, other components can make use of it and leaves only the responsibility of providing a key map and a commands object to the components themselves.
Fixes the KCodeBlock’s copy shortcut (i.e. Alt+C) not working.
=> refactor: externalizes shortcut manager utility

docs/components/skeleton.md, src/components/KSkeleton/CardSkeleton.vue, src/components/KSkeleton/FullScreenKongSkeleton.vue, src/components/KSkeleton/KSkeleton.vue
- Adjust documentation
- Set card to have min-height instead of explicit height
- Fix axe linter warning
- Add `hideProgress` prop
Addresses [KHCP-5659](https://konghq.atlassian.net/browse/KHCP-5659).
Fixed card issue:
=> fix(kskeleton): documentation [khcp-5659]

src/components/KModal/KModal.vue, src/components/KPrompt/KPrompt.vue
=> fix(kmodal): update close button styles [khcp-5508]

docs/components/codeblock.md, src/components/KCodeBlock/KCodeBlock.vue
Allows the `pre` element to scroll if the max-height is set. Also adds documentation for the `--KCodeBlockMaxHeight` CSS variable.
> Notice the code overflowing the container and text
=> fix(kcodeblock): allow container to scroll

src/components/KSelect/KSelect.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-5661](https://konghq.atlassian.net/browse/KHCP-5661)
This PR adds the missing `disabled` styles for `KSelect`.
**Before:**
**After:**
=> fix(kselect): update disabled styles [khcp-5661]

docs/components/codeblock.md, src/components/KCodeBlock/KCodeBlock.vue
Add a new `theme` prop to `KCodeBlock` that accepts `light` (default) or `dark`
=> feat(kcodeblock): dark theme [KHCP-5231]

docs/components/badge.md, src/components/KBadge/KBadge.vue
Adds new `borderColor` prop to allow customizing badge border color.
I decided against adding a `--KBadgeBorderColor` variable because it seemed difficult to determine a good default without knowing more about the theme of the badge.
=> feat(kbadge): add borderColor prop

.github/workflows/get-changed-files.yml, .github/workflows/publish.yml, docs/.vitepress/cache/deps/_metadata.json, src/components/KDropdownMenu/KDropdownItem.vue, src/main.ts
Unscope the `KDropdownItem` styles so that they are always properly applied to all dropdown content, regardless of slotted or not, etc.
=> fix(kdropdownmenu): unscope styles [KHCP-5730]

docs/components/codeblock.md, src/components/KCodeBlock/KCodeBlock.cy.ts, src/components/KCodeBlock/KCodeBlock.vue
- Adds a new `useSingleLine` prop, which will display the code passed into the CodeBlock component on a single line. We have a number of use cases and requirements for this in Konnect.
- Adds docs for the new prop
- Adds a test that verifies the new class is added
**Notes:**
- Line numbers will not be displayed and code will not be searchable when `useSingleLine` is enabled
- I'd thought about adding a prop to allow toggling wether or not the content on the single line gets truncated after a certain length, but decided to truncate by default for now. Happy to change this if anyone thinks truncation should be able to be toggled by default.
**Docs addition**
**With copy button**
**Without copy button**
=> feat(codeBlock): add useSingleLine prop

docs/components/badge.md, src/components/KBadge/KBadge.cy.ts, src/components/KBadge/KBadge.vue
Add styles for clickable `KBadge` items.
Addresses [KHCP-5737](https://konghq.atlassian.net/browse/KHCP-5737).
[KHCP-5738]: https://konghq.atlassian.net/browse/KHCP-5738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KHCP-5737]: https://konghq.atlassian.net/browse/KHCP-5737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(kbadge): add clickable prop [khcp-5737]

docs/.vitepress/theme/index.scss, docs/components/datetime-picker.md, docs/components/multiselect.md, docs/components/tree-list.md, src/components/KMultiselect/KMultiselect.cy.ts, src/components/KMultiselect/KMultiselect.vue, src/components/KMultiselect/KMultiselectItem.vue, src/components/KPop/KPop.vue
- Add support for item creation via `enableItemCreation` prop.
- Emit 2 new events `item:added` and `item:removed`.
- Add validation to confirm the uniqueness of item values.
- Addresses [KHCP-5569](https://konghq.atlassian.net/browse/KHCP-5569).
- Also changes behavior of `KPop` on `Enter` to always open the popover instead of toggling (hit `Esc` to close popover), this fixes an issue where hitting `Enter` would cause the KPop to show and then immediately hide itself.
[KHCP-5569]: https://konghq.atlassian.net/browse/KHCP-5569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(kmultiselect): allow item creation [khcp-5569]

docs/components/badge.md, src/components/KBadge/KBadge.vue
Needed to ensure that clicking on the "x" is does not also trigger the badge's `@click` listener
Bug explained by this screencap:
https://www.loom.com/share/d813c27a5367448fbcbc4ad00601ff81
Test the "Click Me!" example in this section
https://deploy-preview-1045--kongponents.netlify.app/components/badge.html#hovercolor
=> fix(kbadge): dismissable should not trigger @click [MA-1213]

docs/components/popover.md, docs/components/tooltip.md, src/components/KTooltip/KTooltip.cy.ts, src/components/KTooltip/KTooltip.vue
Ticket: https://konghq.atlassian.net/browse/KHCP-5756
All of these values from KPop should be included in the validator/accepted values in KTooltip
```ts
export const placements = {
auto: 'auto',
top: 'top',
topStart: 'top-start',
topEnd: 'top-end',
left: 'left',
leftStart: 'left-start',
leftEnd: 'left-end',
right: 'right',
rightStart: 'right-start',
rightEnd: 'right-end',
bottom: 'bottom',
bottomStart: 'bottom-start',
bottomEnd: 'bottom-end',
}
```
=> fix(ktooltip): add more placement options from kpop [KHCP-5756]

src/components/KPop/KPop.vue
This fixes the issue where other document click event listeners were not being fired because the stopPropagation() was always being called no matter what was the actual action of the click.
Most UI libraries use document-bound click listeners for execution optimization reasons, and this behavior caused them to not work anymore.
stopPropagation() should only be called when the click event is hiding the popper.
=> fix(kpop): stop document click event propagation only when event is about to hide popper

src/components/KCodeBlock/KCodeBlock.vue
I ran across an issue when using the `is-single-line` prop where the code block would extend beyond it's intended container:
For the fix itself, there seem to be a few workable options for the `grid-template-columns` value: `auto`, `100%` and `fit-content(100%)` all seem to work fine. I went with `auto`, but please let me know if one of the other options are better or if there is a different solution that would be more suitable.
=> fix(codeBlock): fix display styling

docs/components/tree-list.md, src/components/KTreeList/KTreeDraggable.vue, src/components/KTreeList/KTreeList.vue
https://konghq.atlassian.net/browse/KHCP-5950
Added `target` to be emitted upon `@change` and `@child-change` events in KTreeList
=> fix(ktreelist): emit target when firing each of @change and @child-change in KTreeList [KHCP-5950]

docs/components/tree-list.md, src/components/KTreeList/KTreeDraggable.vue, src/components/KTreeList/KTreeList.vue
Bubble up emit of `child-change` event for [KHCP-5980](https://konghq.atlassian.net/browse/KHCP-5980).
[KHCP-5980]: https://konghq.atlassian.net/browse/KHCP-5980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ktreelist): emit child-change event [khcp-5980]

docs/components/textarea.md, src/components/KTextArea/KTextArea.cy.ts, src/components/KTextArea/KTextArea.vue
Adds `is-resizable` prop to allow manually resizing of a textarea
=> feat(ktextarea): add prop to allow resizing of textarea

docs/components/multiselect.md, src/components/KBadge/KBadge.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KMultiselect/KMultiselectItem.vue, src/components/KSelect/KSelect.vue
Addresses:
[https://konghq.atlassian.net/browse/KHCP-5995](https://konghq.atlassian.net/browse/KHCP-5995)
Updates KMultiselect so that user can have an option of whether KBadge for an item should be dismissable or not.
=> fix(kmultiselect): dismissable badge [khcp-5995]

docs/components/codeblock.md, src/components/KCodeBlock/KCodeBlock.vue
* **fix(kcodeblock): not replacing all new lines in single line mode**
Fixes an issue with the code block component not replacing all new line characters when 
`props.isSingleLine` is `true`.
**Dev note**: With this change, it’s no longer necessary to set `white-space: nowrap` on the `code` element.
**Dev note**: Replaces access of `props.code` via optional chaining with direct access as `props.code` is required and of type `String`. It is not expected to ever be `undefined` or `null`.
**Dev note**: As an aside, it’s not required to special case the computation of `totalLines`; hence, the previous version of the computation was restored. It behaves correctly for the empty string, strings without new line characters, and strings with new line characters.
* **fix(kcodeblock): scrolling …
=> fix(kcodeblock): minor code block issues

docs/components/button.md, docs/components/dropdown-menu.md, src/components/KButton/KButton.vue, src/components/KDropdownMenu/KDropdownMenu.vue
Adds new `caretColor` prop to `KDropdownMenu` and `KButton` components.
=> fix(kdropdownmenu): allow customizing caret color

src/components/KCodeBlock/KCodeBlock.vue
Fixes an issue when you're rendering `HTML` inside of the code block. It would previously display the actual `div` if you entered a div tag for instance.
=> fix(kcodeblock): escape html tags in code block

src/components/KPrompt/KPrompt.vue
The divider in `KPrompt` has incorrect styles. On the documentation site, the problem won't occur because the divider is getting styles from vitepress:
Without vitepress it looks like this(the divider is darker than expected, and the prompt title is not vertically centered):
=> fix(kprompt): divider style

docs/components/multiselect.md, docs/components/select.md, src/components/KMultiselect/KMultiselect.cy.ts, src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.cy.ts, src/components/KSelect/KSelect.vue, src/styles/_utils.scss
Ticket: https://konghq.atlassian.net/browse/KHCP-6007
KSelect:
KMultiselect:
=> feat(kselect, kmultiselect): add dropdown footer text param and slot in KSelect and KMultiselect [KHCP-6007]

docs/components/badge.md
Vue components must be rendered on a separate line in the docs
=> docs(badge): render vue component on diff line

docs/components/datetime-picker.md, src/components/KDateTimePicker/KDateTimePicker.cy.ts, src/components/KDateTimePicker/KDateTimePicker.vue
https://konghq.atlassian.net/browse/MA-1410
The purpose of the Clear button has recently come into question on Analytics pages where we display Charts or Metrics.  The end user wants to see data displayed, not an empty chart.  Therefore, defaulting to hide the Clear Button.
=> fix(datetimepicker): allow hiding of clear button [MA-1410]

docs/components/select.md, src/components/KSelect/KSelect.cy.ts, src/components/KSelect/KSelect.vue
Ticket: https://konghq.atlassian.net/browse/KCGW-43
Slot for customizing selected item appearance.
`appearance="dropdown"` (default)
`appearance="select"`
Also disappears when `autosuggest` prop is `true`
`appearance="button"`
=> feat(kselect): add selected item slot [KHCP-6336]

src/components/KMenu/KMenuDivider.vue
Similar to https://github.com/Kong/kongponents/pull/1118, the divider in `KMenu` is also affected by vitepress style.
=> fix(kmenu): divider style

docs/components/select.md, src/components/KSelect/KSelect.cy.ts, src/components/KSelect/KSelect.vue
- fixes bug where placeholder doesn't appear when using `selected-item-template` slot && selection is empty
- adds `reuseItemTemplate` prop, which allows customizing selected item element without repeating code
=> feat(kselect): add reuse item template prop

docs/components/dropdown-menu.md, src/components/KDropdownMenu/KDropdownItem.vue, src/components/KDropdownMenu/KDropdownMenu.cy.ts
Fix an issue where the divider wasn't correctly rendering for each of the different item types.
=> fix(kdropdownmenu): divider display

src/components/KTable/KTable.vue
The previous logic was emitting the `update:table-preferences` event on component mount when the values were set instead of just upon user interaction.
=> fix(ktable): only emit table prefs when user changes

src/components/KDropdownMenu/KDropdownItem.vue
This PR fixes an expanded background bug when hovering on a `li` element with a nested `a.has-divider` element.
=> fix(kdropdownmenu): divider style

docs/components/table.md
Document KTable `sort` event for [KHCP-6539](https://konghq.atlassian.net/browse/KHCP-6539).
[KHCP-6539]: https://konghq.atlassian.net/browse/KHCP-6539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ktable): document `sort` event [KHCP-6539]

src/components/KTreeList/KTreeDraggable.vue
Trigger item selection when drag-n-drop is initiated to fix the issue of having difficulty triggering the selection event.
Addresses [KHCP-6355](https://konghq.atlassian.net/browse/KHCP-6355).
[KHCP-6355]: https://konghq.atlassian.net/browse/KHCP-6355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ktreelist): item selection [khcp-6355]

docs/components/skeleton.md, src/components/KSkeleton/FullScreenGenericSpinner.vue, src/components/KSkeleton/FullScreenKongSkeleton.vue, src/components/KSkeleton/KSkeleton.cy.ts, src/components/KSkeleton/KSkeleton.vue, src/styles/_mixins.scss
Adds a generic loading screen for the `KSkeleton` full screen loader, without the Kong gruceo branding.
=> feat(kskeleton): add a generic fullscreen spinner loader (TDX-2940)

docs/components/input-switch.md, src/components/KInputSwitch/KInputSwitch.vue
When labelPosition is left in KInputSwitch, use `position:relative` and `margin-left` on KIcon for proper positioning 
[KHCP-6412]
https://konghq.atlassian.net/browse/KHCP-6412
[KHCP-6412]: https://konghq.atlassian.net/browse/KHCP-6412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kinputswitch): fix position for enabledIcon in KInputSwitch with labelPosition left [KHCP-6412]

docs/components/multiselect.md, src/components/KMultiselect/KMultiselect.cy.ts, src/components/KMultiselect/KMultiselect.vue
Add support for seeing my selections when collapsed (like `expandSelections`), but still allowing for a maximum row count and collapsing extra entries into the `+n` badge.
Address [MA-1456](https://konghq.atlassian.net/browse/MA-1456).
[MA-1456]: https://konghq.atlassian.net/browse/MA-1456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(kmultiselect): collapsedContext [ma-1456]

src/types/dropdown-menu.ts
Adds `hasDivider` optional boolean type to `DropdownItem` so that it can be specified with a divider in `KDropdownItem`
=> fix(kdropdownitem): add hasDivider to KDropdownItem type [KHCP-6613]

docs/components/select.md, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue
Ticket: https://konghq.atlassian.net/browse/KHCP-6433
Before:
After:
=> fix(kselect): add white-space: nowrap; to item label [KHCP-6433]

docs/components/select.md, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue
Revert #1240 
This reverts commit ef81956fc8c232645b50f95add0aa91b697e1ec5.
=> revert(kselect): add white-space: nowrap; to item label [KHCP-6433]

docs/.vitepress/theme/_overrides.scss, docs/components/modal.md, docs/components/prompt.md
Document the differences between `KPrompt` and `KModal`.
=> feat(modals): doc differences prompt vs modal

docs/components/input.md, docs/components/label.md, docs/components/multiselect.md, docs/components/select.md, docs/components/textarea.md, src/components/KInput/KInput.cy.ts, src/components/KInput/KInput.vue, src/components/KLabel/KLabel.cy.ts, src/components/KLabel/KLabel.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.cy.ts, src/components/KSelect/KSelect.vue, src/components/KTextArea/KTextArea.cy.ts, src/components/KTextArea/KTextArea.vue, src/composables/useUtilities.cy.ts, src/composables/useUtilities.ts, src/styles/forms/_inputs.scss, src/styles/forms/_labels.scss, src/types/input.ts
**NOTE: This will require changes when adopting in `khcp-ui` to make sure we aren't showing duplicate asterisks anywhere!**
Adoption discussion in this [slack thread](https://kongstrong.slack.com/archives/CTAMPSTNX/p1681327020300829)
Add support for displaying an asterisk to indicate `required` state.
Addressed [KHCP-6528](https://konghq.atlassian.net/browse/KHCP-6528).
Support added for:
- KInput
- KLabel
- KMultiselect
- KSelect
- KTextarea
Doc updates:
- Added `Theming` section to `KLabel`
- Added `Attribute Bindings` section to `KTextarea`
[KHCP-6528]: https://konghq.atlassian.net/browse/KHCP-6528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(inputs): support required state [khcp-6528]

.github/workflows/test.yml, cypress.config.ts, cypress/support/index.ts, package.json, src/components/KCatalog/KCatalog.cy.ts, src/components/KDropdownMenu/KDropdownMenu.cy.ts, yarn.lock
Add the `cypress-fail-fast` plugin.
Note: this will not stop execution of all spec files, but will skip all remaining tests in a spec if one test in the spec fails.
=> test(component): enable fail fast

.github/workflows/test.yml
when PR preview publish fails - entire PR ci should fail
=> chore: catch and fail CI when PR preview publishing fails [KHCP-7061]

src/components/KTable/KTable.vue, src/types/table.ts
Return a typeof `any` for `row` and `column` slot props to prevent having to explicitly typecast in host applications. Also adds a column slot name type interface to properly resolve the slots in the template along with the corresponding slot props.
=> fix(KTable): loosen types passed to slots in KTable

src/components/KPop/KPop.vue
`KPop` with a two-word `placement` (e.g. `topStart `, `rightEnd `, etc.) has wrong position. This is observed in the `shared-ui-components` [CI](https://github.com/Kong/shared-ui-components/actions/runs/4762038683/jobs/8463884724?pr=760).
In `src/components/KPop/KPop.vue`, `this.placement` is a camel case string, but `new Popper()` expects the `placement` field to be a kebab case string. There used to be [a map](https://github.com/Kong/kongponents/blob/1b025bd36523001275908d95ef7bd1253d30cad2/src/components/KPop/KPop.vue#L125-L139) to do the case transformation, but it was removed in #1292.
Convert `placement` to kebab case before passing it to `new Popper()`.
=> fix(kpop): camel case placement

src/components/KModalFullscreen/KModalFullscreen.vue
Fixes KModalFullscreen header layout on small screen.
Before:
After:
=> fix(kmodalfullscreen): fix header layout on small screen

src/components/KLabel/KLabel.vue, src/styles/forms/_labels.scss
This PR fixes a bug that the help/info tooltip only appears when hovering over the `*` mark.
=> fix(klabel): tooltip trigger

src/components/KDateTimePicker/KDateTimePicker.vue
https://konghq.atlassian.net/browse/MA-1654
Deploy Preview:
https://deploy-preview-1339--kongponents.netlify.app/components/datetime-picker.html#custom-date-and-relative-time-frames
`max-width` property applied in kongponents was forcing the timepicker to expand to full width. This PR should fix things both in Kongponents and in consuming apps.
=> fix: revert datetimepicker popover to original width [MA-1654]

src/components/KDropdownMenu/KDropdownItem.vue, src/types/dropdown-menu.ts
Fixes an issue with KDropdownItem not registering KButton locally which causes the component to be treated as a plain custom element when Kongponents aren’t registered globally.
Fixes #1347.
=> fix(kdropdownitem): not registering KButton locally

docs/components/input.md, docs/components/label.md, src/components/KInput/KInput.cy.ts, src/components/KInput/KInput.vue, src/components/KLabel/KLabel.cy.ts, src/components/KLabel/KLabel.vue
Allow slotting a `KInput` label's tooltip content (also support at `KLabel` level) for [KHCP-7093](https://konghq.atlassian.net/browse/KHCP-7093).
[KHCP-7093]: https://konghq.atlassian.net/browse/KHCP-7093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(kinput): slot tooltip [khcp-7093]

src/components/KPagination/KPagination.vue
Order needs to be adjusted so that the styling from the CSS var is actually being used. Otherwise in its current order, the default color overrides it even if it is set.
=> fix(kpagination): change order so background color styling is applied

docs/components/multiselect.md, docs/components/select.md, docs/components/textarea.md, src/components/KInput/KInput.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.vue, src/components/KTextArea/KTextArea.vue
Add tooltip slot support to `KTextArea`, `KSelect`, and `KMultiselect`.
=> feat(inputs): add label tooltip slot support

docs/components/table.md, src/components/KTable/KTable.vue, src/composables/useUtilities.ts, src/types/table.ts
Provide the SWRV state information as a slot param for the `toolbar` slot to allow proper show/hide of that content.
- make `hasData` reactive so that we can correctly use it
- fix an issue where the empty state would flash after clearing search input
=> feat(ktable): provide swrv state in toolbar slot

docs/components/catalog.md, src/components/KCatalog/KCatalog.cy.ts, src/components/KCatalog/KCatalog.vue, src/components/KCatalog/KCatalogItem.vue, src/components/KTable/KTable.vue, src/types/catalog.ts
Add caching support for [KHCP-7309](https://konghq.atlassian.net/browse/KHCP-7309).
Includes:
- new prop `cacheIdentifier`
- new slot `cardActions` (will be needed for implementation in `khcp-ui`)
[KHCP-7309]: https://konghq.atlassian.net/browse/KHCP-7309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(kcatalog): swrv caching [khcp-7309]

docs/components/codeblock.md, src/components/KCodeBlock/KCodeBlock.vue
Adds an optional `secondary-actions` slot to `KCodeBlock`. It allows adding elements **after** the copy button (if it’s shown) or in its place (if it’s not shown).
=> feat(kcodeblock): adds secondary actions slot

docs/components/checkbox.md, docs/components/input.md, docs/components/radio.md, src/components/KCheckbox/KCheckbox.cy.ts, src/components/KCheckbox/KCheckbox.vue, src/components/KRadio/KRadio.cy.ts, src/components/KRadio/KRadio.vue, src/styles/forms/_checkbox-radio.scss
General cleanup / switch to `KLabel` for tooltip support for `KRadio` / `KCheckbox`.
Fixes:
- Cleanup reuse of v-model vars in docs
- Update docs - format is example followed by code snippet (not the reverse)
- Add `labelAttributes` prop for both components
- Add `tooltip` slot
- Add example usage of `description` slot
- Fix bug causing KRadio disabled styles not to be applied correctly
- Bind the label to the input using generated id's (and requiring `testMode` prop)
=> feat(kradio,kcheckbox): cleanup / support tooltip

.github/workflows/test.yml
Skips trying to publish a preview package if a package with the same version already exists. This is necessary in order to be able to re-run flaky tests.
Someone with better Shell foo should be looking over this
=> ci: skips preview publishing if version already exists

package.json, yarn.lock
`@arkweid/lefthook` has been renamed to `@evilmartians/lefthook` - updating to use new package.
=> chore(deps): replace lefthook with current package

src/components/KRadio/KRadio.vue
- Prevent activating the radio if clicked when disabled
- Moves the padding from the `.k-radio-card` element to the interior label in order to allow a user to click anywhere on the card to activate the radio.
=> fix(kradio): allow type=card entire element to be clickable

src/components/KMultiselect/KMultiselectItem.vue, src/components/KSelect/KSelectItem.vue
This PR fixes a bug that clicking the empty item in `KSelect` or `KMultiSelect` submits the form they're nested in.
Reproduction: https://codesandbox.io/s/select-in-form-forked-fnfwi4
=> fix(select): clicking empty item submits the form

src/components/KTable/KTable.vue
This PR fixes a bug that changing page sizes has no effect: 
`@event="() => handler"` will not actually call `handler` but just returns it.
=> fix(ktable): pagination event handlers

src/components/KPagination/KPagination.vue
**chore: ensures pagesVisible is list of number**
Changes `getVisiblePages` to return `[]` when `props.disablePageJump` is true instead of `0` allowing the function’s return type to be `number[]` instead of `number | number[]` which is likely unintentional seeing as `pageVisible` is used in a `v-for` directive. This silences the TypeScript error shown in the template related to this.
**fix(kpagination): kpopAttrs not being defined but used**
Adds `kpopAttrs` again which was lost in a previous refactoring. This ensures `placement: top` is passed to `KSelect` and silences the Vue warning appearing during development.
=> fix(kpagination): kpopAttrs not being defined but used

mocks/KTableMockData.ts, src/components/KTable/KTable.cy.ts
Addresses https://konghq.atlassian.net/browse/KHCP-7560
Adds missing test for the following scenarios:
- Data changes as expected when clicking a specific page number for non-offset pagination
- Data changes as expected when clicking arrows for offset based pagination
- Data changes as expected when pageSize is changed
- Data changes as expected when sort key or sort direction is changed and NOT using clientSideSort
=> fix(ktable): add missing test coverage for data changes as expected [KHCP-7560]

src/components/KSelect/KSelect.vue
Changes the local variable `iconSize` from `18` to `'18'` as it is used as the value for string prop which leads to the warning `Invalid prop: type check failed for prop "size". Expected String with value "18", got Number with value 18.`.
=> chore(kselect): fix passing size prop as number

src/components/KIcon/KIcon.vue
Restore the `inheritAttrs` setting in `KIcon`
=> fix(kicon): restore inheritAttrs setting

package.json, yarn.lock
Revert the `vue` dependency version to `3.2.47` until we're ready for `3.3.x`
=> revert(*): downgrade Vue to 3.2.x

.github/dependabot.yml, package.json, src/types/index.ts, yarn.lock
We're not ready for Vue 3.3 in host apps, so pin the Vue version
=> fix: pin vue version

docs/components/select.md, src/components/KSelect/KSelect.cy.ts, src/components/KSelect/KSelect.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-7555
Adds `enableItemCreation` prop to allow custom select item creation
=> feat(kselect): add enable-item-creation prop [KHCP-7555]

src/components/KSelect/KSelect.cy.ts, src/components/KSelect/KSelect.vue
`<KSelect>` with `enableItemCreation` should accept a previously created item as its value, otherwise there'll be a problem when editing an entity. Context: https://kongstrong.slack.com/archives/C04FLSMJ2ET/p1686726647993929.
=> fix(kselect): value when `enableItemCreation` is true

src/components/KCatalog/KCatalog.vue, src/components/KTable/KTable.vue
Fixes for [KHCP-7559](https://konghq.atlassian.net/browse/KHCP-7559).
- KCatalog doesn't react to page/pageSize change
- KTable/KCatalog don't reset to page 1 when searching
[KHCP-7559]: https://konghq.atlassian.net/browse/KHCP-7559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ktable/kcatalog): pagination + search [khcp-7559]

src/components/KSelect/KSelect.cy.ts, src/components/KSelect/KSelect.vue
This reverts commit 07eb8c6873d60fe5b7f5ec32ac057450cbe1fed1.
=> Revert "fix(kselect): value when `enableItemCreation` is true (#1460)"

src/components/KCatalog/KCatalog.vue, src/components/KSkeleton/CardSkeleton.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-5907
Fix `KCatalog` loading `KSkeleton` cards width.
Before
After
=> fix(kcatalog): fix loading skeleton cards width [KHCP-5907]

src/components/KTooltip/KTooltip.vue
Remove default `KPop` timeout from `KTooltip`
=> fix(ktooltip): remove kpop default timeout

.github/workflows/cleanup-preview-packages.yaml, .github/workflows/pr-closed.yml, .github/workflows/test.yml
- add job to cleanup PR preview version published 
- do not publish PR previews for dependabot originated PRs
=> feat: cron job to cleanup PR preview versions published [KHCP-7461]

docs/components/dropdown-menu.md, src/components/KDropdownMenu/KDropdownItem.vue
Fix `KDropdownMenu` to truncate button content when it extends beyond explicit set width.
Addresses [KHCP-7688](https://konghq.atlassian.net/browse/KHCP-7688).
[KHCP-7688]: https://konghq.atlassian.net/browse/KHCP-7688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kdropdownmenu): item truncation [khcp-7688]

src/components/KEmptyState/KEmptyState.vue
Changes the empty state component to only render container divs if the associated slots which don’t have fallback content are slotted in (e.g. if `title` is not slotted in, the component no longer renders an empty `.k-empty-state-title-header` div).
Changes the margins used to space out the individual parts of the empty state component to only apply if they make sense (e.g. the `message` slot will no longer have a large bottom margin if the CTA is hidden).
=> fix(kemptystate): unnecessary spaces and gaps

src/components/KEmptyState/KEmptyState.vue
Fixing a bug where the `cta` named slot renders nothing. This is caught in the `shared-ui-components` CI: https://github.com/Kong/shared-ui-components/actions/runs/5396449758/jobs/9800184704
=> fix(kemptystate): `cta` slot

src/components/KDropdownMenu/KDropdownItem.vue
https://konghq.atlassian.net/browse/KHCP-7907
increased line-height to prevent cutoff in KDropdownItem
=> fix(kdropdownitem): increase line-height to prevent cutoff in kdropdownitem [KHCP-7907]

docs/vite.config.ts, src/styles/_variables.scss, vite.config.ts
Refactor the design token imports so they are not exposed in the existing `dist/_variables.scss` file, which allows the `@kong/design-tokens` package to remain a `devDependency`.
Having the import directly in the `src/styles/_variables.scss` requires the package to be linked as a `dependency` for host applications as well since this file is being directly exported. 👎🏼 
**Note**: in the future breaking release, we should remove the `dist/_variables.scss` export as it should not be exposed.
=> fix(*): design token imports

src/components/KPagination/KPagination.vue
Fix [KHCP-7908](https://konghq.atlassian.net/browse/KHCP-7908) by watching for changes to `pageCount`.
[KHCP-7908]: https://konghq.atlassian.net/browse/KHCP-7908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kpagination): cache issue [khcp-7908]

docs/components/multiselect.md, src/components/KMultiselect/KMultiselectItem.vue
Always display the lock icon if a `KMultiselect` item is `disabled` (even if it's not `selected`) for [KHCP-7963](https://konghq.atlassian.net/browse/KHCP-7963).
Fix logic to not render a `KTooltip` if no `disabledTooltipText`.
[KHCP-7963]: https://konghq.atlassian.net/browse/KHCP-7963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kmultiselect): always show lock [khcp-7963]

.vscode/settings.json, package.json, yarn.lock
Update the `@kong/design-tokens` package and adjust the SCSS intellisense plugin settings to not exclude `node_modules`
=> fix(scss): autocompletion

src/components/KCatalog/KCatalog.cy.ts, src/components/KCatalog/KCatalog.vue
Fix flakey `KCatalog` component test for [KHCP-7022](https://konghq.atlassian.net/browse/KHCP-7022).
[KHCP-7022]: https://konghq.atlassian.net/browse/KHCP-7022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kcatalog): flakey test [khcp-7022]

src/components/KMultiselect/KMultiselect.vue, src/components/KTruncate/KTruncate.vue
https://konghq.atlassian.net/browse/KHCP-7734
Disable Uncaught "ResizeObserver loop limit exceeded" error
=> fix(KTruncate, KMultiselect): add fix for ResizeObserver [KHCP-7734]

docs/components/input.md
https://konghq.atlassian.net/browse/KHCP-7360
Add nested label attributes examples to KInput documentation
=> docs(KInput): add tooltipAttributes description and example [KHCP-7360]

.github/CODEOWNERS, docs/components/badge.md, src/components/KBadge/KBadge.vue, src/styles/_mixins.scss, src/types/badge.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-7694
Changes:
- introduce `kui-` design tokens in `KBadge` component
- break down usage of Kongponents utility classes in `KBadge` component template AND in documentation markdown file
=> feat(kbadge): introduce kui tokens [KHCP-7694]

src/components/KCodeBlock/KCodeBlock.vue
Fixes not showing the correct number of matching lines. Since cycling through matches happens on a line by line basis (i.e. we don’t jump to one line containing multiple matches once per match but only once per matching line), we should also show the number of results in relation to matched lines.
=> fix(kcodeblock): not showing correct number of matching lines

docs/components/breadcrumbs.md, src/components/KBreadcrumbs/KBreadcrumbs.cy.ts, src/components/KBreadcrumbs/KBreadcrumbs.vue
Add new `divider` slot for KBreadcrumb for page header update.
Part of [KHCP-8092](https://konghq.atlassian.net/browse/KHCP-8029).
=> feat(kbreadcrumb): custom divider [khcp-8029]

src/components/KModal/KModal.vue
https://konghq.atlassian.net/browse/KHCP-7758
Fix `Your focus-trap must have at least one container with at least one tabbable node in it at all times` DD error
=> fix(KModal): fix focusTrap error [KHCP-7758]

src/components/KSelect/KSelect.vue
https://konghq.atlassian.net/browse/KHCP-7756
Fix `TypeError: Cannot read properties of null (reading 'length')` error
=> fix(KSelect): add pre-check presence for selectItems.value  [KHCP-7756]

.github/CODEOWNERS, docs/components/input.md, package.json, src/components/KInput/KInput.vue, src/styles/forms/_inputs.scss, yarn.lock
Addresses: https://konghq.atlassian.net/browse/KHCP-7709
Changes:
- introduces `kui-` design tokens in `KInput` component
- removes any usage of Kongponents utility classes in `KInput` component template (none found)
=> feat(kinput): introduce kui tokens [KHCP-7709]

src/components/KAlert/KAlert.vue, src/components/KBadge/KBadge.vue, src/components/KButton/KButton.vue, src/components/KDateTimePicker/KDateTimePicker.vue, src/components/KTable/KTable.vue
Fixes icon size in Kongponents that were completed prior to introduction of `kui-icon-size-*` tokens
=> fix(*): fix icon size in components with design tokens

.github/CODEOWNERS, src/components/KPrompt/KPrompt.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-7719
Changes:
- introduces `kui-` design tokens in `KPrompt` component
- removes any usage of Kongponents utility classes in `KPrompt` component template
=> feat(kprompt): introduce kui tokens [KHCP-7719]

.github/CODEOWNERS, src/components/KTextArea/KTextArea.vue, src/styles/_mixins.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-7728
Changes:
- introduces `kui-` design tokens in `KTextArea` component
- removes any usage of Kongponents utility classes in `KTextArea` component template
=> feat(ktextarea): introduce kui tokens [KHCP-7728]

.github/CODEOWNERS, docs/components/dropdown-menu.md, src/components/KDropdownMenu/KDropdownItem.vue, src/components/KDropdownMenu/KDropdownMenu.vue, src/types/dropdown-menu.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-7703
Changes:
- introduces `kui-` design tokens in `KDropdownMenu` component
- removes any usage of Kongponents utility classes in `KDropdownMenu` component template (none found)
=> feat(kdropdownmenu): introduce kui tokens [KHCP-7703]

.github/CODEOWNERS, docs/components/file-upload.md, src/components/KAlert/KAlert.vue, src/components/KEmptyState/KEmptyState.vue, src/components/KFileUpload/KFileUpload.vue, src/styles/_tmp-variables.scss, src/styles/forms/_inputs.scss, src/styles/forms/_labels.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-7706
Changes:
- introduces `kui-` design tokens in `KFileUpload` component
- removes any usage of Kongponents utility classes in `KFileUpload` component template
=> feat(kfileupload): introduce kui tokens [KHCP-7706]

.github/CODEOWNERS, src/components/KRadio/KRadio.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-7720
Changes:
- introduces `kui-` design tokens in `KRadio` component
- removes any usage of Kongponents utility classes in `KRadio` component template
=> feat(kradio): introduce kui tokens [KHCP-7720]

src/components/KBreadcrumbs/KBreadcrumbs.vue
Properly adjusts the line-height of the icon divider to respect the `align-items: center` rule to fix the vertical alignment.
=> fix(kbreadcrumbs): divider line height

docs/components/breadcrumbs.md, src/components/KBadge/KBadge.cy.ts, src/components/KBreadcrumbs/KBreadcrumbs.cy.ts, src/components/KBreadcrumbs/KBreadcrumbs.vue, src/types/breadcrumbs.ts
KBreadcrumb style updates for [KHCP-8029](https://konghq.atlassian.net/browse/KHCP-8029).
Adds `emphasis` prop, divider slot, and support for breadcrumb item's that are not a link.
Figma: https://www.figma.com/file/8k70HMMdPj98APLaexYJyR/Header?type=design&node-id=11%3A7494&mode=dev
[KHCP-8029]: https://konghq.atlassian.net/browse/KHCP-8029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(kbreadcrumb): style updates [khcp-8029]

.github/CODEOWNERS, docs/components/method-badge.md, src/components/KMethodBadge/KMethodBadge.vue, src/types/method-badge.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-7713
Changes:
- introduces `kui-` design tokens in `KMethodBadge` component
- removes any usage of Kongponents utility classes in `KMethodBadge` component template (none found)
=> feat(kmethodbadge): introduce kui tokens [KHCP-7713]

.github/CODEOWNERS, docs/components/icon.md, src/components/KIcon/KIcon.vue
Addresses https://konghq.atlassian.net/browse/KHCP-7707
Changes:
- introduces `kui-` design tokens in `KIcon` component
- removes any usage of Kongponents utility classes in `KIcon` component template (none found)
=> feat(kicon): introduce kui tokens [KHCP-7707]

.github/CODEOWNERS, docs/components/inline-edit.md, src/components/KInlineEdit/KInlineEdit.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-7708
Changes:
- introduces `kui-` design tokens in `KInlineEdit` component
- removes any usage of Kongponents utility classes in `KInlineEdit` component template
=> feat(kinlineedit): introduce kui tokens [KHCP-7708]

src/components/KBreadcrumbs/KBreadcrumbs.vue
Change default color of divider slot content from teal to grey. No visible to changes to docs site.
=> fix(kbreadcrumbs): default divider color

.github/CODEOWNERS, docs/components/truncate.md, src/components/KTruncate/KTruncate.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-7732
Changes:
- introduces `kui-` design tokens in `KTruncate` component
- removes any usage of Kongponents utility classes in `KTruncate` component template
=> feat(ktruncate): introduce kui tokens [KHCP-7732]

.github/CODEOWNERS, docs/components/tree-list.md, src/components/KTreeList/KTreeDraggable.vue, src/components/KTreeList/KTreeItem.vue, src/components/KTreeList/KTreeList.vue, src/styles/_tmp-variables.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-7731
- introduces `kui-` design tokens in `KTreelist` component
- removes any usage of Kongponents utility classes in `KTreelist` component template
=> feat(ktreelist): tokenization [khcp-7731]

.github/CODEOWNERS, docs/components/menu.md, src/components/KMenu/KMenu.vue, src/components/KMenu/KMenuDivider.vue, src/components/KMenu/KMenuItem.vue, src/styles/_tmp-variables.scss
https://konghq.atlassian.net/browse/KHCP-7712
**Changes:**
- introduces `kui-` design tokens in `KMenu`, `KMenuDivider`, and `KMenuItem` component
- removes any usage of Kongponents utility classes in `KMenu`, `KMenuDivider`, and `KMenuItem` component template
=> feat(kmenu): introduce kui tokens [KHCP-7712]

docs/components/breadcrumbs.md, src/components/KBreadcrumbs/KBreadcrumbs.cy.ts, src/components/KBreadcrumbs/KBreadcrumbs.vue
Add icon slot for each breadcrumb (needed for Runtime Manager breadcrumbs).
=> feat(kbreadcrumb): add icon slot

.github/CODEOWNERS, docs/components/tooltip.md, src/components/KTooltip/KTooltip.vue
https://konghq.atlassian.net/browse/KHCP-7730
**Changes:**
- introduces `kui-` design tokens in `KTooltip` component
- removes any usage of Kongponents utility classes in `KTooltip` component template
=> feat(ktooltip): introduce kui tokens [KHCP-7730]

src/components/KCard/KCard.vue
Fixes the line-height of table cells nested inside a KCard body. Currently, the `font-size` and `line-height` will be the same pixel value (16px) unless overridden.
=> fix(kcard): body line-height in table cells

src/styles/_utils.scss
Fix line height issue for truncating texts.
=> fix(style): line height for truncate

src/styles/_variables.scss
Update the default font family variables.
=> fix(*): update fcont family scss vars

.github/CODEOWNERS, docs/components/stepper.md, src/components/KStepper/KStep.vue, src/components/KStepper/KStepState.vue, src/components/KStepper/stepper-icons/KActiveState.vue, src/components/KStepper/stepper-icons/KCompletedState.vue, src/components/KStepper/stepper-icons/KDefaultState.vue, src/components/KStepper/stepper-icons/KErrorState.vue, src/components/KStepper/stepper-icons/KPendingState.vue, src/styles/_tmp-variables.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-7725
Changes:
- introduces `kui-` design tokens in `KStepper` component
- removes any usage of Kongponents utility classes in `KStepper` component template
=> feat(kstepper): introduce kui tokens [KHCP-7725]

.github/CODEOWNERS, docs/components/skeleton.md, src/components/KSkeleton/CardSkeleton.vue, src/components/KSkeleton/FormSkeleton.vue, src/components/KSkeleton/FullScreenGenericSpinner.vue, src/components/KSkeleton/FullScreenKongSkeleton.vue, src/components/KSkeleton/KSkeleton.vue, src/components/KSkeleton/KSkeletonBox.vue, src/components/KSkeleton/TableSkeleton.vue, src/styles/_tmp-variables.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-7723
Changes:
- introduces `kui-` design tokens in `KSkeleton` component
- removes any usage of Kongponents utility classes in `KSkeleton` component template
=> feat(kskeleton): introduce kui tokens [KHCP-7723]

docs/components/catalog.md, src/components/KCatalog/KCatalog.cy.ts, src/components/KCatalog/KCatalog.vue, src/components/KCatalog/KCatalogItem.vue
Add an event emission for when a `KCatalogItem` is clicked.
=> feat(kcatalog): emit on card click

src/components/KMultiselect/KMultiselectItems.vue, src/components/KSelect/KSelectItems.vue
https://konghq.atlassian.net/browse/KHCP-8828
Fix DD error [https://app.datadoghq.com/rum/error-tracking?query=%40application.id%3A6e430333-9e0f-4d6b-ac63-5f7d4ad9a641 env%3Aprod -%40browser.name%3AHeadlessChrome %40issue.age%3A<%3D300000&issueId=bed92134-467c-11ee-9f79-da7ad0900002&from_ts=1693320929000&to_ts=1693321229000&live=false](https://app.datadoghq.com/rum/error-tracking?query=%40application.id%3A6e430333-9e0f-4d6b-ac63-5f7d4ad9a641%20env%3Aprod%20-%40browser.name%3AHeadlessChrome%20%40issue.age%3A%3C%3D300000&issueId=bed92134-467c-11ee-9f79-da7ad0900002&from_ts=1693320929000&to_ts=1693321229000&live=false)
=> fix(KSelect): add optional chaining for props.items [KHCP-8828]

src/components/KMultiselect/KMultiselect.cy.ts, src/components/KMultiselect/KMultiselect.vue
Issues observed with `<MultiSelect />`:
1. Excessive calls to `stageSelections()`. The current implementation schedules `items.length` macro tasks while `items` changed, leading to forced DOM reflows due to frequent access to `clientHeight`, and multiple changes to `stagingKey`.
2. The current strategy to prevent item container flickering involves the use of an offscreen div to gauge the maximum number of pills it can accommodate. This involves populating the pills and checking for remaining space sequentially, leading to a fixed `len(selected)` times DOM updates. Large selected items adversely affect performance.
Optimizations:
- Moved `stageSelections()` outside the loop to schedule only a single task post processing of all items.
- Modified the pill measurement strategy to maximize …
=> fix(multi-select): optimize overflow detection for selected items container

src/components/KCodeBlock/KCodeBlock.vue
Fixes the code block’s slotted content not getting the styles intended for it. This was caused in parts by some selectors being wrong (`.k-code-block .theme-dark .k-button` won’t ever match because `.theme-dark` is a class on `.k-code-block`, not one of its descendants) and in parts by some styles being in the scoped style block which won’t apply to slotted content.
=> fix(kcodeblock): dark theme not applying to slotted content of code block

src/components/KCodeBlock/KCodeBlock.vue
Fixes the code block’s slotted content not getting the styles intended for it. This was caused in parts by some selectors being wrong (`.k-code-block .theme-dark .k-button` won’t ever match because `.theme-dark` is a class on `.k-code-block`, not one of its descendants) and in parts by some styles being in the scoped style block which won’t apply to slotted content.
This is a copy of https://github.com/Kong/kongponents/pull/1719 which was merged into `alpha` previously.
=> fix(kcodeblock): dark theme styles not applying to slotted content

src/components/KEmptyState/KEmptyState.vue
Fixes KEmptyState rendering an empty `.k-empty-state-cta` element when `props.ctaIsHidden` is set.
This was previously fixed in #1474 but that change introduced the issue that content slotted into `cta` was hidden except if `props.ctaText` was set.
In #1486 that regression was fixed, but that change also undid the fix to rendering an empty `.k-empty-state-cta` element if no CTA was to be shown.
This change makes sure that the element is rendered if (1) the `cta ` slot is provided or (2) `props.ctaIsHidden` is `false` and `props.ctaText` is provided.
=> fix(kemptystate): rendering empty cta element

src/components/KBadge/KBadge.vue
Fixes KBadge being able to receive focus when it’s not interactive. It now will only have `tabindex="0"` if a `click` handler is present.
Removes `tabindex="0"` from KBadge’s dismiss button if `props.hidden` isn’t true. Setting `tabindex="0"` is unnecessary as KButton is already focusable by virtue of being a button.
=> fix(kbadge): non-interactive badge being focusable

src/components/KCodeBlock/KCodeBlock.vue
Fixes a bug with the code block not resetting its currently matched line UI when updating the query which led to the UI showing text like "4 of 1".
=> fix(kcodeblock): not resetting current match on query change

src/components/KCodeBlock/KCodeBlock.vue
Changes the style of buttons inside the code block to have borders in the light theme.
=> fix(kcodeblock): buttons not being bordered in light theme

src/components/KTabs/KTabs.vue
Removes the `.k-tabs ul .tab-item:after` pseudo element styles as they don’t seem to have a clear purpose and interfere with rendering of KTabs within overflowing containers.
=> chore(ktabs): removes unnecessary pseudo element

docs/components/button.md, docs/components/tooltip.md, src/components/KTooltip/KTooltip.cy.ts, src/components/KTooltip/KTooltip.vue
Hide the tooltip popover if no `label` prop or `content` slot template is provided.
=> feat(ktooltip): hide tooltip if no label or content

docs/components/tooltip.md, src/components/KLabel/KLabel.vue, src/components/KTooltip/KTooltip.vue
Remove slot wrapper div and add `tabindex` to label tooltip trigger icon
=> fix(ktooltip, klabel): remove tooltip slot wrapper

docs/components/dropdown.md, docs/components/input.md, docs/components/table.md, docs/guide/contributing.md, docs/guide/migrating-to-version-9.md, package.json, sandbox/pages/SandboxDropdown.vue, sandbox/pages/SandboxInput.vue, sandbox/pages/SandboxTable.vue, src/components/KDropdown/KDropdown.cy.ts, src/components/KDropdown/KDropdown.vue, src/components/KDropdown/KDropdownItem.vue, src/components/KFileUpload/KFileUpload.vue, src/components/KInput/KInput.cy.ts, src/components/KInput/KInput.vue, src/components/KRadio/KRadio.vue, yarn.lock
Addresses: https://konghq.atlassian.net/browse/KHCP-9548
Changes:
- `KInput`:
- deprecate `hasError` prop in favor of `error`
- update underlying class structure to match the change
- `KDropdown`:
-  change `isSelectionMenu` prop to `selectionMenu`
- `KDropdownItem`:
- deprecate `isDangerous` prop in favor of `danger`
=> fix(*): deprecate and update boolean props [KHCP-9548]

src/components/KCodeBlock/KCodeBlock.vue
Removes the limitation to only trigger a search when (1) a piece of code is shorter than 1000 characters or (2) the query is greater than 2 characters.
=> fix(kcodeblock): not searching long content with short queries

docs/guide/migrating-to-version-9.md, sandbox/pages/SandboxLabel.vue, src/components/KCheckbox/KCheckbox.vue, src/components/KInput/KInput.vue, src/components/KLabel/KLabel.vue, src/components/KRadio/KRadio.vue, src/types/input.ts
Instead of removing `help` prop in `KLabel`, deprecate it for backwards compatibility.
=> fix(*): deprecate klabel help prop

src/components/KTooltip/KTooltip.cy.ts, src/components/KTooltip/KTooltip.vue
This PR removes KPop entirely if no label or content is provided. Instead, it'll only render the default slot.
Before:
After:
=> feat(ktooltip): render a plain slot if no label or content

docs/components/codeblock.md, src/components/KCodeBlock/KCodeBlock.vue
Assigns Enter to the "Jump to next match" action.
Assigns Shift+Enter to the "Jump to previous match" action.
=> feat(kcodeblock): assign Enter to jump to next match action

docs/components/codeblock.md, src/components/KCodeBlock/KCodeBlock.cy.ts, src/components/KCodeBlock/KCodeBlock.vue
Adds the new optional `props.initialFilterMode` and `props.initialRegExpMode` which both default to `false`. They control whether filter and regular expression mode are initially active. These props can be used to initialize a code block with some state stored in the application (e.g. via URL query parameters or client-side storage).
Adds the new optional events `filter-mode-change` and `reg-exp-mode-change` which both emit a boolean value representing whether filter and regular expression mode are currently active. These events can be used to persist the modes in the application’s state so that they can later been restored using `props.initialFilterMode` and `props.initialRegExpMode`.
=> feat(kcodeblock): add filter and regexp mode props and events

src/components/KTable/KTable.vue
Ensure KTable does not render the CTA button if the `emptyStateActionMessage` is empty
=> fix(ktable): hide empty state cta if no text

src/components/KSelect/KSelect.vue
Minor spacing fix for KSelect button appearance
=> fix(kselect): button appearance spacing

docs/components/select.md, docs/components/textarea.md, src/components/KCopy/KCopy.vue, src/components/KPrompt/KPrompt.vue
Temporary fix for KPrompt body spacing cutting off input focus ring (permanent fix will be implemented during component reskin)
=> fix(kprompt): body spacing fix

src/components/KDropdown/KDropdown.cy.ts, src/components/KDropdown/KDropdownItem.vue
Removes `disabled` class from `.dropdown-item-trigger` element in `KDropdownItem`
=> fix(kdropdownitem): remove disabled class

src/components/KPagination/KPagination.vue
Changes the KSelect’s `props.width` value from `170` to `190` to account for the widest default content (i.e. "100 items per page"). This otherwise triggers the pagination to overflow (e.g. causes a horizontal scrollbar in KTable).
Before:
After:
=> fix(kpagination): select widget too thin for wide content

src/components/KSlideout/KSlideout.vue
Fixes the content area always as tall as the viewport when using `props.offsetTop` making it too tall.
=> fix(kslideout): content being taller than viewport when using props.offsetTop

src/components/KDropdown/KDropdown.cy.ts, src/components/KDropdown/KDropdownItem.vue
Add disabled class and remove the disabled attribute on KDropdownItem link types
=> fix(kdropdownitem): add disabled class on links

docs/components/input.md, docs/components/textarea.md, docs/guide/migrating-to-version-9.md, sandbox/index.ts, sandbox/pages/SandboxInput.vue, sandbox/pages/SandboxTextarea.vue, sandbox/router/sandbox-routes.ts, src/components/KInput/KInput.cy.ts, src/components/KInput/KInput.vue, src/components/KLabel/KLabel.cy.ts, src/components/KLabel/KLabel.vue, src/components/KTextArea/KTextArea.cy.ts, src/components/KTextArea/KTextArea.vue, src/styles/mixins/_input-text.scss
[Jira](https://konghq.atlassian.net/browse/KHCP-9004)
[Figma](https://www.figma.com/file/Yze0SWXl5nKjR0rFdilljK/Components?type=design&node-id=737%3A10936&mode=dev)
KTextarea component reskinning.
Links:
- [Kongponents sandbox](https://deploy-preview-1826--kongponents-sandbox.netlify.app/#/textarea)
- [Kongponents docs preview](https://deploy-preview-1826--kongponents.netlify.app/components/textarea.html)
=> fix(ktextarea): reskin component [KHCP-9004]

src/components/KTable/KTable.vue
When `sortColumnKey` is changed, the `offsets` array needs to be reset to avoid using the previous `offset` of the old sort key.
=> fix(ktable): reset offsets after sort key changes

package.json, yarn.lock
This PR upgrades `axios` to address [a CSRF issue](https://github.com/Kong/kong-admin/security/dependabot/169) and moves it from `dependencies` to `devDependencies` as we are only using some of its types.
=> chore: upgrade axios

src/components/KSelect/KSelect.vue
This resolves an issue where sometimes the selectedItems can have duplicate `selected = true` state.
Essentially you have reactive `items` value that can look like this:
```json
[
{
"value": "b81af73c-a556-446a-a0a3-16980a791e12",
"label": "v1",
"selected": true
},
{
"value": "cd026175-cafa-46b0-b269-4a40c1f79b68",
"label": "v2",
"selected": false
},
{
"value": "10cb8ed7-d0a4-409b-89a6-551df65e8963",
"label": "v3",
"selected": false
}
]
```
Next you update the props to be as follows:
```json
[
{
"value": "b81af73c-a556-446a-a0a3-16980a791e12",
"label": "v1",
"selected": false
},
{
"value": "cd026175-cafa-46b0-b269-4a40c1f79b68",
"label": "v2",
"selected": false
},
{
"value": "10cb8ed7-d0a4-409b-89a6-551df65e8963",
"label": "v3",
"selected": true
}
]
```
On the second loop, [Line …
=> fix: kselect selectedItem should reset to null

src/components/KSelect/KSelect.vue
This PR fixes a bug where extra `query-change` events are fired after the user clicks on an item in autosuggest mode, making the item lose its "selected" status (because in the `query-change` event handler of the autosuggest select, users will fetch new `items` based on user input, which will then trigger the `props.items` watcher and [set `selectedItem.value` to null](https://github.com/Kong/kongponents/blob/27e460f6460dfdf299bd279c44664a77874d1deb/src/components/KSelect/KSelect.vue#L718)).
Before the fix:
After the fix:
=> fix(kselect): autosuggest query

src/styles/mixins/_input-text.scss
The `KInput` is missing the `box-sizing` property, meaning the element's padding will cause it to exceed it's container's width
=> fix(kinput): add box-sizing rule

src/components/KTable/KTable.vue
This PR fixes an empty button in the `cta` slot when `errorStateActionMessage` is not passed to `<KTable>`. As a reference, this is how we handle `emptyStateActionMessage`: https://github.com/Kong/kongponents/blob/93397a42ccbfb05cd2d922d66934ae4bbfb1a501/src/components/KTable/KTable.vue#L76-L89 
The `main` branch does not have this problem.
=> fix(ktable): error state CTA

src/components/KTable/KTable.vue
Add `.truncate` class styles in `th` and `td` elements
=> fix(ktable): add truncate class styles

src/components/KCopy/KCopy.vue
**fix(kcopy): icon having left margin when format is hidden**
Fix an issue when using KCopy’s `props.format` being set to `'hidden'` that adds an unnecessary left margin to the icon even though no text is shown.
**chore(kcopy): remove unused styles**
**fix(kcopy): rendering badgeLabel content when badgeLabel isn’t set**
- This slightly narrows the gap between text and copy icon when using `props.badge` on account of `.truncate-content` adding a right marging and `.text-icon-wrapper` adding a left margin. It seems like this gap is unintentionally big currently.
- There is one more instance in KCopy where using `gap` on a container would be a more robust strategy to create space between elements: `.copy-badge-text`. I left this …
=> fix(kcopy): icon having left margin when format is hidden

src/components/KSlideout/KSlideout.vue
Fix an issue with long, non-wrapping titles not truncating and triggering a horizontal scrollbar in the content area.
| Before | After |
| ------ | ----- |
| ![image](https://github.com/Kong/kongponents/assets/5774638/b79edd26-0511-47d9-89d5-43b9465ea602) | ![image](https://github.com/Kong/kongponents/assets/5774638/1d55b9f8-9fa4-4f7b-9627-d95e9770867a) |
=> fix(kslideout): long titles not truncating

docs/components/copy.md, sandbox/index.ts, sandbox/pages/SandboxCopy.vue, sandbox/router/sandbox-routes.ts, src/components/KBadge/KBadge.vue, src/components/KCopy/KCopy.vue, src/styles/_vars.scss, src/styles/mixins/_badges.scss
[Jira](https://konghq.atlassian.net/browse/KHCP-9663)
`KCopy` component reskin
Links:
- [Kongponents sandbox](https://deploy-preview-1925--kongponents-sandbox.netlify.app/#/copy)
- [Kongponents docs preview](https://deploy-preview-1925--kongponents.netlify.app/components/copy.html)
=> feat(kcopy): reskin component [KHCP-9663]

docs/guide/migrating-to-version-9.md, sandbox/pages/SandboxSelect.vue, src/components/KSelect/KSelect.vue
Use standalone KLabel and help text elements in KSelect to fix absolutely positioned element (custom item) taking up full height (screenshot)
=> fix(kselect): fix klabel and help text elements

src/components/KSelect/KSelect.vue
Fixes:
1. We clear selected items to then find it again in the items array, however if items is empty we still want to have the selected item that’s set through `v-model`
2. Hide input placeholder when custom selected item is visible
=> fix(kselect): do not clear selected item when items empty

docs/components/modal.md, docs/components/multiselect.md, docs/guide/migrating-to-version-9.md, src/components/KMultiselect/KMultiselect.vue, src/styles/mixins/_badges.scss, src/types/multi-select.ts
Changes:
* KMultiselect: rename `MultiselectFilterFnParams` type to `MultiselectFilterFunctionParams` to match KSelect
* KBadge: modify hover selector (to avoid applying hover styles to badge content when badge has tooltip which applies `role="button"` attribute under the hood)
=> fix(*): phase 4 misc fixes

sandbox/pages/SandboxInputSwitch.vue, sandbox/pages/SandboxTabs.vue, src/components/KInputSwitch/KInputSwitch.vue, src/components/KTabs/KTabs.vue
Fixes:
- removes `tabindex` attribute from KTabs panel container
- adds padding top to fix cutoff
- fixes `transition` property invalid value
=> fix(ktabs): remove panel tabindex, add padding top

src/components/KTabs/KTabs.vue
fix(ktabs): padding not assigned to tab content when using hidePanels
Restores the padding being assigned to a tab’s content instead of the tab itself when using `props.hidePanels`.
fix(ktabs): layout shift when clicking tabs
Fixes a layout shift when clicking tabs that was caused by transitioning between `border-bottom: none` and `border-bottom: 2px ...`.
Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com
=> fix(ktabs): tab click target being too small when using hide panels

docs/components/dropdown.md, src/components/KDropdown/KDropdown.cy.ts, src/components/KDropdown/KDropdown.vue, src/components/KDropdown/KDropdownItem.vue, src/components/KInput/KInput.vue, src/components/KPagination/KPagination.vue, src/components/KTabs/KTabs.vue
Adds selected item styling to KDropdown selectionMenu selected item
Before (selected item in not distinct from other items in the dropdown)
After (selected item has different background and text color, following the pattern established in KSelect and KMultiselect)
=> fix(kdropdown): selection menu item selected state style

src/components/KTabs/KTabs.vue
Adds `margin-top: 0;` to KTabs `ul role=tablist` element
=> fix(ktabs): add margin top 0

docs/components/button.md, docs/components/copy.md, sandbox/pages/SandboxCopy.vue, src/components/KCopy/KCopy.vue
KCopy:
* expose `triggerCopy` method to allow executing copy action from outside the component
* tweak styling to take hover color set by KButton when KCopy is a child of KButton
=> fix(kcopy): expose copy method, tweak hover in kbutton

src/components/KSegmentedControl/KSegmentedControl.vue
Add `type="button"` on KSegmentedControl button to prevent submit in case component is used within a form
=> fix(ksegmentedcontrol): add type button

src/components/KButton/KButton.vue
Clicking then releasing and moving away from a `KButton` without a subsequent DOM re-render leaves the KButton in its darker 'focus' state.
This PR changes some selectors to use `:focus-visible` over just `:focus` to keep the desired coloring when the browser heuristics have decided that the button should look focused, but doesn't apply them otherwise.
I'm pretty sure this is the correct way to do this going from reading:
> For instance, when a button is clicked using a pointing device, the focus is generally not visually indicated, but when a text box needing user input has focus, focus is indicated. While focus styles are always required when users are navigating the page with the keyboard or when focus is managed via scripts, focus styles are not required when the user knows where they …
=> fix(kbutton): fix unfocusing of kbutton

sandbox/index.ts, src/index.ts
Export a `components` object in order to loop through available components in a host app.
=> fix: export components object

src/types/dropdown.ts
Add `danger?: boolean` property to `DropdownItem` interface
=> fix(ts): add danger property to dropdown item interface

docs/components/dropdown.md, docs/components/tooltip.md, docs/guide/migrating-to-version-9.md, sandbox/pages/SandboxDropdown.vue, src/components/KCopy/KCopy.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KTooltip/KTooltip.cy.ts, src/components/KTooltip/KTooltip.vue
[Figma](https://www.figma.com/file/Yze0SWXl5nKjR0rFdilljK/Components?type=design&node-id=1134%3A13064&mode=dev&t=eq1kZMLAvXixR9vC-1)
[Jira](https://konghq.atlassian.net/browse/KHCP-9007)
`KTooltip` component reskin
Links:
- [Kongponents docs preview](https://deploy-preview-1988--kongponents.netlify.app/components/tooltip.html)
=> feat(ktooltip): reskin component styles [KHCP-9007]

docs/guide/migrating-to-version-9.md, sandbox/pages/SandboxDateTimePicker.vue, src/components/KDateTimePicker/KDateTimePicker.cy.ts, src/components/KDateTimePicker/KDateTimePicker.vue, src/styles/mixins/_input-text.scss
Issue: we want KDateTimePicker to wrap to next line when a range is selected and the space is either too narrow (like on smaller screens). Because KInput which the component utilizes under the hood won't allow wrapping, we need to use a `div role="button"` styled like KInput.
Before
After
=> fix(kdatetimepicker): fix wrapping in timepicker display

docs/components/truncate.md, docs/guide/migrating-to-version-9.md, src/components/KTruncate/KTruncate.cy.ts, src/components/KTruncate/KTruncate.vue
Jira: https://konghq.atlassian.net/browse/KHCP-9009
`KTruncate` component reskin
=> feat(ktruncate): reskin component [KHCP-9009]

src/styles/mixins/_input-text.scss
Updates readonly KInput styles to make them more accessible
=> fix(kinput): update readonly styles [KHCP-10785]

docs/components/toaster.md, sandbox/pages/SandboxToaster.vue, src/components/KToaster/KToaster.vue, src/components/KToaster/ToastManager.ts, src/types/toaster.ts
Changes:
* title becomes optional
* when only argument provided to `ToastManager.open()` is string - treat it like message
* styling tweaks displaying icon, title and message
=> fix(ktoaster): icon, title and message styling

docs/components/codeblock.md, src/components/KCodeBlock/KCodeBlock.vue
Changes:
* add a bit more spacing to code block actions container so it doesn't overlap with the scrollbar (screenshot)
* `maxHeight` prop to add `px` to value automatically
=> fix(kcodeblock): spacing and max height prop fixes

docs/components/button.md, docs/components/dropdown.md, docs/components/empty-state.md, docs/components/table.md, docs/guide/migrating-to-version-9.md, sandbox/pages/SandboxEmptyState.vue, sandbox/pages/SandboxTable.vue, src/components/KAlert/KAlert.vue, src/components/KEmptyState/KEmptyState.vue, src/components/KTable/KTable.vue, src/components/KToaster/KToaster.vue, src/types/empty-state.ts
Changes:
`KTable.vue`:
- remove `empty-state-action-button-icon` prop because it was utilizing KIcon - we no longer want to be doing that
- remove `empty-state-icon` - same reason as above
- remove `empty-state-icon-color` - no longer supported, KEmptyState sets the default color for the icon
- remove `empty-state-icon-size` - not supported, icon comes in default size
- add `emptyStateIconVariant` prop
- add `empty-state-action-icon` slot
- all of the above documented in migration guide and reflected in KTable docs
`KEmptyState.vue`:
- add kong icon variant
=> fix(ktable): kemptystate props

docs/components/tree-list.md, docs/guide/migrating-to-version-9.md, sandbox/index.ts, sandbox/pages/SandboxTreeList.vue, sandbox/router/sandbox-routes.ts, src/components/KTreeList/KTreeDraggable.vue, src/components/KTreeList/KTreeItem.vue, src/components/KTreeList/KTreeList.cy.ts, src/components/KTreeList/KTreeList.vue, src/types/tree-list.ts
[Jira](https://konghq.atlassian.net/browse/KHCP-9008)
`KTreeList` component reskin
Links:
- [Kongponents sandbox](https://deploy-preview-2064--kongponents-sandbox.netlify.app/#/treelist)
- [Kongponents docs preview](https://deploy-preview-2064--kongponents.netlify.app/components/tree-list.html)
=> feat(ktreelist): reskin component [KHCP-9008]

src/components/KSlideout/KSlideout.vue
Remove `user-select: none` from title of KSlideout to allow user to select the title
=> fix(kslideout): remove user-select: none from title of KSlideout

docs/components/tooltip.md, src/components/KLabel/KLabel.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.vue, src/components/KTooltip/KTooltip.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-11026
Changes:
* add `aria-labelledby` on KLabel's tooltip
* add `aria-live` attribute in KSelect and KMultiselect
* change element to bind attributes to in KMultiselect
=> fix(klabel, kselect, kmultiselect): a11y attributes [KHCP-111026]

docs/components/copy.md, src/components/KCopy/KCopy.vue
Update `KCopy` to support truncation while expanding to fill the space if it's available by specifying `'auto'` for the `truncationLimit`.
Part of [KHCP-11256](https://konghq.atlassian.net/browse/KHCP-11256).
[KHCP-11256]: https://konghq.atlassian.net/browse/KHCP-11256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(kcopy): support truncationLimit auto [khcp-11256]

sandbox/pages/SandboxTabs.vue, src/components/KTabs/KTabs.cy.ts, src/components/KTabs/KTabs.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-11265
=> fix(ktabs): disabled item remove pointer events none [KHCP-11265]

docs/components/table.md, sandbox/pages/SandboxTable.vue, src/components/KTable/KTable.cy.ts, src/components/KTable/KTable.vue, src/types/table.ts
Add column resize support to `KTable` for [KHCP-11161](https://konghq.atlassian.net/browse/KHCP-11161).
[KHCP-11161]: https://konghq.atlassian.net/browse/KHCP-11161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ktable): add column resize support [khcp-11161]

src/components/KCopy/KCopy.vue
Fix KCopy not using an actual button for its click interaction. This is strictly better because you don’t have to worry about re-implementing button functionality and it’s default accessibility properties.
- There is a pre-existing "Extraneous non-props attributes (class, data-testid) were passed to component but could not be automatically inherited because component renders fragment or text root nodes." warning in this component.
=> fix(kcopy): not using actual button

src/components/KAlert/KAlert.cy.ts, src/components/KEmptyState/KEmptyState.cy.ts
=> fix(kalert,kemptystate): icon slot test

src/components/KCopy/KCopy.vue, src/components/KInput/KInput.vue, src/components/KModal/KModal.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.vue, src/components/KSlideout/KSlideout.vue, src/components/KToaster/KToaster.vue, src/components/KTruncate/KTruncate.vue, src/styles/_mixins.scss, src/styles/mixins/_buttons.scss
Fix using icons as buttons in KModal, KMultiSelect, KSelect, KSlideout, KToaster, and KTruncate.
It’s important to use actual buttons for click interactions to ensure all the expected behavior is made available to users. Native buttons can be focused, handle keyboard interactions correctly, expose their accessibility properties (e.g. `role="button"`), and more all without requiring developer attention beyond using the appropriate markup. It should be noted that other means to expose an accessible name (done here using `aria-label`) are available and can be considered.
See also https://github.com/Kong/kongponents/pull/2113 and https://github.com/Kong/kongponents/pull/2100#discussion_r1553172711.
=> fix: using icons as buttons

src/components/KTreeList/KTreeItem.vue
On smaller screens, the text ends up being center-aligned. This PR aligns left.
=> fix(ktreelist): label alignment

docs/components/card.md, src/types/card.ts
Allow `legend` value in `HeaderTag` type
=> fix(types): allow legend header tag

src/components/KTable/KTable.vue
Fix a bug where visibility preferences were getting overridden by default value.
=> fix(ktable): dont clear visibility prefs on load

docs/components/catalog.md, docs/components/icon.md, docs/components/popover.md, docs/components/renderless/k-component.md, docs/components/renderless/toggle.md, docs/components/skeleton.md, docs/components/table.md, src/components/KToggle/index.ts
Named slots have a `#` shorthand which can be used instead of `v-slot:`. [Ref](https://vuejs.org/guide/components/slots.html#named-slots:~:text=v%2Dslot%20has%20a%20dedicated%20shorthand%20%23%2C%20so%20%3Ctemplate%20v%2Dslot%3Aheader%3E%20can%20be%20shortened%20to%20just%20%3Ctemplate%20%23header%3E.%20Think%20of%20it%20as%20%22render%20this%20template%20fragment%20in%20the%20child%20component%27s%20%27header%27%20slot%22.)
[KHCP-11488](https://konghq.atlassian.net/browse/KHCP-11488)
N/A * ~[ ] **Tests coverage:** test coverage was added for new features and bug fixes~
[KHCP-11488]: https://konghq.atlassian.net/browse/KHCP-11488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: use shorthand for named slots usage in docs [KHCP-11488]

src/components/KTable/ColumnVisibilityMenu.vue
=> feat(ktable): make visibility menu scrollable

docs/components/modal.md, docs/components/popover.md, docs/components/skeleton.md, docs/components/slideout.md, docs/components/toaster.md, src/components/KModal/KModal.cy.ts, src/components/KModal/KModal.vue, src/components/KPop/KPop.cy.ts, src/components/KPop/KPop.vue, src/components/KSkeleton/FullScreenGenericSpinner.vue, src/components/KSkeleton/FullScreenKongSkeleton.vue, src/components/KSkeleton/KSkeleton.cy.ts, src/components/KSkeleton/KSkeleton.vue, src/components/KSlideout/KSlideout.cy.ts, src/components/KSlideout/KSlideout.vue, src/components/KToaster/KToaster.cy.ts, src/components/KToaster/KToaster.vue, src/components/KToaster/ToastManager.ts, src/components/KTooltip/KTooltip.cy.ts, src/components/KTooltip/KTooltip.vue, src/styles/mixins/_loaders.scss
Adds a `zIndex` prop to all overlaying components (that need to be shown above the default layer) so that they can be assigned custom `z-index` values.
Components updated:
- `KModal`
- `KPop`
- `KSlideout`
- `KToaster`
- `KTooltip`
- `KSkeleton`
- `FullScreenKongSkeleton`
- `FullScreenGenericSpinner`
[KHCP-10747](https://konghq.atlassian.net/browse/KHCP-10747)
[KHCP-10747]: https://konghq.atlassian.net/browse/KHCP-10747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add zIndex prop to overlaying components [KHCP-10747]

src/utilities/ShortcutManager.ts
Datadog reported that in `normalizeKeyCode` method, `.replace` was being accessed on `undefined`. So added a check to early return with an empty string in case the parameter passed to the method is `undefined`, or an invalid string.
Extended explanation [here](https://konghq.atlassian.net/browse/KHCP-11186?focusedCommentId=129798)
[Ref Datadog error](https://app.datadoghq.com/rum/error-tracking/issue/4fc5bfdc-e857-11ee-b032-da7ad0900002?query=env%3Aprod%20-%40browser.name%3AHeadlessChrome%20%40issue.age%3A%3C%3D300000&refresh_mode=sliding&view=spans&from_ts=1707996277000&to_ts=1713180277000&live=true)
[KHCP-11186](https://konghq.atlassian.net/browse/KHCP-11186)
~[ ] **Tests coverage:** test coverage was added for new features and bug fixes~
~[ ] **Docs:** includes a technically accurate …
=> fix(ShortcutManager): return empty string for invalid keycode during normalization [KHCP-11186]

src/components/KTable/KTable.vue
Hide column visibility menu when loading/error/empty state and persist initial column widths from table preferences.
=> fix(ktable): column visibility menu button

sandbox/pages/SandboxTable.vue, src/components/KTable/KTable.vue
Fixes choppy behaviour during column resize after getting column width < header content width
=> fix(ktable): resized column choppiness

src/components/KCodeBlock/KCodeBlockIconButton.vue
Adds `inheritAttrs: false` in `KCodeBlockIconButton.vue` so all attributes are bound to `KButton` (instead of `KTooltip` wrapper element)
=> fix(kcodeblock): icon button not to inherit attrs

src/components/KInput/KInput.vue
Added the helper text as a constraint/error description for the input tag via aria attribute
[LevelAccess ticket](https://kong.hub.essentia11y.com/manual-evaluations/65a99b2c7e398d9f95af2af7/results/AMP449/view?linkedPropertyData=64b6a2897bb1382840bc4998%7C64b6a2897bb13892bcbc4992)
[KHCP-11030](https://konghq.atlassian.net/browse/KHCP-11030)
~[ ] **Tests coverage:** test coverage was added for new features and bug fixes~
~[ ] **Docs:** includes a technically accurate README~
[KHCP-11030]: https://konghq.atlassian.net/browse/KHCP-11030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(KInput): add aria label to associate helper text with input [KHCP-11030]

src/components/KCheckbox/KCheckbox.vue, src/components/KCodeBlock/KCodeBlock.vue, src/components/KCopy/KCopy.vue, src/components/KDropdown/KDropdown.vue, src/components/KExternalLink/KExternalLink.vue, src/components/KLabel/KLabel.vue, src/components/KModal/KModal.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KPagination/KPagination.vue, src/components/KPagination/PaginationOffset.vue, src/components/KRadio/KRadio.vue, src/components/KSelect/KSelect.vue, src/components/KSkeleton/KSkeleton.vue, src/components/KSlideout/KSlideout.vue, src/components/KTable/ColumnVisibilityMenu.vue, src/components/KTreeList/KTreeItem.vue, src/components/KTruncate/KTruncate.vue
Adds `title` or `decorative` prop to icons used in components
=> fix(*): add title or decorative prop to icons

docs/components/catalog.md, src/components/KCatalog/KCatalogItem.vue
Adds a `card-footer` slot to the `KCatalogItem` component so that items in a `KCatalog` can leverage a card footer.
=> feat(kcatalogitem): add card-footer slot

src/components/KSelect/KSelect.cy.ts, src/components/KSelect/KSelect.vue
Fixes a bug where KSelect emits `selected` event twice when both `v-model` and `@selected` are provided
=> fix(kselect): fix double emits bug

src/components/KTable/ColumnVisibilityMenu.vue, src/components/KTable/KTable.vue
Fix an issue where initial provided visibility preferences were immediately cleared for [KHCP-11730](https://konghq.atlassian.net/browse/KHCP-11730).
[KHCP-11730]: https://konghq.atlassian.net/browse/KHCP-11730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ktable): init col visibility [khcp-11730]

src/components/KTooltip/KTooltip.vue
it's safe to set `inheritAttrs` to `false` because we have set `v-bind="$attrs"` on `<KPop />` manually
=> fix(ktooltip): suppress vue attr passthrough warning

src/components/KFileUpload/KFileUpload.vue
this prevents the native "No file selected" placeholder from being rendered and causing the placeholder text overlapped
before:
after:
=> fix(kfileupload): force transparent color for the input element

docs/components/table.md, src/components/KTable/KTable.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-11890
=> fix(ktable): emit preferences only in success state [KHCP-11890]

sandbox/pages/SandboxButton.vue, sandbox/pages/SandboxCatalog.vue, sandbox/pages/SandboxTable/SandboxTableActions.vue, src/components/KTable/ColumnVisibilityMenu.vue
This PR removes the deprecated `icon` slot usage in `<TableColumnsIcon>` and all components sandboxes.
=> fix(kbutton): remove deprecated icon slot

src/components/KDropdown/KDropdown.vue
Fixes leaking from KDropdown to other components using KPop styles (scrrenshots)
Before
After
=> fix(kdropdown): fix leaking styles

src/components/KPop/KPop.vue
This PR fixes an issue where two popover elements are present until the transition animation ends.
=> fix(kpop): duplicate popover elements when transitioning

src/components/KTable/KTable.cy.ts, src/components/KTable/KTable.vue, src/types/table.ts
- Copy changes to internal ref on prop change.
- Update tests.
=> fix(ktable): `props.headers` should be reactive [MA-3028]

docs/components/multiselect.md, src/components/KMultiselect/KMultiselect.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-12560
When a placeholder is provided, display it in dropdown input. In selections container, only display _0 items selected_ when no selections have been made
=> fix(kmultiselect): duplicate placeholder [KHCP-12560]

src/components/KSelect/KSelect.vue
Prevent the KSelect input triggering the keyboard on mobile when filtering is not enabled
=> fix(kselect): blur input on click

docs/components/pagination.md, docs/components/table.md, docs/guide/usage.md, package.json, pnpm-lock.yaml, sandbox/index.html, sandbox/pages/SandboxPagination.vue, src/components/KPagination/KPagination.vue, src/components/KPagination/PaginationOffset.vue, src/components/KSelect/KSelect.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-10930
Changes:
* KPaginatiion to automatically detect horizontal overflow and adjust number of displayed pagination items until overflow is fixed
* Styling to stack on mobile (screenshot)
=> fix(kpagination): detect and fix overflow [KHCP-10930]

.github/workflows/publish.yaml, .github/workflows/test.yaml
Reuse the build artifacts from the `test.yaml` workflow when publishing.
=> ci: reuse build artifacts

src/components/KButton/KButton.vue, src/components/KPagination/KPagination.vue, src/components/KPagination/PaginationOffset.vue, src/styles/mixins/_buttons.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-12680
KPagination is throwing hydration errors in SSR mode because of conditional props dependant on screen size. Instead of relying on js for that, add media queries to override certain styles on large and small screens.
=> fix(kpagination): remove dynamic size props [KHCP-12680]

src/components/KCodeBlock/KCodeBlock.vue
Adjusts the line height to center the text in single-line code blocks
Before & After:
JIRA: KM-347
=> fix(kcodeblock): correct the line height for single line code block

sandbox/pages/SandboxPagination.vue, src/components/KPagination/KPagination.vue
If your current page is not in the set of page buttons that KPagination defaults to (e.g. [1] [2] [3] [...] [20] with a current page of `7`). This fix ensures that the correct set of page buttons is displayed plus highlights the button that corresponds to the current page.
Honestly, I've kinda no idea what this is doing (I've no idea what `firstDetached` means for example), but I fiddled with things a little and noticed the hardcoded `false` in related code. Following this I copy/pasta'd some code in from somewhere else that seemed to be doing something important 🤷 and things began to work 😅 
I also added an example to the sandbox which I used to figure this out.
---
FYI: Our use case is that we always pass bookmarkable `?page=7` parameters to our pages, previous to this fix a '7 page …
=> fix(kpagination): ensure currentPage is highlighted

docs/components/prompt.md, src/components/KPrompt/KPrompt.vue
Allow trigger proceed action on _Enter_ upon typing in confirmation text in KPrompt
=> fix(kprompt): proceed on enter

docs/components/tree-list.md, sandbox/pages/SandboxTreeList.vue, src/components/KTreeList/KTreeDraggable.vue, src/components/KTreeList/KTreeList.cy.ts, src/components/KTreeList/KTreeList.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-13028
Adds `group` prop in KTreeList that allows disabling dragging items from one list into another
=> fix(ktreelist): add group prop [KHCP-13028]

sandbox/pages/SandboxSegmentedControl.vue, src/components/KSegmentedControl/KSegmentedControl.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-13152
Update KSegmentedControl button border width and colors to match KButton `appearance="secondary"` styles
=> fix(ksegmentedcontrol): bump border width and colors [KHCP-13152]

src/components/KLabel/KLabel.vue, src/components/KTooltip/KTooltip.vue
Fixes background color for slotted `code` element in KTooltip
=> fix(ktooltip, klabel): slotted code background color

src/components/KTable/KTable.vue, src/components/KTableView/KTableView.vue
The column resizer should ignore right clicks.
Before:
After:
=> fix(ktable, ktableview): `resizeColumns` should ignore right clicks

src/components/KTable/ColumnVisibilityMenu.vue
before:
https://github.com/user-attachments/assets/ae84f9d1-d960-4e32-b9ef-56ab850854ff
after:
https://github.com/user-attachments/assets/14523c68-d46d-4d25-a2dd-5feab7c24d78
=> fix(ktable): mask delay of column visibility menu

src/components/KCard/KCard.vue
Fixes KCard actions content wrapping
=> fix(kcard): actions content wrapping

src/components/KSkeleton/KSkeleton.vue
There is a brief layout shift during the query update in the `KTable`. You can observe this between 0:05 and 0:06 in the video, specifically after typing the second ‘d’ and before the Skeleton appears.
https://github.com/user-attachments/assets/903cf59a-e6be-4aa6-90f9-fc3aaa0bdd86
The issue arises because the Skeleton component is always rendered after a `setTimeout`. This PR addresses the issue by ensuring that when `delayMilliseconds === 0`, the Skeleton is rendered immediately.
https://github.com/user-attachments/assets/b4deee86-ea3c-4e57-a67b-43c5ba14125f
=> fix(skeleton): layout shifting due to delayed rendering

sandbox/pages/SandboxCopy.vue, src/components/KCopy/KCopy.vue
Added `max-width` for the tooltip for `<KCopy>`. I currently set it to `500px` , same as the copy button tooltip. Not sure if we have any design guideline here.
https://github.com/Kong/kongponents/blob/aa5192b3058c5cdd602689dfa3a2a1d54a2f68b5/src/components/KCopy/KCopy.vue#L29-L34
Before:
After:
=> fix(kcopy): truncated text should have max-width on tooltip

sandbox/pages/SandboxTableView/SandboxTableView.vue, src/components/KTable/ColumnVisibilityMenu.vue, src/components/KTable/KTable.vue, src/components/KTableView/KTableView.vue
Jira: https://konghq.atlassian.net/browse/KHCP-13248
KTable and KTableView toolbar default items include bulk actions dropdown (only supported in KTableView) and column visibility menu (screenshot).
Changes:
Instead of hiding toolbar default items in loading and empty states at all times, only hide them in those states when toolbar slot is NOT provided. Otherwise, display those toolbar default items in disabled state to avoid layout shifts when table switches states (e.g. loading -> empty -> loading -> success).
=> fix(ktableview): disable column visibility dropdown [KHCP-13248]

src/components/KDateTimePicker/KDateTimePicker.cy.ts, src/components/KDateTimePicker/KDateTimePicker.vue
We now auto-submit relative timeframe button clicks. Custom (calendar) ranges still require the extra click on "Apply".
https://konghq.atlassian.net/browse/MA-3223
https://deploy-preview-2404--kongponents.netlify.app/components/datetime-picker.html#custom-date-time-and-relative-time-frames
=> feat: autosubmit timeframe button clicks [MA-3223]

docs/components/multiselect.md, sandbox/pages/SandboxMultiselect.vue, src/components/KMultiselect/KMultiselect.cy.ts, src/components/KMultiselect/KMultiselect.vue
Jira: https://konghq.atlassian.net/browse/KHCP-13352
Changes (KMultiselect):
* add `searchPlaceholder` prop that acts as search input placeholder
* in collapsed-context mode - the trigger element is the search input so text passed through `searchPlaceholder` prop displays in the trigger element when no items are selected
* otherwise, `searchPlaceholder` sets a placeholder in search input inside multiselect dropdown
* in non-collapsed-context mode, existing `placeholder` prop (if has value) is used as trigger element text when no items are selected
* add `placeholder` and `searchPlaceholder` props documentation
=> feat(kmultiselect): add search-placeholder prop [KHCP-13352]

docs/components/modal.md
Minor fix in KModal docs example
=> docs(kmodal): fix content slot example

docs/components/multiselect.md, sandbox/pages/SandboxMultiselect.vue, src/components/KMultiselect/KMultiselect.cy.ts, src/components/KMultiselect/KMultiselect.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-13541
Adds `itemCreationValidator` prop for validating user input when `enableItemCreation` is `true`
=> fix(kmultiselect): add item-creation-validator prop [KHCP-13541]

src/components/KCheckbox/KCheckbox.vue, src/styles/mixins/_tables.scss
=> fix(ktable): bulk actions checkboxes should be valign center

package.json, pnpm-lock.yaml, vite.config.ts
[KM-579](https://konghq.atlassian.net/browse/KM-579)
Sass start to show a [deprecation warning](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#js-api-2) since `1.79.0`.
~~This PR migrate the usage to its modern compiler [as we did for `konnect-ui-apps`](https://github.com/Kong/konnect-ui-apps/pull/4514).~~
* See https://github.com/Kong/shared-ui-components/pull/2872
[KM-579]: https://konghq.atlassian.net/browse/KM-579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(*): switch to sass modern api

docs/components/input.md
=> docs(kinput): fix typo

src/components/KPagination/KPagination.vue
[KM-580]
When the currentPage is controlled for kpagination, it may behave differently from when there is no currentPage passed in and add unneeded ellipsis
Before:
After:
[KM-580]: https://konghq.atlassian.net/browse/KM-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kpagination): ensure firstDetached consistency [KM-580]

src/components/KLabel/KLabel.vue
We are now getting a console error when we focused on a tooltip icon:
> Blocked aria-hidden on a <span> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. 
So I made some changes according to the [spec](https://www.w3.org/TR/html-aria/):
* Removed `decorative` for the icon
* Moved `aria-describedby` on label to the icon as `<label>` is [Naming prohibited](https://www.w3.org/TR/html-aria/#dfn-naming-prohibited).
=> fix(klabel): fix aria attributes on tooltip icon

docs/components/input.md, src/components/KInput/KInput.cy.ts, src/components/KInput/KInput.vue
Fixed issue where clicking icons/buttons inside an input caused focus loss. This PR ensures the input remains focused.
Before:
After:
=> fix(kinput): prevent focus loss on icon/button click

src/components/KTableData/KTableData.vue
Addresses: https://github.com/Kong/konnect-ui-apps/pull/4328#pullrequestreview-2374080324
=> fix(ktabledata): show loading when revalidating

.stylelintrc.mjs, docs/components/button.md, docs/vite.config.ts, sandbox/pages/SandboxButton.vue, src/components/KButton/KButton.vue, src/types/button.ts
This PR adds a `none` value to the `<KButton>` `appearance` prop, enabling buttons to render with minimal styling similar to a `<div>`. This allows for fully custom styles while retaining `<KButton>` features like link rendering to links, cursor styles, and disabled states.
- New Appearance: `none`
- Renders `<KButton>` with minimal styles (`border-box`, `cursor`) for custom styling.
- Style Refactoring
- `.k-button` no longer applies primary styles unless the `primary` class is present to make overriding easier.
- Output `primary outline` classes to maintain backward compatibility when `appearance="outline"` (or any other invalid values).
- Disabled Link Behavior
- Disabled links are now unfocusable and cannot be activated with the <kbd>enter</kbd> key.
- Removed `pointer-events: none` …
=> feat(kbutton): add appearance="none" to button

src/components/KPop/KPop.vue
`autoUpdate` starts in the `KPop` component’s mounted hook, continuously calculating the position even when the pop-up is not visible, significant lag when there are many `Kpop` on the page
**Before:**
https://github.com/user-attachments/assets/9936e1b2-3ff3-480c-ba45-435447eca7d6
**After:**
https://github.com/user-attachments/assets/5c2704be-8dc0-44ba-be8a-365984727516
=> refactor(kpop): improve kpop performance on page scrolling

docs/components/table-view.md, docs/components/tabs.md, sandbox/pages/SandboxTabs.vue, src/components/KTabs/KTabs.vue
The issue:
When a link is slotted into anchor slot of a tab, when using keyboard nav, the user needs to press tab twice to navigate to next element (first time the wrapper element `div.tab-link` has focus, then the slotted link element).
Solution:
Add `anchorTabindex` prop that allows set tabindex for `div.tab-link` element. This allows to make only one element in tab focusable.
https://github.com/user-attachments/assets/8d37cb5a-548b-42fd-8652-465be6546780
=> fix(ktabs): slotted anchor link

docs/components/select.md, sandbox/pages/SandboxSelect.vue, src/components/KSelect/KSelect.vue
[KM-637](https://konghq.atlassian.net/browse/KM-637)
Added support for the `before` slot of `<KSelect>`.
[KM-637]: https://konghq.atlassian.net/browse/KM-637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(kselect): add `before` slot

src/types/table.ts
Accept `Record<string, any>` instead of `Record<string, string>` in `cellAttrs` & `rowAttrs` props in KTableView & KTableData.
Explanation:
```
// this isn't valid because style is object, not a string
:cell-attrs="() => ({ style: { width: '100%' }, class: 'foobar' })"
```
=> fix(ktableview, ktabledata): cell-attrs and row-attrs prop type

src/components/KPop/KPop.vue
This PR fixes an issue where the popover disappears when hovered.
KM-653
=> fix(kpop): not enterable

cypress/support/index.ts, src/components/KButton/KButton.cy.ts, src/components/KButton/KButton.vue
KM-644
`to` prop needs to be passed to `<router-link>`. So when `disabled` is passed, we still pass `to` prop to it and delete `href` attribute so that users cannot bypass this grey state by right clicking and open it in a new tab.
=> fix(kbutton): pass to as long as it's a router-link [KM-644]

src/components/KSelect/KSelect.cy.ts, src/components/KSelect/KSelect.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-13895
Selecting a value in KSelect should not trigger `@query-change` event
=> fix(kselect): don't emit query-change on select [KHCP-13895]

src/components/KMultiselect/KMultiselect.cy.ts, src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.cy.ts, src/components/KSelect/KSelect.vue
When filtering items for `<KSelect>` and `<KMultiselect>`, pressing <kbd>enter</kbd> should not trigger form submission.
=> fix(kselect,kmultiselect): enter should not submit form while filtering

src/components/KTabs/KTabs.vue
=> fix(ktabs): minor fix

docs/components/select.md, src/components/KSelect/KSelect.cy.ts, src/components/KSelect/KSelect.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-13908
Update KSelect item creation logic to allow creating an item for any unique string rather than only when search produces no results.
=> fix(kselect): item creation logic [KHCP-13908]

docs/components/radio.md, sandbox/pages/SandboxRadio.vue, src/components/KRadio/KRadio.cy.ts, src/components/KRadio/KRadio.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-13540
Adds `cardOrientation` and `showCardRadio` props
=> fix(kradio): show-card-radio and card-orientation props [KHCP-13540]

src/components/KInputSwitch/KInputSwitch.vue
=> fix(kinputswitch): fix events race condition

docs/components/table-view.md, sandbox/pages/SandboxTableData.vue, sandbox/pages/SandboxTableView/SandboxTableView.vue, src/components/KTableData/KTableData.vue, src/components/KTableView/KTableView.cy.ts, src/components/KTableView/KTableView.vue, src/types/table.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-14234
Changes:
* add `row-expanded` prop to provide an ability to render some rows expanded by default initially
* rename `row-expand` event to `update:row-expanded` and change event payload
* instead of emitting event only when a row is expanded, event is emitted when a row is expanded OR collapsed
* event payload changed from `row: Record<string, any>` object to `{ row: Record<string, any>, expanded: boolean }`
=> fix(ktableview): row-expanded prop and event [KHCP-14243]

docs/components/tabs.md, sandbox/pages/SandboxTabs.vue, src/components/KCodeBlock/KCodeBlock.vue, src/components/KTabs/KTabs.cy.ts, src/components/KTabs/KTabs.vue, src/types/tabs.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-13866
Add `to` property in `Tab` interface to support rendering tabs as links
=> fix(ktabs): allow tab anchors to be links [KHCP-13866]

src/components/KRadio/KRadio.vue
Remove automatic vertical spacing for horizontal KRadio card so that they can be used in both vertical and horizontal layouts
=> fix(kradio): remove horizontal card vertical spacing

src/components/KPagination/PaginationOffset.vue, src/components/KTableView/ColumnVisibilityMenu.vue
- Add missing imports in `PaginationOffset` and `ColumnVisibilityMenu`.
- Use `TableDataHeader` instead of the deprecated `TableHeader`.
=> fix(kpagination,ktableview): add missing import

src/components/KTableView/KTableView.cy.ts, src/components/KTableView/KTableView.vue
Fixing a bug where `KTableView` incorrectly swaps sort direction when changing sort column.
=> fix(ktableview): sort order when changing sort column [KHCP-14449]

src/components/KAlert/KAlert.vue
Update the KAlert `danger` appearance icon to match our design system.
=> fix(kalert): use proper danger icon

src/composables/useUtilities.cy.ts, src/composables/useUtilities.ts
[KM-843](https://konghq.atlassian.net/browse/KM-843)
Fixed the implementation of `getSizeFromString` which was producing `nonepx` in `<KCodeBlock>`.
Before:
After:
[KM-843]: https://konghq.atlassian.net/browse/KM-843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kcodeblock): fix maxHeight and getSizeFromString util

docs/components/codeblock.md, sandbox/pages/SandboxCodeBlock.vue, src/components/KCodeBlock/KCodeBlock.cy.ts, src/components/KCodeBlock/KCodeBlock.vue
Add new `highlightedLineNumbers` prop to manually set highlighting without requiring search.
=> feat(kcodeblock): add highlighted line numbers prop

.github/workflows/pr-on-close.yaml, .github/workflows/renovate-auto-approve.yaml
=> ci: rename workflow jobs [KHCP-14529]

.vscode/settings.json, docs/components/codeblock.md, sandbox/pages/SandboxCodeBlock.vue, src/components/KCodeBlock/KCodeBlock.cy.ts, src/components/KCodeBlock/KCodeBlock.vue, src/utilities/lineHighlighting.cy.ts, src/utilities/lineHighlighting.ts
[KM-886](https://konghq.atlassian.net/browse/KM-886)
[KHCP-14552](https://konghq.atlassian.net/browse/KHCP-14552)
This PR:
1. Introduces support for line highlighting syntax (e.g., `"2,4,6-12"`) for the `<KCodeBlock>` component’s `highlighted-line-numbers` prop. I recommend using this approach over arrays, as primitive values are less likely to trigger unnecessary re-renders. This is particularly advantageous compared to binding array literals like `:highlighted-line-numbers="[2, 4, 6]"`.
2. Improves the line navigation behavior to prevent scrolling each time the “Next match” or “Previous match” button is clicked, which reduce the pain for consecutive clicks.
3. Enhances line matching performance, particularly when dealing with multiple matches for a lengthy section of code.
[KM-886]: …
=> feat(kcodeblock): support line highlight syntax

src/components/KInput/KInput.vue
To fix the issue when clicking the mask-toggle button triggers a form submission.
slack: https://kongstrong.slack.com/archives/C05UE909XU5/p1736469294982699
After fix: 
https://github.com/user-attachments/assets/ec8d9751-f031-4b39-a7cd-9481c7e39d37
=> fix(kinput): add type button to mask toggle

docs/components/table-data.md
Addresses: https://konghq.atlassian.net/browse/KHCP-14443
Remove confusing part in KTableData `fetcherCacheKey` prop usage documentation
=> docs(table-data): fetcher-cache-key usage [KHCP-14443]

src/components/KMultiselect/KMultiselect.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-14366
Add `min-height: 24px;` on selected badges element to prevent it from jumping once the first item is selected
=> fix(kmultiselect): select jump glitch [KHCP-14366]

.github/workflows/auto-approve.yaml, .github/workflows/renovate-auto-approve.yaml
Temporarily disabling auto-approve for security reasons. 
Context: github.actor dependabot or renovate can cause security vulnerabilities. Pausing this auto approval until this can be looked into.
=> chore(*): disable workflow

.stylelintrc.mjs, sandbox/pages/SandboxBadge.vue, src/styles/mixins/_badges.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-14774
Fixes slotted link styles in KBadge
Before
After
Also fixes `selector-pseudo-class-no-unknown` stylelint flagging `:deep` selector (screenshot)
=> fix(kbadge): slotted link styles [KHCP-14774]

docs/components/tree-list.md, sandbox/pages/SandboxTreeList.vue, src/components/KTreeList/KTreeDraggable.vue, src/components/KTreeList/KTreeItem.vue, src/components/KTreeList/KTreeList.cy.ts, src/components/KTreeList/KTreeList.vue
https://konghq.atlassian.net/browse/KHCP-14716
- add `collapsible` prop to enable collapse/expand feature.
- add `collapseAll` prop to allow initial collapse/expand for all items.
- add docs
- add component tests
=> feat(ktreelist): add collapse/expand option [KHCP-14716]

src/components/KTreeList/KTreeDraggable.vue
Add `filter` prop in KTreeList to make sure item cannot be dragged by grabbing the expand / collapse handle so that clicks on caret never trigger unintentional dragging
=> fix(ktreelist): collapse handle click behavior

src/components/KMultiselect/KMultiselect.vue, src/components/KMultiselect/KMultiselectItems.vue, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItems.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-13956
Fixes broken arrow navigation in KSelect and KMultiselect
Verification steps:
1. Find a sortable instance of KSelect and/or KMultiselect in sandbox or docs
2. Type a query in and after the component shows the results, remove it
3. Try navigating through items using up and down arrows - it should work correctly
=> fix(kselect, kmultiselect): filtered arrow navigation [KHCP-13956]

docs/components/textarea.md, sandbox/pages/SandboxTextarea.vue, src/components/KCodeBlock/KCodeBlock.vue, src/components/KTextArea/KTextArea.cy.ts, src/components/KTextArea/KTextArea.vue, src/utilities/browser.ts
- Introduced a new `autosize` prop that dynamically adjusts the height of the textarea based on its content.
- Added an enhancement for `resizable` textareas where double-clicking the drag handle resets the default sizing (which Firefox supports natively)
- Added a new browser utilities module for handling user-agent detection and ensuring browser compatibility.
=> feat(ktextarea): add `autosize` for `<KTextArea>`

src/components/KCodeBlock/KCodeBlock.vue
[KM-919](https://konghq.atlassian.net/browse/KM-919)
[KM-919]: https://konghq.atlassian.net/browse/KM-919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kcodeblock): prevent unexpected horizontal scrollbar

src/components/KTableData/KTableData.cy.ts, src/components/KTableData/KTableData.vue
[KM-946](https://konghq.atlassian.net/browse/KM-946)
- When `client-sort` is enabled, exclude sort-related parameters from the cache key.
- Removed an unintended `console.log`.
Konnect Preview: https://github.com/Kong/konnect-ui-apps/pull/5733
[KM-946]: https://konghq.atlassian.net/browse/KM-946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ktabledata): client sort should not trigger cache invalidation

docs/components/tree-list.md, sandbox/pages/SandboxTreeList.vue, src/components/KTreeList/KTreeDraggable.vue, src/components/KTreeList/KTreeList.vue
Add a new `ignoreDragSelectors` prop that can be utilized to disable dragging on slotted elements within the `KTreeList`
=> feat(ktreelist): add prop to filter draggable element selectors

src/components/KModal/KModal.cy.ts, src/components/KModal/KModal.vue
https://konghq.atlassian.net/browse/KHCP-15048
This PR fixes issue with backdrop closing modal during text selection or drag outside, see video below:
| Before | After |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/8ab96894-d511-468f-b172-ea4389773c3f" /> | <video src="https://github.com/user-attachments/assets/929f9b10-b77a-4014-b8aa-ec5a2525ef46" /> |
=> fix(kmodal): prevent backdrop close when selecting text [KHCP-15048]

docs/components/input-switch.md, sandbox/pages/SandboxInputSwitch.vue, src/components/KInputSwitch/KInputSwitch.vue
Add `tooltipAttributes` prop in KInputSwitch to give a way to control tooltip placement when `disabledTooltipText` prop is used
Before
After
=> fix(kinputswitch): add tooltipattributes prop

docs/components/tooltip.md, src/components/KBadge/KBadge.vue
Assign `tabindex="0"` to badge content element if badge displays tooltip
=> fix(kbadge): tabindex when has tooltip

src/utilities/browser.ts
`navigator.platform` is undefined in some browser environments and throwing an error in SSR builds.
Issue introduced in https://github.com/Kong/kongponents/pull/2587
=> fix(browser): platform is undefined

docs/.vitepress/theme/index.scss
=> docs: improve code section scrollbar color scheme

docs/components/table-data.md, src/components/KTableData/KTableData.vue
[KM-952](https://konghq.atlassian.net/browse/KM-952)
Reasoning: see #2614 for details.
This PR offers an alternate way to mitigate the original issue discussed in #2614.
I'm also I’m still considering whether to expose the SWRV options inside `<KTableData>` as a prop, which would support more declarative revalidation.
[KM-952]: https://konghq.atlassian.net/browse/KM-952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ktabledata): expose revalidate method

src/components/KModal/KModal.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-15360
Fix issue in KModal where it's not scrollable vertically when `content` slot is used
=> fix(kmodal): kmodal not scrollable when content slot used [KHCP-15360]

sandbox/pages/SandboxTableView/SandboxTableView.vue, src/components/KDropdown/KDropdownItem.vue, src/components/KTableView/KTableView.cy.ts, src/components/KTableView/KTableView.vue, src/styles/mixins/_tables.scss, src/types/dropdown.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-15221
Add horizontal scroll overlay indicators in KTableView
Demo: https://www.loom.com/share/f5a1c853a6954601a44aa6d4cad9a5b8?sid=4af28c32-ee9b-449c-90ed-271fe21cf8eb
=> fix(ktableview): horizontal scroll overlay indicators [KHCP-15221]

src/components/KLabel/KLabel.vue
Fix the required indicator bottom value did not include  $kLabelRequiredDotSize to calculate
The value of the red dot `bottom` did not include the `$kLabelRequiredDotSize` into its calculation, this PR simply brings the value to the equation so that the red dot can be properly aligned with the label text.
| Before | After |
| ------ | ----- |
| ![CleanShot 2025-03-11 at 17 48 52@2x](https://github.com/user-attachments/assets/a0936c1a-67e4-40ec-a5c6-ce18b322d972) |  ![CleanShot 2025-03-11 at 17 49 27@2x](https://github.com/user-attachments/assets/3e56f1a8-cdf7-48a2-b92d-745d42df693b) |
=> fix(klabel): required indicator icon not aligned properly [KM-1034]

src/types/popover.ts
Allow `width` property in `PopoverAttributes` type for backward compatibility
=> fix(types): popover attributes allow width

src/components/KTable/KTable.vue
A new container class `table-container` has been introduced which nests all styles and has not been added to the KTable component.
---
Related commit that introduced `table-container` class: https://github.com/Kong/kongponents/commit/5782168b1ce5f15283bec327fcf9cb1e9bbd6ddf
Before
After
=> fix(ktable): missing styles, no container class

src/components/KTableView/KTableView.vue
Don't set `tabindex` on rows when `rowLink` prop is provided
=> fix(ktableview): row links tabindex [KHCP-15202]

.github/workflows/get-changed-files.yaml
Use kong changed-files github actions as the original upstream has been compromised and shut down. See #incident-456.
=> fix(actions): use kong changed files

src/styles/mixins/_tables.scss
=> fix(ktableview): make header non-sticky in firefox

docs/components/popover.md, sandbox/pages/SandboxPop.vue, src/components/KDropdown/KDropdown.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KPop/KPop.vue, src/components/KPop/KPopTeleportWrapper.vue, src/components/KSelect/KSelect.vue, src/components/KTooltip/KTooltip.vue, src/types/popover.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-15449
Add `target` prop in KPop to specify a selector for the element where the popover will be teleported. Also expose it through `kpopAttributes` prop for KTooltip
=> feat(kpop): add target prop and conditional teleport [KHCP-15449]

src/components/KBreadcrumbs/KBreadcrumbs.vue, src/types/breadcrumbs.ts
Update KBreadcrumb props declaration with `type` instead of object. [KM-1102]
Preview https://github.com/Kong/konnect-ui-apps/pull/6331
[KM-1102]: https://konghq.atlassian.net/browse/KM-1102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(kbreadcrumb): typescript improvement [KM-1102]

src/components/KMultiselect/KMultiselect.vue, src/components/KMultiselect/KMultiselectItem.vue, src/components/KMultiselect/KMultiselectItems.vue, src/components/KSelect/KSelect.vue, src/components/KSelect/KSelectItem.vue, src/components/KSelect/KSelectItems.vue
Addresses:
https://konghq.atlassian.net/browse/KHCP-15520
https://konghq.atlassian.net/browse/KHCP-15522
KSelect and KMultiselect arrow navigation impprovements:
KSelect:
- when has selected item
- upon pressing up or down keys, navigation starts from selected item
- when does not have selected item
- upon pressing down key, navigation starts with the very first selectable item
- upon pressing down key, navigation starts with the very last selectable item
- fix outline offset for items in `focus-visible` state
KMultiselect:
- upon pressing down key, navigation starts with the very first selectable item
- upon pressing down key, navigation starts with the very last selectable item
- fix outline offset for items in `focus-visible` state
=> fix(kselect, kmultiselect): arrow navigation improvements [KHCP-15520]

docs/components/table-view.md, sandbox/pages/SandboxTableView/SandboxTableView.vue, src/components/KTableView/KTableView.vue, src/styles/mixins/_tables.scss, src/types/table.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-15528
Adds `teleportTarget` prop for passing the teleport target element selector KTableView-rendered tooltips will be teleported to (defaults to `body`).
Testing instructions:
In KTableView and KTableData sandbox and docs, make sure column header tooltips render where they are supposed to be and there are no errors in the console.
Before (all browsers)
After
Before (Firefox only)
After
=> fix(ktableview): add tooltip-target prop [KHCP-15528]

src/components/KInput/KInput.vue, src/types/input.ts
[KM-1139]
TypeScript improvements for `KInput` component.
[KM-1139]: https://konghq.atlassian.net/browse/KM-1139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(k-input): typescript improvements for k-input

package.json, pnpm-lock.yaml
There is no longer usage of `axios` in the repository; remove the dependency
=> fix(deps): remove axios

src/components/KTabs/KTabs.vue
[KM-1192](https://konghq.atlassian.net/browse/KM-1192)
Reuse the logic in `<KButton>` that handles `to`, `disabled`, etc.
- Preview: https://github.com/Kong/konnect-ui-apps/pull/6533
[KM-1192]: https://konghq.atlassian.net/browse/KM-1192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ktabs): use kbutton for ktabs

src/components/KSkeleton/KSkeletonBox.vue
[KM-1247](https://konghq.atlassian.net/browse/KM-1247)
`KSkeletonBox` is not internal and the default values should be provided.
[KM-1247]: https://konghq.atlassian.net/browse/KM-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kskeleton): fix kskeletonbox default value

src/types/file-upload.ts, src/types/input.ts, src/types/select.ts
[KM-1093](https://konghq.atlassian.net/browse/KM-1093)
`@default` is the correct annotation tag for most related toolings, eg. JSDoc, TSDoc, TypeDoc, etc.
[KM-1093]: https://konghq.atlassian.net/browse/KM-1093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(*): fix `@default` annotation

src/components/KRadio/KRadio.vue
In `KRadio`, `data-testid` is applied to `input` element. However, for card radio, most of the actual click area is taken up by the `label` instead of the `input`. But since the `data-testid` was on the `input` element and not on the `label`, Datadog wasn't registering any clicks on the card radio.
This PR adds a `data-testid` to the label for radio cards, by appending `-label` to the `data-testid` applied to the `KRadio`, so that clicks on anywhere on the component get registered in Datadog.
=> fix(k-radio): apply data-testid to wrapper for card radio [KHCP-16147]

src/components/KRadio/KRadio.vue
#2747 was merged without rebasing with the changes in #2739, which removed the `const props = defineProps` from the file and caused lint errors
=> fix(k-radio): lint error

src/components/KCopy/KCopy.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KPagination/KPagination.vue, src/components/KSelect/KSelect.vue, src/components/KTruncate/KTruncate.vue
The lifecycle hook `onUnmounted` is triggered as soon as all child components are unmounted. When the `unobserve` method on the resize-observer ref is being called at this point with the param of a ref to a child element, the child element is `null` and the `unobserve` method returns without cleaning up the resize observer.
=> fix: resize-observer not cleaned up

src/components/KCodeBlock/KCodeBlock.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-14696
Fix little jump in KCodeBlock docs when searching through code
=> fix(kcodeblock): docs search height jump [KHCP-14696]

src/types/button.ts, src/types/radio.ts, src/types/segmented-control.ts, src/types/slideout.ts
[KM-1279](https://konghq.atlassian.net/browse/KM-1279)
Fixes the type errors mentioned at https://github.com/Kong/kongponents/issues/2753.
[KM-1279]: https://konghq.atlassian.net/browse/KM-1279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(types): mark all slots as optional

src/components/KTableData/KTableData.vue
Bound `paginationAttributes` are getting overridden by the component which is incorrect.
=> fix(ktabledata): prioritize bound pagination attributes

docs/components/file-upload.md, src/components/KFileUpload/KFileUpload.vue, src/types/file-upload.ts
[KM-1293](https://konghq.atlassian.net/browse/KM-1293)
Fixed a runtime error when user click cancel in the system file dialog.
[KM-1293]: https://konghq.atlassian.net/browse/KM-1293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(kfileupload): fix filelist conversion, simplify code

docs/components/multiselect.md, sandbox/pages/SandboxMultiselect.vue, src/components/KButton/KButton.vue, src/components/KMultiselect/KMultiselect.cy.ts, src/components/KMultiselect/KMultiselect.vue, src/types/multi-select.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-17046
Adds `item-badge-icon` slot in KMultiselect
=> feat(kmultiselect): add item-badge-icon slot [KHCP-17046]

docs/components/datetime-picker.md, sandbox/pages/SandboxDateTimePicker.vue, src/components/KDateTimePicker/CalendarWrapper.vue, src/components/KDateTimePicker/KDateTimePicker.vue, src/types/date-time-picker.ts
https://konghq.atlassian.net/browse/MA-4122
Adds validation to prevent users from selecting a start time that exceeds the end time when using the custom time range picker.
- Added hasCalendarError reactive flag and bound it to the submit button to prevent submission on invalid ranges
- Introduced helpText to surface validation errors to the user (e.g., "Start time cannot exceed end time")
- Added input-error class styling for invalid inputs
- Extended watchers on startTimeValue and endTimeValue to validate the full range on each update
- Corrected a bug in the endTimeParts assignment (was reading startTimeValue)
=> fix(kdatetimepicker): add validation for start and end time

docs/components/radio.md, sandbox/pages/SandboxRadio.vue, src/components/KRadio/KRadio.cy.ts, src/components/KRadio/KRadio.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-17236
Add `tooltip` slot in KRadio card
=> fix(kradio): card tooltip slot [KHCP-17236]

src/components/KTableData/KTableData.vue
Fixes the bug where if a values is passed through `initialFetcherParams.sortColumnKey` that doesn't correspond to any of the `key` parameters passed through `headers` prop, KTableData will try to destructure an `undefined` and break
=> fix(ktabledata): initial sorting table header undefined

sandbox/pages/SandboxDateTimePicker.vue, src/components/KDateTimePicker/CalendarWrapper.vue, src/components/KDateTimePicker/KDateTimePicker.cy.ts, src/components/KDateTimePicker/KDateTimePicker.vue
https://konghq.atlassian.net/jira/software/c/projects/MA/boards/109
This PR replaces the initialization approach in KDateTimePicker from `onMounted` to  a `watch` on `modelValue` with `{ immediate: true }`. This ensures the component properly initializes and also reacts to external model value changes consistently.
- Set the time input values correctly when v calendar model updates
- Use `watch` with `{ immediate: true }` instead of `onMounted` for both initializing the state and reacting to external changes to `modelValue`
- Added a reset time range button in the sandbox to simulate external updates to the model value
- When updating the time range externally (e.g. via zoom), the time portion was incorrectly reset to the current time instead of preserving the intended value.
- Updating …
=> fix(kdatetimepicker): Update internal state on modelValue changed

docs/components/table-data.md, sandbox/pages/SandboxTableData.vue, src/components/KTableData/KTableData.vue
Fixing the issue in KTableData where `fetcher` is firing twice on component mount when `clientSort` is `false`
=> fix(ktabledata): fetcher firing twice when initial sorting provided

src/components/KDateTimePicker/CalendarWrapper.vue, src/components/KDateTimePicker/KDateTimePicker.cy.ts, src/components/KDateTimePicker/KDateTimePicker.vue
https://konghq.atlassian.net/browse/MA-4158
Reset time inputs if the date picker popover is closed without applying changes.
=> fix: reset time picker values if date picker is "cancelled"

src/components/KAlert/KAlert.vue, src/components/KToaster/KToaster.vue, src/styles/mixins/_badges.scss
Addresses: https://konghq.atlassian.net/browse/KHCP-17541
Pick up `kui-color-text-info` and `kui-color-background-info` tokens for `info` apearances in KAlert, Kbadge and KToaster
=> fix(kalert, kbadge, ktoaster): info appearance tokens [KHCP-17541]

src/components/KDateTimePicker/CalendarWrapper.vue, src/components/KDateTimePicker/KDateTimePicker.cy.ts
https://konghq.atlassian.net/browse/MA-4240
When clearing the time input calendar v-model was ending up as an "Invalid Date" -> date-fns was throwing error when attempting to format the invalid date.
Changes
- Check if new time value is defined in watcher
- Wrap date-fns format() fn in a try - catch and console.warn the error
=> fix: better error handling for time inputs

docs/components/empty-state.md, sandbox/pages/SandboxEmptyState.vue, src/components/KEmptyState/KEmptyState.cy.ts, src/components/KEmptyState/KEmptyState.vue, src/types/empty-state.ts
Add `action-button-icon` slot in KEmptyState to make rendering icon in action button easy (screenshot)
=> fix(kemptystate): add action-button-icon slot

src/components/KDateTimePicker/KDateTimePicker.vue, src/components/KDropdown/KDropdown.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.vue
Increase spacing betweet popover and trigger elements in KDropdown as per component [Figma](https://www.figma.com/design/Yze0SWXl5nKjR0rFdilljK/Components?node-id=466-9443)
Before
After
=> fix(*): kpop offset [KHCP-17692]

sandbox/pages/SandboxModals.vue, src/components/KModal/KModal.vue
Fix KModal height on smaller viewport when `maxHeight` is provided
Before
https://github.com/user-attachments/assets/0b2269e7-32ea-495a-8214-1654b3fc652e
After
https://github.com/user-attachments/assets/02da6eeb-6693-4617-9c6b-158004686911
=> fix(kmodal): kmodal max-height on shorter viewports

docs/components/file-upload.md, sandbox/pages/SandboxFileUpload.vue, src/components/KFileUpload/KFileUpload.cy.ts, src/components/KFileUpload/KFileUpload.vue, src/components/KTreeList/KTreeDraggable.vue, src/types/file-upload.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-17516
* Add `appearance="dropzone"` prop to support dropzone appearance in KFileUpload ([Figma](https://www.figma.com/design/TKG7r9QQSMDsBRfR0Gphpc/Drop-zone?node-id=0-1&p=f&t=4q58NCsIsnAMjThc-0))
=> feat(kfileupload): allow drag & drop, dropzone appearance [KHCP-17516]

docs/components/multiselect.md, sandbox/pages/SandboxDropdown.vue, sandbox/pages/SandboxMultiselect.vue, sandbox/pages/SandboxSelect.vue, src/components/KDropdown/KDropdown.vue, src/components/KMultiselect/KMultiselect.vue, src/components/KSelect/KSelect.vue, src/types/dropdown.ts, src/types/multi-select.ts, src/types/popover.ts, src/types/select.ts
[KM-1721](https://konghq.atlassian.net/browse/KM-1721)
Currently, the `target` option is not supported in the `kpop-attributes` prop for `<KDropdown>`, `<KSelect>`, and `<KMultiselect>` at the type level.
This PR updates the approach by applying styles to the popover contents within a global `<style>`, ensuring teleportation works as intended.
For example, we may need to teleport the dropdown popover to `body` or other top-level container to make the dropdown appear above everything else.
[KM-1721]: https://konghq.atlassian.net/browse/KM-1721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(*): support specifying target for dropdown/select/multiselect popovers

src/components/KTableData/KTableData.cy.ts, src/components/KTableData/KTableData.vue, src/components/KTableView/KTableView.cy.ts, src/components/KTableView/KTableView.vue
Add watchers for `tablePreferences` in KTableView and KTableData in case `tablePreferences` are updated later after component has mounted (issue discovered in https://github.com/Kong/konnect-ui-apps/pull/8561 where `tablePreferences` fetched from the API didn't work correctly in tables).
=> fix(ktableview, ktabledata): table preference wathcers
